module.exports = {
  ACCOUNT_CREATED: 'Conta criada',
  BY_CREATING_AN_ACCOUNT_YOU_AGREE_OUR: 'Ao criar uma conta, você concorda com os nossos',
  COMPANY: 'empresa',
  FIRST_NAME: 'nome',
  I_AM_A: 'Eu sou um',
  I_WANT_TO_RECEIVE_NEWS_ABOUT_TAGO: 'Quero receber notícias sobre a TagoIO',
  I_WILL_BUILD_APPLICATIONS_TAGO: 'Vou desenvolver aplicativos na TagoIO',
  LAST_NAME: 'sobrenome',
  PASSWORD_MUST_CONTAIN_AT_LEAST_SIX_CHARACTERS: 'A senha deve conter pelo menos 6 caracteres',
  RETURN_TO_LOGIN_PAGE: 'Retornar para página de autenticação',
  SIGN_IN_TO_YOUR_ACCOUNT: 'faça login',
  SIGN_UP: 'Registre-se',
  TERMS_AND_CONDITIONS: 'Termos & Condições',
  WE_JUST_NEED_TO_CONFIRM_YOUR_EMAIL: 'Precisamos confirmar seu e-mail. Verifique seu e-mail para mais detalhes',
};
