module.exports = {
  ADD_MARKER: 'Agregar pin a esta layer',
  ADD_LAYER: 'Añadir capa',
  DEFINE_EMBED_TO_APPEAR_TOOLBOX: 'Defina una incrustación para que aparezca en la caja de herramientas',
  DEFINE_LABEL_TO_APPEAR_TOOLBOX: 'Defina una etiqueta para que aparezca en la caja de herramientas',
  DEFINE_IMAGE_EMBED_APPEAR_TOOLBOX: 'Definir una imagen o una incrustación para que aparezca en la caja de herramientas',
  DO_YOU_REALLY_DELETE_LAYER: '¿Realmente quieres eliminar esta capa?',
  DO_YOU_REALLY_DELETE_PIN: '¿Realmente quieres eliminar este pin?',
  EDIT_LAYER: 'Editar capa',
  EDIT_MARKER: 'Editar pin',
  ENTER_VALUE_VARIABLE: 'ingrese el valor de este pin',
  ICON_MARKER: 'Defina un ícono para este pin',
  IMAGE_MARKER: 'Definir una imagen para que aparezca en la información sobre herramientas',
  VALUE_MARKER: 'Defina el valor para este pin',
  VARIABLE_MARKER: 'Define dónde se almacenará este pin',
};
