module.exports = {
  CONTACT_US_FOOTER: 'Contact us',
  TAGO_NAME: 'Tago LLC',
  TAGO_ADDRESS: '1017 Main Campus Drive, Suite 2300',
  TAGO_CITY: 'Raleigh, NC 27606 - USA',
  TAGO_PHONE_TEXT: 'Phone:',
  TAGO_PHONE_NUMBER: '(800) 607-7410',
  TAGO_PHONE_HREF: 'tel:8006077410',
  TAGO_EMAIL_TEXT: 'E-mail:',
  TAGO_EMAIL_ADRESS: 'contact@tago.io',
  TAGO_EMAIL_HREF: 'mailto:contact@tago.io',
  TAGO_RESERVED_SYMBOL: '©',
  TAGO_RESERVED: ' - TAGO LLC. ALL RIGHTS RESERVED',
  ABOUT_US: 'About us',
  ABOUT_US_DESCRIPTION: 'Tago offers an end-to-end cloud platform that transforms the way businesses create value from connected products and user interactions.',
  OUR_LINKS_FOOTER: 'Our links',
  TERMS_SUPPORT_FOOTER: 'Terms of Support',
  PRIVACY_FOOTER: 'Privacy',
  FAQ_FOOTER: 'FAQ',
  BLOG_FOOTER: 'Blog',
  DOCUMENTATION_FOOTER: 'Documentation',
  COMMUNITY_FOOTER: 'Community',
  GITHUB_FOOTER: 'GitHub',
  API_FOOTER: 'API',
};
