module.exports = {
  COMMUM_NEXT: 'Proximo',

  WELCOME_GET_STARTED: 'Vamos começar',
  WELCOME_CONNECT_DEVICE: 'Conecte o dispositivo',
  WELCOME_CONNECT_DEVICE_DESC: 'Conecte qualquer dispositivo que já tenha construído um driver para. Siga nossas diretrizes para conectar seu próprio dispositivo facilmente.',
  WELCOME_BUILD_APP: 'Construa seu aplicação',
  WELCOME_BUILD_APP_DESC: 'Combine dados de diferentes tipos de dispositivos dentro da sua própria aplicação. Acesse sua conta em www.tago.io e comece a construir agora.',
  WELCOME_SHARE_ANY: 'Compartilhe com qualquer um',
  WELCOME_SHARE_ANY_DESC: 'Compartilhe seus dashboards com qualquer pessoa usando opções privadas ou públicas. Outros receberão atualizações em tempo real.',

  LOGIN_EMAIL: 'E-mail',
  LOGIN_PASSWORD: 'Senha',
  LOGIN_BTN_SIGNIN: 'Entrar',
  LOGIN_BTN_SIGNUP: 'Criar uma conta',

  SECTION_DASHBOARD: 'Painéis',
  SECTION_EXPLORE: 'Explore',
  SECTION_NOTIFICATION: 'Notificações',
  SECTION_SETTINGS: 'Configurações',

  SETTINGS_TOUCHID: 'Ativar TouchID',
  SETTINGS_NOTIFICATIONS: 'Notificações',
  SETTINGS_FULLSCREEN: 'Tela cheia na horizontal',
  SETTINGS_KEEPAWAKE: 'Manter acordado',
  SETTINGS_LOGOUT: 'Sair',
  SETTINGS_VERSION: 'Versão:',

  NOTIFICATIONS_ACCEPTED: 'Aceito',
  NOTIFICATIONS_DECLINED: 'Recusou',
  NOTIFICATIONS_ACCEPT: 'Aceitar',
  NOTIFICATIONS_DECLINE: 'Recusar',
  NOTIFICATIONS_IGNORE: 'Ignorar',
  NOTIFICATIONS_GOTODASH: 'Ir para o Painél',
  NOTIFICATIONS_APPSETTINGS: 'Configurações da aplicação',
  NOTIFICATIONS_NEWUSERREGISTERED: 'Novo usuário registrado',
  NOTIFICATIONS_NEWUSERREGISTERED_DESC: '$0$ acabou de criar uma conta na Tago. O item que você compartilhou está disponível para ele aceitar',
  NOTIFICATIONS_SHAREPROFILE: 'Compartilhamento de perfil',
  NOTIFICATIONS_SHAREPROFILE_DESC: '$0$ deseja compartilhar o perfil com você',
  NOTIFICATIONS_SHAREREQUEST_DASH: 'Solicitação de compartilhamento - Painél',
  NOTIFICATIONS_SHAREREQUEST_DASH_DESC: '$0$ deseja compartilhar o painél $1$ com você',
  NOTIFICATIONS_SHAREREQUEST_BUCKET: 'Solicitação de compartilhamento - Bucket',
  NOTIFICATIONS_SHAREREQUEST_BUCKET_DESC: '${notification.ref_from.name} eseja compartilhar o bucket ${notification.ref_id.name} com você',

  EXPLORER_SHOWALL: 'Mostre tudo',
  EXPLORER_TRANSPORTATION: 'Transporte',
  EXPLORER_HOME: 'Casa',
  EXPLORER_AGRICULTURE: 'Agricultura',
  EXPLORER_ENERGY: 'Energia',
  EXPLORER_INDUSTRIAL: 'Industrial',
  EXPLORER_ALREADYADDED: 'Já adicionado',
  EXPLORER_BY: 'Por',
  EXPLORER_FILTERCATEGORY: 'Filtrar por Categoria',
  EXPLORER_SEARCHFORMODEL: 'Procure por modelo, marca ou aplicativo ...',
  EXPLORER_CANCEL: 'Cancelar',
  EPLORER_COMPATIBLE: 'Dispositivos compatíveis:',
  EXPLORER_HOWTOALERT: 'Como instalar',
  EXPLORER_HOWTOINSTALL: 'Como instalar esta aplicação?',
  EXPLORER_ADDAPPLI: 'Adicionar aplicação',
  EXPLORER_CONFIGURE: 'Configurar',
  EXPLORER_DOWANTCONT: 'Você quer continuar?',
  EXPLORER_THISACTIONWILL: 'Esta ação irá adicioná-lo à sua lista de painéis.',
  EXPLORER_NO: 'Não',
  EXPLORER_YES: 'Sim',
  EXPLORER_ENTERPIN: 'Isso requer um código PIN. Digite o código fornecido pelo criador.',
  EXPLORER_ENTERCODE: 'Digite o código requerido...',
  EXPLORER_ADD: 'Adicionar',
  EXPLORER_OOPS: 'Opa, algo deu errado',
  EXPLORER_BACK: 'Voltar',
  EXPLORER_DONE: 'Pronto!',
  EXPLORER_YOUWILLRECEIVE: "Você receberá uma notificação quando ela estiver disponível na sua conta. Não se preocupe, isso levará apenas alguns segundos.",
  EXPLORER_BACKTOEXPLORE: 'Voltar para o Explore',
  EXPLORER_LOADING: 'Estamos trabalhando nisso...',

  DASHBOARD_SHARE_ONEHOUR: 'Compartilhar por uma hora',
  DASHBOARD_SHARE_ENDDAY: 'Compartilhar até o final do dia',
  DASHBOARD_SHARE_INDEF: 'Compartilhar Indefinidamente',
  DASHBOARD_SHARE_CANCEL: 'Cancelar',
  DASHBOARD_SHARE_EMAIL: 'Digite o e-mail do usuário',
  DASHBOARD_SHARE_INVITE: 'Convidar',
  DASHBOARD_SHARE_ALLOWOTHERS: 'Permitir que o usuário compartilhe com outras pessoas?',
  DASHBOARD_SHARE_NO: 'Não',
  DASHBOARD_SHARE_YES: 'Sim',
  DASHBOARD_SHARE_INVEMAIL: 'Estrutura de email inválida',
  DASHBOARD_SHARE_TRYA: 'Tente novamente',
  DASHBOARD_SHARE_YOUSHARE: 'Você compartilhou um painel com uma data de expiração maior que a data de expiração do compartilhamento que foi feito para você. O compartilhamento para:',
  DASHBOARD_SHARE_WILLEXP: 'irá expirar em: $0$',
  DASHBOARD_SHARE_OK: 'Certo',
  DASHBOARD_SHARE_SHARESUCESS: 'Compartilhamento feito',
  DASHBOARD_SHARE_FAIL: 'Falha no compartilhamento',
  DASHBOARD_SHARE_USERINVITED: 'O usuário foi convidado para acessar este painel',
  DASHBOARD_SHARE_NOTALLOWED: 'Você não tem direitos para compartilhar este painel. Peça a $0$ para enviá-lo novamente com autorização para você compartilhar com outros',
  DASHBOARD_SHARE_SHAREDASH: 'Compartilhe este painel em tempo real e em particular',
};
