module.exports = {
  COMMUM_NEXT: 'Proximo',

  WELCOME_GET_STARTED: 'Vamos começar',
  WELCOME_CONNECT_DEVICE: 'Conecte o dispositivo',
  WELCOME_CONNECT_DEVICE_DESC: 'Conecte qualquer dispositivo que já tenha construído um driver para. Siga nossas diretrizes para conectar seu próprio dispositivo facilmente.',
  WELCOME_BUILD_APP: 'Construa seu aplicação',
  WELCOME_BUILD_APP_DESC: 'Combine dados de diferentes tipos de dispositivos dentro da sua própria aplicação. Acesse sua conta em www.tago.io e comece a construir agora.',
  WELCOME_SHARE_ANY: 'Compartilhe com qualquer um',
  WELCOME_SHARE_ANY_DESC: 'Compartilhe seus dashboards com qualquer pessoa usando opções privadas ou públicas. Outros receberão atualizações em tempo real.',

  LOGIN_EMAIL: 'E-mail',
  LOGIN_PASSWORD: 'Senha',
  LOGIN_BTN_SIGNIN: 'Entrar',
  LOGIN_BTN_SIGNUP: 'Criar uma conta',

  SECTION_DASHBOARD: 'Painéis',
  SECTION_DASHBOARD_INFO: 'Informações do Painel',
  SECTION_EXPLORE: 'Explore',
  SECTION_NOTIFICATION: 'Notificações',
  SECTION_SETTINGS: 'Configurações',
  SECTION_SHAREPRIVATE: 'Compartilhamento',
  SECTION_APPINFO: 'Aplicação',
  SECTION_DEVICES: 'Dispositivos',


  SETTINGS_TOUCHID: 'Ativar TouchID',
  SETTINGS_NOTIFICATIONS: 'Notificações',
  SETTINGS_FULLSCREEN: 'Tela cheia na horizontal',
  SETTINGS_KEEPAWAKE: 'Manter acordado',
  SETTINGS_LOGOUT: 'Sair',
  SETTINGS_VERSION: 'Versão:',

  NOTIFICATIONS_ACCEPTED: 'Aceito',
  NOTIFICATIONS_DECLINED: 'Recusou',
  NOTIFICATIONS_ACCEPT: 'Aceitar',
  NOTIFICATIONS_DECLINE: 'Recusar',
  NOTIFICATIONS_IGNORE: 'Ignorar',
  NOTIFICATIONS_GOTODASH: 'Ir para o Painél',
  NOTIFICATIONS_APPSETTINGS: 'Configurações da aplicação',
  NOTIFICATIONS_NEWUSERREGISTERED: 'Novo usuário registrado',
  NOTIFICATIONS_NEWUSERREGISTERED_DESC: '$0$ acabou de criar uma conta na Tago. O item que você compartilhou está disponível para ele aceitar',
  NOTIFICATIONS_SHAREPROFILE: 'Compartilhamento de perfil',
  NOTIFICATIONS_SHAREPROFILE_DESC: '$0$ deseja compartilhar o perfil com você',
  NOTIFICATIONS_SHAREREQUEST_DASH: 'Solicitação de compartilhamento - Painél',
  NOTIFICATIONS_SHAREREQUEST_DASH_DESC: '$0$ deseja compartilhar o painél $1$ com você',
  NOTIFICATIONS_SHAREREQUEST_BUCKET: 'Solicitação de compartilhamento - Bucket',
  NOTIFICATIONS_SHAREREQUEST_BUCKET_DESC: '${notification.ref_from.name} eseja compartilhar o bucket ${notification.ref_id.name} com você',

  EXPLORER_SHOWALL: 'Mostre tudo',
  EXPLORER_TRANSPORTATION: 'Transporte',
  EXPLORER_HOME: 'Casa',
  EXPLORER_AGRICULTURE: 'Agricultura',
  EXPLORER_ENERGY: 'Energia',
  EXPLORER_INDUSTRIAL: 'Industrial',
  EXPLORER_ALREADYADDED: 'Já adicionado',
  EXPLORER_BY: 'Por',
  EXPLORER_FILTERCATEGORY: 'Filtrar por Categoria',
  EXPLORER_SEARCHFORMODEL: 'Procure por modelo, marca ou aplicativo ...',
  EXPLORER_CANCEL: 'Cancelar',
  EPLORER_COMPATIBLE: 'Dispositivos compatíveis:',
  EXPLORER_HOWTOALERT: 'Como instalar',
  EXPLORER_HOWTOINSTALL: 'Como instalar esta aplicação?',
  EXPLORER_ADDAPPLI: 'Adicionar aplicação',
  EXPLORER_CONFIGURE: 'Configurar',
  EXPLORER_DOWANTCONT: 'Você quer continuar?',
  EXPLORER_THISACTIONWILL: 'Esta ação irá adicioná-lo à sua lista de painéis.',
  EXPLORER_NO: 'Não',
  EXPLORER_YES: 'Sim',
  EXPLORER_ENTERPIN: 'Isso requer um código PIN. Digite o código fornecido pelo criador.',
  EXPLORER_ENTERCODE: 'Digite o código requerido...',
  EXPLORER_ADD: 'Adicionar',
  EXPLORER_OOPS: 'Opa, algo deu errado',
  EXPLORER_BACK: 'Voltar',
  EXPLORER_DONE: 'Pronto!',
  EXPLORER_YOUWILLRECEIVE: 'Você receberá uma notificação quando ela estiver disponível na sua conta. Não se preocupe, isso levará apenas alguns segundos.',
  EXPLORER_BACKTOEXPLORE: 'Voltar para o Explore',
  EXPLORER_LOADING: 'Estamos trabalhando nisso...',

  DASHBOARD_SHARE: 'Convidar',
  DASHBOARD_SHARE_ONEHOUR: 'Compartilhar por uma hora',
  DASHBOARD_SHARE_ENDDAY: 'Compartilhar até o final do dia',
  DASHBOARD_SHARE_INDEF: 'Compartilhar Indefinidamente',
  DASHBOARD_SHARE_CANCEL: 'Cancelar',
  DASHBOARD_SHARE_EMAIL: 'Digite o e-mail do usuário',
  DASHBOARD_SHARE_INVITE: 'Convidar',
  DASHBOARD_SHARE_ALLOWOTHERS: 'Permitir que o usuário compartilhe com outras pessoas?',
  DASHBOARD_SHARE_NO: 'Não',
  DASHBOARD_SHARE_YES: 'Sim',
  DASHBOARD_SHARE_INVEMAIL: 'Estrutura de email inválida',
  DASHBOARD_SHARE_TRYA: 'Tente novamente',
  DASHBOARD_SHARE_YOUSHARE: 'Você compartilhou um painel com uma data de expiração maior que a data de expiração do compartilhamento que foi feito para você. O compartilhamento para:',
  DASHBOARD_SHARE_WILLEXP: 'irá expirar em: $0$',
  DASHBOARD_SHARE_OK: 'Certo',
  DASHBOARD_SHARE_SHARESUCESS: 'Compartilhamento feito',
  DASHBOARD_SHARE_FAIL: 'Falha no compartilhamento',
  DASHBOARD_SHARE_USERINVITED: 'O usuário foi convidado para acessar este painel',
  DASHBOARD_SHARE_NOTALLOWED: 'Você não tem direitos para compartilhar este painel. Peça a $0$ para enviá-lo novamente com autorização para você compartilhar com outros',
  DASHBOARD_SHARE_SHAREDASH: 'Compartilhe este painel em tempo real e em particular',

  DASHBOARDINFO_REMOVEDASH: 'Remover este painel?',
  DASHBOARDINFO_ACTIONREMOVEDESC: 'Esta ação também irá removê-lo da lista de todos que você compartilhou.',
  DASHBOARDINFO_NO: 'Não',
  DASHBOARDINFO_YES: 'Sim',
  DASHBOARDINFO_DASHREMOVED: 'Painel removido com sucesso',
  DASHBOARDINFO_YOUACCESSREMOVED: 'Seu acesso a este painel foi removido.',
  DASHBOARDINFO_OK: 'Certo',
  DASHBOARDINFO_TRYA: 'Tente novamente',
  DASHBOARDINFO_INDEF: 'Indefinidamente',
  DASHBOARDINFO_SHAREBY: 'Compartilhado por:',
  DASHBOARDINFO_YOUOWNER: 'Você é o dono',
  DASHBOARDINFO_SHAREEXPAT: 'O compartilhamento expira em:',
  DASHBOARDINFO_REMOVETDASH: 'Remover este painel',
  DASHBOARDINFO_SHARETHISDASH: 'Compartilhar este painel',
  DASHBOARDINFO_SHARETHISDASHDESC: 'O compartilhamento permite que outras pessoas acessem este painel em tempo real durante o período definido por você. Você pode permitir que os usuários compartilhem este painel com outras pessoas. ',

  DASHBOARDSHAREPRIV_STOPSHARE: 'Parar de compartilhar com este usuário?',
  DASHBOARDSHAREPRIV_STOPSHAREDESC: 'Isso também removerá o compartilhamento com todos os usuários convidados por este usuário',
  DASHBOARDSHAREPRIV_NO: 'Não',
  DASHBOARDSHAREPRIV_YES: 'Sim',
  DASHBOARDSHAREPRIV_SHARESUCCESS: 'Compartilhamento removido com sucesso',
  DASHBOARDSHAREPRIV_NOLONGERACCESS: 'O usuário não pode mais acessar este painel',
  DASHBOARDSHAREPRIV_OK: 'Certo',
  DASHBOARDSHAREPRIV_ERRORSHARE: 'A remoção do compartilhamento falhou',
  DASHBOARDSHAREPRIV_TRYA: 'Tente novamente',
  DASHBOARDSHAREPRIV_INDEF: 'Indefinidamente',
  DASHBOARDSHAREPRIV_USERNOACC: 'O usuário ainda não tem uma conta',
  DASHBOARDSHAREPRIV_ACCEPTED: 'Aceito',
  DASHBOARDSHAREPRIV_PENDING: 'Pendente',
  DASHBOARDSHAREPRIV_INVITSTA: 'Status do convite:',
  DASHBOARDSHAREPRIV_SHAREBY: 'Compartilhado por:',
  DASHBOARDSHAREPRIV_USERCANOTHERS: 'O usuário pode compartilhar com outras pessoas:',
  DASHBOARDSHAREPRIV_SHAREEXPIRE: 'O compartilhamento com este usuário expira em:',
  DASHBOARDSHAREPRIV_SHARENOW: 'Compartilhe este painel agora',
  DASHBOARDSHAREPRIV_NORIGHTS: 'Você não tem permissão para compartilhar este painel',
  DASHBOARDSHAREPRIV_LISTDOESNTHTHERS: 'Esta lista não inclui painéis que foram removidos por outros usuários ou que expiraram.',

  APPLICATION_REMOVEAPPQ: 'Remover aplicativo?',
  APPLICATION_REMOVEAPPDESC: 'Esta ação removerá completamente o aplicativo',
  APPLICATION_CANCEL: 'Cancelar',
  APPLICATION_REMOVE: 'Remover',
  APPLICATION_CREATED: 'Criado por:',
  APPLICATION_VERSION: 'Versão:',
  APPLICATION_REMOVEAPP: 'Remover aplicativo',
  APPLICATION_DEVICES: 'Dispositivos',

  APPLICATION_DEVICES_REMOVEQ: 'Remover dispositivo?',
  APPLICATION_DEVICES_REMOVEDESC: 'Esta ação removerá completamente o dispositivo',
  APPLICATION_DEVICES_CANCEL: 'Cancelar',
  APPLICATION_DEVICES_REMOVE: 'Remover',
  APPLICATION_DEVICES_DELETE: 'Excluir',
  APPLICATION_DEVICES_NONAME: 'Sem nome',
  APPLICATION_DEVICES_ADDD: 'Adicionar dispositivo',
  APPLICATION_DEVICES_APPNOTREQ: 'Este aplicativo não requer dispositivos.',

  APPLICATION_NDEVICES_SELECTD: 'Selecionar dispositivo',
  APPLICATION_NDEVICES_HOWINT: 'Como instalar',
  APPLICATION_NDEVICES_HOWQ: 'Como instalar este aplicativo?',
  APPLICATION_NDEVICES_SELECTDAPPL: 'Selecione o tipo do dispositivo para esta aplicação',
  APPLICATION_NDEVICES_APPNAME: 'Nome do Aplicativo:',
  APPLICATION_NDEVICES_DEVTYPE: 'Tipo do dispositivo:',
  APPLICATION_NDEVICES_NAME: 'Nome:',
  APPLICATION_NDEVICES_ENAME: 'Digite o nome ...',
  APPLICATION_NDEVICES_SERIAL: 'Número de série:',
  APPLICATION_NDEVICES_ESERIAL: 'Digite o número de série ...',
  APPLICATION_NDEVICES_VERIFCODE: 'Código de verificação:',
  APPLICATION_NDEVICES_EVERIFCODE: 'Digite o código de verificação ...',
  APPLICATION_NDEVICES_ADDD: 'Adicionar dispositivo',
};
