module.exports = {
  HOME: 'Início',
  USE_CASES: 'Casos de uso',
  PRICING: 'Preços',
  PRODUCT: 'Produto',
  FEATURES: 'Visão Geral',
  CONNECTIVITY: 'Conectividade',
  INTEGRATION: 'Análise de dados',
  CUSTOMIZATION: 'Customização',
  RESOURCES: 'Recursos',
  DEVELOPERS: 'Desenvolvedores',
  PARTNERS: 'Parceiros',
  VIDEOS: 'Vídeos',
  FAQ: 'FAQ',
  BLOG: 'Blog',
  CONTACT_US: 'Contato',
  TALK_TO_SALES: 'Equipe de vendas',
  CUSTOMER_SUPPORT: 'Suporte ao cliente',
  SIGN_IN: 'Entrar',
  GET_STARTED: 'Criar Conta',
  TAGORUN: 'TagoRUN',
};
