module.exports = {
  OUR_PRODUCT: 'Nosso Produto',
  OUR_PRODUCT_SUBTITLE1: 'Crie mais valor com os dados gerados pelo seu produto conectado com a Tago',
  OUR_PRODUCT_SUBTITLE2: 'Aprenda sobre as funcionalidades da nossa plataforma',
  PRODUCT_OVERVIEW: 'Geral',
  PRODUCT_OVERVIEW_TITLE1: 'Crie ou melhore sua fontes de dados',
  PRODUCT_OVERVIEW_DESCRIPTION1: 'Antecipe oportunidades através da combinação dos dados do seu produto e outras fontes. Otimize o desempenho e a usabilidade da sua solução e exceda as expectativas dos seus clientes.',
  PRODUCT_OVERVIEW_LINK1: 'Mais sobre Conectividade',
  PRODUCT_OVERVIEW_TITLE2: 'Aja em tempo-real integrando diretamente com o seu processo',
  PRODUCT_OVERVIEW_DESCRIPTION2: 'Responda as necessidades dos seus clientes based nas suas regras de negócios. Use nossos conectadores para integrar com serviços como CRM, ERP, Google, Microsoft, AWS e outros.',
  PRODUCT_OVERVIEW_LINK2: 'Mais sobre \'Analysis\'',
  PRODUCT_OVERVIEW_TITLE3: 'Enriqueça o relacionamento da sua marca com seus clientes',
  PRODUCT_OVERVIEW_DESCRIPTION3: 'Saiba mais como seus clientes estão interagindo com seus produtos. Use nossa versão de portal \'Whitelabel\' para alcançar o visual da sua marca.',
  PRODUCT_OVERVIEW_LINK3: 'Mais sobre Customizaçaão',
  PRODUCT_DEVICE_MANAGEMENT: 'Gerenciamento de Dispositivos',
  PRODUCT_DEVICE_MANAGEMENT_H1: 'Gerenciamento de Dispositivos',
  PRODUCT_DEVICE_MANAGEMENT_TITLE1: 'Gerencie todos os seus dispositivos de forma segura e simples',
  PRODUCT_DEVICE_MANAGEMENT_DESCRIPTION1: 'Mantenha o controle total dos dispositivos conectados a sua conta. Define a regras para restrições de acesso e uso.',
  PRODUCT_DEVICE_MANAGEMENT_TITLE2: 'Gerenciamento de \'Tokens\'',
  PRODUCT_DEVICE_MANAGEMENT_DESCRIPTION2: 'Crie diferente niveis de acesso para cada dispositivo. Cada dispositivo é autenticado de forma única e segura. Toda comunicação entre seus dispositivos e a Tago é feita por HTTPS.',
  PRODUCT_DEVICE_MANAGEMENT_TITLE3: 'Gerenciamento de Inventário',
  PRODUCT_DEVICE_MANAGEMENT_DESCRIPTION3: 'Use etiquetas para agrupar seus dispositivos a fim de achá-los mais facilmente; isto é uma ótima solução se voce tiver 10 ou 100,000 dispositivos.',
  PRODUCT_DEVICE_MANAGEMENT_TITLE4: 'Múltiplos meios de conectividade',
  PRODUCT_DEVICE_MANAGEMENT_DESCRIPTION4: 'Conecte qualquer tipo de dispositivo usando RESTful, MQTT ou o seu próprio protocolo. Não importa se voce utiliza comunicação por WiFi, Bluetooth, Sigfox, LoRa, zWave, RPMA, CDMA, 3G, Satélites ou qualquer outro meio, a Tago pode suportar todas elas.',
  PRODUCT_DATA_MANAGEMENT: 'Gereciamento de Dados',
  PRODUCT_DATA_MANAGEMENT_H1: 'Gereciamento de Dados',
  PRODUCT_DATA_MANAGEMENT_TITLE1: 'Nosso sistema inovador de armazenamento de dados torna a manipulação de dados muito mais fácil ',
  PRODUCT_DATA_MANAGEMENT_DESCRIPTION1: 'Não é necessário ser expert em banco de dados. A Tago organiza todos os dados em \'buckets\' para um fácil entendimento. Compartilhe seus \'buckets\' com seus clientes e parceiros.',
  PRODUCT_DATA_MANAGEMENT_TITLE2: 'Compartilhamento de Dados',
  PRODUCT_DATA_MANAGEMENT_DESCRIPTION2: 'Compartilhe dados individuais ou um conjunto deles com base na maneira como seus dispositivos são vinculados aos buckets. É possível alterar facilmente a configuração dos links e o tipo de acesso a qualquer momento com poucos cliques.',
  PRODUCT_DATA_MANAGEMENT_TITLE3: 'Retenção e Backup de Dados',
  PRODUCT_DATA_MANAGEMENT_DESCRIPTION3: 'Controle como os dados são armazenados em backup e evite custos desnecessários definindo o período de retenção para os dados não usados com frequência. Baixe seus dados para o seu driver local ou outros servidores.',
  PRODUCT_DATA_MANAGEMENT_TITLE4: 'Manipulação de Dados',
  PRODUCT_DATA_MANAGEMENT_DESCRIPTION4: 'Acesse uma lista das variáveis criadas por seus dispositivos e tenha noção clara sobre a quantidade de registros. Além disso, você pode esvaziar todo o intervalo ou apenas excluir variáveis específicas com apenas alguns cliques.',
  PRODUCT_ANALITICS: 'Analítica',
  PRODUCT_ANALITICS_H1: 'Analítica',
  PRODUCT_ANALITICS_TITLE1: 'Crie scripts poderosos para executar análises em tempo real',
  PRODUCT_ANALITICS_DESCRIPTION1: 'Implemente suas próprias regras de negócios para reagir instantaneamente a qualquer alteração em seu sistema. Você pode executar operações simples, como conversação de temperatura, reconhecimento de imagem e análise avançada de grandes massas de dados.',
  PRODUCT_ANALITICS_TITLE2: 'Decisoões em tempo-real',
  PRODUCT_ANALITICS_DESCRIPTION2: 'O Tago oferece opções poderosas para você criar e executar seus próprios scripts em tempo real. Você pode executar scripts criados em qualquer linguagem de computador. Os scripts podem ser acionados por intervalo fixo, quando um dispositivo envia dados ou quando uma determinada condição é correspondida.',
  PRODUCT_ANALITICS_TITLE3: 'Console para Debug',
  PRODUCT_ANALITICS_DESCRIPTION3: 'Acompanhe o status de seus scripts durante a execução usando nosso recurso Console. Conecte suas ferramentas de desenvolvimento usadas em seu computador diretamente ao Tago para sincronizar o script em seu computador com os eventos em sua conta.',
  PRODUCT_ACTIONS: 'Ações',
  PRODUCT_ACTIONS_H1: 'Ações',
  PRODUCT_ACTIONS_TITLE1: 'Prepare conjuntos de dados e relatórios para serem enviados para usuários ou dispositivos por email, SMS, MQTT ou HTTP',
  PRODUCT_ACTIONS_DESCRIPTION1: 'Não fique limitado a apenas obter mais informações - entre em ação! Assuma o controle de seu sistema enviando dados de volta para dispositivos ou para outros sistemas de back-end. O Tago é facilmente integrado a softwares de terceiros usando APIs combinando os recursos Actions e Analysis. Configure sua ação para enviar e-mail, SMS, dados para o dispositivo, encerre os dados em outro ponto de extremidade HTTP quando determinada condição for atendida.',
  PRODUCT_ACTIONS_DESCRIPTION2: 'Regras simples podem ser configuradas aqui em poucos cliques. Quando uma condição é correspondida, a ação selecionada é acionada. Condições mais complexas podem ser construídas com scripts ou usando nosso conector com software externo como o Flow da Microsoft.',
  PRODUCT_DASHBOARDS: 'Painéis',
  PRODUCT_DASHBOARDS_H1: 'Painéis',
  PRODUCT_DASHBOARDS_TITLE1: 'Crie e compartilhe seus painéis com qualquer pessoa ou organização',
  PRODUCT_DASHBOARDS_DESCRIPTION1: 'Crie e compartilhe seus painéis com usuários internos e externos de forma segura com apenas alguns cliques. É fácil compartilhar soluções com qualquer pessoa, mesmo que elas não tenham uma conta do Tago. Quando você edita um painel compartilhado, todos recebem a atualização automaticamente.',
  PRODUCT_DASHBOARDS_DESCRIPTION2: 'Tago fornece várias opções de widgets para construir seu painel em minutos. Todos eles fornecem visualização em tempo real. Alguns widgets podem ser usados para coletar entradas dos usuários para tornar a interface mais intuitiva e interativa.',
  PRODUCT_DASHBOARDS_DESCRIPTION3: 'Além de displays, tabelas, mapas e gráficos, a Tago oferece widgets para exibir animações, vídeos e sobrepor imagens com mapas de calor. Vá além e crie seu próprio widget personalizado para ser usado apenas em seu aplicativo.',
  PRODUCT_CONNECTIVITY: 'Conectividade',
  PRODUCT_CONNECTIVITY_SUBTITLE: 'Tome ações em tempo-real combinando seus dados com serviços externos',
  PRODUCT_CONNECTIVITY_DESCRIPTION1: 'A Tago já está conectada a vários gateways, sensores, fontes de dados e provedores de rede para ficar mais fácil e rápida para você implantar totalmente seu aplicativo. Quer o seu produto seja ligado através de WiFi, Bluetooth, Sigfox, LoRa, RPMA, CDMA, 3G, satélite ou qualquer outro meio, o Tago pode ser facilmente configurado para suportar a sua aplicação.',
  PRODUCT_CONNECTIVITY_LINK1: 'Mais sobre nossos Parceiros',
  PRODUCT_CONNECTIVITY_DESCRIPTION2: 'Cada dispositivo é autenticado com um token exclusivo gerado pelo backend Tago. Toda a comunicação entre os dispositivos e o Tago é realizada em camada segura - HTTPS. Camada adicional de segurança pode ser implementada com a inclusão de certificados dentro dos dispositivos para garantir autenticação dupla.',
  PRODUCT_CONNECTIVITY_DESCRIPTION3: 'Não há necessidade de aprender sobre a estrutura do banco de dados. Tago organiza todos os dados provenientes de dispositivos em \'buckets\'. Os dados estão disponíveis nesses buckets para serem visualizados e processados em tempo real. Gere mais oportunidades de negócios usando um recurso exclusivo da Tago que permite que dados sejam facilmente compartilhados com usuários internos e externos.',
  PRODUCT_ANALYSIS: 'Análise',
  PRODUCT_ANALYSIS_SUBTITLE: 'Tome ações em tempo real para responder às demandas de seus clientes',
  PRODUCT_ANALYSIS_DESCRIPTION1: 'Implemente suas próprias regras de negócios para reagir instantaneamente a qualquer alteração em seu sistema. Você pode executar operações simples, como conversação de temperatura, para reconhecimento de imagem, para análise avançada de dados.',
  PRODUCT_ANALYSIS_DESCRIPTION2: 'Defina regras de configuração para gerar relatórios para suas equipes internas ou clientes. Mantenha-os informados sobre problemas de funcionamento do produto, operações suspeitas e cronogramas de manutenção. Ofereça serviços que melhor atendam às necessidades de seus clientes com base nas informaçoões de como eles usam seus produtos.',
  PRODUCT_ANALYSIS_DESCRIPTION3: 'Antecipe problemas e oportunidades, combinando dados do seu produto e de outras fontes. Aproveite os diversoso dispositivos e serviços disponíveis ao Tago. Otimize o desempenho e a usabilidade do produto para superar as expectativas do cliente.',
  PRODUCT_CUSTOMIZATION: 'Customização',
  PRODUCT_CUSTOMIZATION_SUBTITLE: 'Crie uma experiência única para o seu cliente fornecendo soluções diferenciadas',
  PRODUCT_CUSTOMIZATION_DESCRIPTION1: 'Com mais informações à mão, sua empresa extrairá mais valor para sua própria marca. Implemente os painéis com seu próprio logotipo, cores, serviços de e-mail e URL usando nossa edição Whitelabel.',
  PRODUCT_CUSTOMIZATION_DESCRIPTION2: 'Sua equipe saberá quem está conectado e controlará o acesso aos aplicativos de cada um deles. Combinando o conhecimento adquirido da utilização do produto e das preferências do usuário, sua solução pode ser configurada para executar a operação de pagamento automático.',
  PRODUCT_CUSTOMIZATION_DESCRIPTION3: 'Entendemos que, em alguns casos, os clientes precisarão de uma interface de usuário totalmente personalizada ou de um aplicativo para dispositivos móveis. Nosso poderoso conjunto de APIs permite a integração completa do back-end Tago com o aplicativo móvel nativo ou qualquer outro serviço externo.',
  PRODUCT_CUSTOMIZATION_LNIK1: 'Vá para API',
  PRODUCT_DESCRIPTION: 'Obtenha mais dos dados gerados pelo seu produto conectado usando os melhores serviços desenvolvidos pela TagoIO. Saiba o que podemos oferecer para você criar painéis, análises, notificações, integrações e gerenciar usuários e dispositivos.',
  CONNECTIVITY_DESCRIPTION: 'O TagoIO está integrado a vários gateways, sensores, fontes de dados e provedores de rede para facilitar e agilizar a implantação do aplicativo. Se o seu produto será conectado via Wi-Fi, Bluetooth, Sigfox, LoRa, LoRaWAN, 3G, satélite ou qualquer outro meio, o TagoIO pode ser facilmente configurado para suportar sua aplicação.',
  ANALYSIS_DESCRIPTION: 'Crie scripts que serão executados em tempo real para antecipar problemas técnicos e oportunidades de negócios, combinando dados do seu produto e de outras fontes. Implemente suas próprias regras de negócios para reagir instantaneamente a qualquer alteração em seu sistema.',
  CUSTOMIZATION_DESCRIPTION: 'Implante seu próprio ambiente com painéis, exibindo seu próprio logotipo, cores, serviços de e-mail e URL usando nossa edição White-label.',
};
