module.exports = {
  PRICING: 'Planos',
  PRICING_DESCRIPTION1: 'Nossos preços são compostos pela combinação do plano do conjunto de ferramentas selecionado e dos serviços utilizados durante o período de um mês. Todos os valores são expressos em Dólar Americano (USD).',
  PRICING_DESCRIPTION2: 'A Tago oferece todas as ferramentas que sua empresa precisa para construir a melhor solução conectada da indústria. Cada plano é formado por uma série de características ideal para cada estágio e tamanho do seu projeto.',
  FREE: 'Free',
  FREE_VALUE: '0',
  STARTER: 'Starter',
  STARTER_VALUE: '49',
  SCALE: 'Scale',
  SCALE_VALUE: '199',
  ENTERPRISE: 'Enterprise',
  ENTERPRISE_VALUE: '399',
  GET_STARTED_PLAN: 'Comece Agora',
  OUR_PLANS: 'Nossos Planos',
  OUR_PLANS_DESCRIPTION: 'Selecione o plano baseado na ferramentas que voce precisar para sua solução. Altere seu plano a medida que sua aplicação vai crescendo. Todos os valores são expressos em Dólar Americano (USD).',
  PLAN_FEATURES: 'Características',
  DEVICE_MANAGEMENT: 'Gerenciamento de Dispositivos',
  DEVICE_MANAGEMENT_SPAN_FREE: 'Conecte até 5 dispositivos',
  DASHBOARD_CREATION: 'Criação de Painéis',
  DASHBOARD_CREATION_SPAN_FREE: 'Crie até 5 painéis',
  NATIVE_SHARE_CAPABILITY: 'Compartilhação nativa de dados',
  RUN_ANALYSIS: 'Execução de código em tempo-real',
  RUN_ANALYSIS_SPAN_FREE: 'rode até 250 scripts/hora',
  API_REQUESTS: 'Requisições controlada de API',
  API_REQUESTS_SPAN_FREE: 'até 250 / hora',
  API_REQUESTS_SPAN_STARTER: 'até 10,000 / hora',
  API_REQUESTS_SPAN_SCALE_ENTERPRISE: '+ 10,000 / hora',
  CONFIGURABLE_MAX_REQUEST: 'Controle de limite de acesso',
  DATA_RETENTION_CONTROL: 'Controle de Retenção de Dados',
  DATA_RETENTION_CONTROL_SPAN_FREE: 'limitado a 30 dias',
  AUTOMATIC_DATA_BACKUP: 'Backup Automático',
  TAGS_MANAGEMENT: 'Gerenciamento de Etiquetas',
  USER_PROFILE_MANAGEMENT: 'Gerenciamento de Usuários',
  USER_PROFILE_MANAGEMENT_STARTER: 'Adicione mais 1 usuário',
  USER_PROFILE_MANAGEMENT_SCALE: 'Adicione até 5 usuários',
  USER_PROFILE_MANAGEMENT_ENTERPRISE: 'Número ilimitado de usuários',
  COMPLETE_AUDIT_LOG: 'Log de Auditoria',
  COMPLETE_AUDIT_LOG_STARTER: 'limitado somente aos logs da conta',
  EMBED_WIDGET_CREATION: 'Criação de Widget embarcados',
  SLA: 'SLA',
  PREMIUM_WIDGETS: 'Widgets Prêmio',
  PRIVATE_SLACK_CHANNEL: 'Canal Privado no Slack',
  CUSTOMIZED_MIDDLEWARE_FOR_ANY_DEVICE: 'Servidor de Middleware Customizado',
  REALESE_SOLUTION_EXPLORE: 'Publicaçāo no Explore',
  WHITELABEL_VERSION: 'Versão WhiteLabel',
  SERVICE_USAGE: 'Uso dos Serviços',
  SERVICE_USAGE_DESCRIPTION: 'Pague somente pelos serviços que voce utilizar. Não cobramos por números de dispositivos, painéis, ou usuários. Os custos do uso são cobrados mensalmente baseado na transações realizadas e na quantidade de dados armazenadas.',
  SERVICE: 'Serviço',
  COST: 'Custo (USD)',
  UNIT: 'Unidade',
  ANALYSIS_RUNNING_SRIPTS: 'Analysis (execução de código)',
  ANALYSIS_RUNNING_SRIPTS_SPAN: 'Execute códigos para processar dados dos seus dispositivos. Cada execução deve ser concluida em até 30s.',
  ANALYSIS_RUNNING_SRIPTS_COST: '$0.100',
  ANALYSIS_RUNNING_SRIPTS_UNIT: '1,000 execuções',
  USAGE_API_REQUESTS: 'Requisições',
  USAGE_API_REQUESTS_SPAN: 'Qualquer acesso feito pelas APIs usando POST, GET ou DELETE',
  USAGE_API_REQUESTS_COST: '$0.025',
  USAGE_API_REQUESTS_UNIT: '1,000 requisições',
  STORAGE_ONLINE_DATA: 'Armazenamento - Online',
  STORAGE_ONLINE_DATA_SPAN: 'Dados online estão sempre disponiveis para visualização e processamento.',
  STORAGE_ONLINE_DATA_COST: '$0.015',
  STORAGE_ONLINE_DATA_UNIT: '1,000 requisições',
  STORAGE_ONLINE_BACKUP: 'Armazenamento - Backup',
  STORAGE_ONLINE_BACKUP_SPAN: 'Dados de backup são mantidos offline.',
  STORAGE_ONLINE_BACKUP_COST: '$0.005',
  STORAGE_ONLINE_BACKUP_UNIT: '1,000 registros',
  USAGE_SMS: 'SMS',
  USAGE_SMS_SPAN: 'Preços para envio de SMS nos EUA e Canadá (entre em contato para outros países).',
  USAGE_SMS_COST: '$0.025',
  USAGE_SMS_UNIT: '1 unidade',
  USAGE_EMAIL: 'Email',
  USAGE_EMAIL_COST: '$0.025',
  USAGE_EMAIL_UNIT: '1,000 unidades',
  CONTACT_SALES_TEAM_TALK: 'Contate nosso time de Vendas sobre descontos para alto volume de uso.',
  PRICING_TALK_TO_SALES: 'Fale com Vendas',
  PRICING_EXAMPLES: 'Estimativa de Preços',
  PRICING_EXAMPLE_1: 'Exemplo 1',
  PRICING_EXAMPLE_1_DESCRIPTION: 'Se você seleciona o plano Starter, adiciona 1,000 dispositivos que enviam (POST) um pacote de dados de 6 variáveis por hora, seus custos podem ser estimados como descrito a seguir:',
  PRICING_EXAMPLE_1_MONTHLY_PLAN: 'Plano selecionado:',
  PRICING_EXAMPLE_1_MONTHLY_PLAN_VALUE: 'Starter $49',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE: 'Uso mensal dos serviços:',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE1: 'Preço das requisições de API = $0.025 per 1,000/requisições.',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE2: 'Número de requisições mensal = 1,000 * 24 * 30 = 720,000',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE3: 'Custo mensal das requisições de API = 720,000 * 0.025/1000 = $18.00',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE4: 'Preço do armazenamento de dados = $0.015 per 1,000/registros',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE5: 'Número de registros armazenados mensalmente = 6 * 1,000 * 24 * 30 = 4,320,000',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE6: 'Custo mensal do armazenamento online = 4,320,000 * $0.015 = $64.80',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE7: 'Sub-total mensal do uso dos serviços = $18.00 + $64.80 = $82.80',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES: 'Custo mensal total:',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES_VALUE1: 'Custo mensal total = Custo do Plano + custo do uso = $49 + $82.80 = USD $131.80',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES_VALUE2: 'ou seja USD $0.13 / dispositivo / mês',
  PRICING_EXAMPLE_2: 'Exemplo 2',
  PRICING_EXAMPLE_2_DESCRIPTION1: 'Você seleciona o plano Scale e adiciona 1,000 dispositivos que enviam (POST) um pacote de dados de 6 variáveis por hora. ',
  PRICING_EXAMPLE_2_DESCRIPTION2: 'Adicionalmente, você decide executar uma Analysis (código) cada vez que um pacote de dados chegar na sua conta. Seus custos podem ser estimados como descrito a seguir:',
  PRICING_EXAMPLE_2_MONTHLY_PLAN: 'Plano selecionado:',
  PRICING_EXAMPLE_2_MONTHLY_PLAN_VALUE: 'Scale $199',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE: 'Uso mensal dos serviços:',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE1: 'Preço das requisições de API = $0.025 per 1,000/requisições.',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE2: 'Número de requisições mensal = 1,000 * 24 * 30 = 720,000',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE3: 'Custo mensal das requisições de API = 720,000 * $0.025/1000 = $18.00',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE4: 'Preço do armazenamento de dados = $0.015 per 1,000/registros',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE5: 'Número de registros armazenados mensalmente = 6 * 1,000 * 24 * 30 = 432,000',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE6: 'Custo mensal do armazenamento online = 432,000 * $0.015 = $64.80',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE7: 'Preço da execução de Analysis = $0.10 per 1,000/execução',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE8: 'Número de analysis executadas mensalmente = 1,000 * 24 * 30 = 720,000',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE9: 'Custo mensal para executar as analysis = 720,000 * $0.10 = $72.00',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE10: 'Sub-total mensal do uso dos serviços = $18.00 + $64.80 + $72.00 = $154.80',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES: 'Custo mensal total:',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES_VALUE1: 'Custo mensal total = Custo do Plano + custo do uso = $199 + $154.80 = USD $353.80',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES_VALUE2: 'ou seja USD $0.35 / dispositivo / mês',
  FREQUENTLY_ASKED_QUESTIONS: 'Frequently Asked Questions',
  PRICING_QUESTION1: 'For what I will be charged for?',
  PRICING_RESPONSE1: "Different from other providers, Tago doesn't charge by the number devices, dashboards, or even users. Our model is based on the real usage of the services, or in other words the system charges by transactions, and by the tools that are made available for you depending on your plan.  So, the monthly bill will be a sum of the plan that you selected plus the real usage of the services. You can also include some add-ons, such as the support plans.",
  PRICING_QUESTION2: 'What is the billing cycle of Tago?',
  PRICING_RESPONSE2: 'Tago closes the billing period at midnight on the last day of each month. Invoices are generally available with the first four days of the month.',
  PRICING_QUESTION3: 'If I upgrade my plan, how will that be billed?',
  PRICING_RESPONSE3: 'We make a one-time prorated charge at the time of the upgrade for the equivalent reminder of the billing cycle. For example, if you upgrade from the Free plan to the Starter plan when there is 10 remaining days in the month, we will charge 1/3 of the Starter monthly pricing immediately when you confirm the upgrade. In the next month, we will charge the full price of the Starter plan. Also, any service usage and add-ons will be added to that next bill.',
  PRICING_QUESTION4: 'What are the payment methods accepted?',
  PRICING_RESPONSE4: 'Tago accepts most major credit cards for payment. In specific cases we may be able to invoice customers directly, talk to our sales team for questions.',
  PRICING_QUESTION5: 'Do you save credit card details?',
  PRICING_RESPONSE5: 'No. Your credit card details are not saved on our servers. In fact, all information goes directly from your computer to our payment service provider (Stripe).',
  PRICING_QUESTION6: 'If I downgrade my plan, when will I see the change to be effective?',
  PRICING_RESPONSE6: 'We will downgrade you to the new selected plan at your next renewal date. Your subscription will remain active at its current level through the end of the billing period that you’ve already paid for.',
  PRICING_QUESTION7: 'If I downgrade to a free plan, what will happen with the data stored in my buckets?',
  PRICING_RESPONSE7: 'First, your subscription will remain active at its current level through the end of the billing period that you’ve already paid for. Then, while in the free plan, our system will force the 30-days data retention policy - i.e. all data with timestamp older than that will be removed. So, we highly recommend that you plan this operation carefully to prevent undesired data lost.',
  PRICING_QUESTION8: 'How is the Analysis Timeout defined?',
  PRICING_RESPONSE8: 'When the Analysis runs your script, the execution time should be less than the Timeout defined for your plan. You can monitor the status using the Console feature.',

  PRICING_ADDITIONAL_COAST: 'Custos adicionais',
  PRICING_ALL_FEATURES: 'Todos recursos',
  PRICING_COLLAPSE_ALL: 'Esconder todos',
  PRICING_EXPAND_ALL: 'Mostrar todos',
  PRICING_NOT_INCLUDED: 'Não inclúido',
  PRICING_SOME_FEATURES: 'Alguns recursos',

  PRICING_MANAGE_DEVICES: 'Gerencimanento de Dispositivos',
  PRICING_CONNECT_UNLIMITED_NUMBER_DEVICES: 'Conecte ilimitados dispositivos',
  PRICING_UP_TO: 'até',
  PRICING_TAGS_FOR_MANAGEMENT: 'Tags para gerenciamento',

  PRICING_HELP_1: 'Não cobramos com base no número de dispositivos conectados. Cada dispositivo recebe um token exclusivo para acessar sua conta.',
  PRICING_HELP_2: 'Gerencie todos os seus dispositivos usando Tags para ajudar a organizá-los por grupos.',
  PRICING_HELP_3: 'Cada vez que um dispositivo envia um pacote de dados ou faz uma leitura do sistema, ele é contado como uma solicitação de API.',

  PRICING_CREATE_DASHBOARDS: 'Criação de painéis',
  PRICING_BUILD_UNLIMITED_NUMBER_DASHBOARDS: 'Número inlimitado de painéis',
  PRICING_PREMIUM_WIDGETS: 'Premium widgets',
  PRICING_EMBEDDED_WIDGETS: 'Embedded widgets',

  PRICING_HELP_4: 'Use nossas ferramentas poderosas e fáceis de usar para criar ótimas maneiras de visualizar dados.',
  PRICING_HELP_5: 'Utilize widgets avançados que facilitam a interação dos usuários com seu aplicativo.',
  PRICING_HELP_6: "Adicione widgets no seu site ou portal. A versão em scale permite remover a marca d'água 'Power by Tago'.",

  PRICING_GO_MOBILE: 'Utilização no celular',
  PRICING_MOBILE_APP_ANDROIND_IOS: 'Aplicação para celular - Androind & iOS',

  PRICING_HELP_7: 'Tago mobile está disponível gratuitamente para desenvolvedores e usuários finais para acessar suas aplicações.',

  PRICING_RUN_ANALYSIS_REAL_TIME: 'Execução de análises em tempo real',
  PRICING_RUN_SCRIPTS_ANALYZE_DATA: 'Execução de scripts para analisar dados',
  PRICING_RUN_MACHINE_LEARNING_REAL_TIME: 'Execução machine learning em tempo real',

  PRICING_HELP_8: 'Faça o upload do seu próprio script na Análise da Tago para processar dados em tempo real.',
  PRICING_HELP_9: 'Fale com nosso suporte técnico para usar o Machine Learning para fazer previsões que trarão valor adicional aos suas aplicações.',

  PRICING_SHARE_YOUR_APPLICATION_AND_DATA: 'Comatilhamento aplicação e seus dados',
  PRICING_NATIVE_SHARING_FOR_DASHBOARDS: 'Compartilhamento nativo de painéis',
  PRICING_NATIVE_SHARING_FOR_DATA_BUCKETS: 'Compartilhamento nativo de um buckets',

  PRICING_HELP_10: 'O recurso de compartilhamento com um clique permite compartilhar painéis com qualquer pessoa, pública ou privada. Qualquer pessoa sem uma conta existente do Tango será solicitada a se inscrever quando você enviar um convite.',
  PRICING_HELP_11: 'O recurso de compartilhamento com um clique permite compartilhar seus dados com qualquer pessoa com segurança.',

  PRICING_AUTOMATE_EXPAND_SOLUTIONS_WITH_INTEGRATION: 'Automatize e expanda soluções com integração',
  PRICING_CONNECT_ANY_APP: 'Conecte-se a qualquer aplicativo',
  PRICING_CONNECT_SIGFOX_LORAWAN: 'Conecte-se com Sigfox, LoRaWan...',
  PRICING_NATIVE_INTEGRATION_MICROSOFT_FLOW: 'Integração nativa com Microsoft Flow',
  PRICING_NATIVE_INTEGRATION_CRM: 'Integração nativa com CRM',
  PRICING_INTEGRATED_CUSTOMIZED_MIDDLEWARE: 'Integrado com middleware customizado',

  PRICING_HELP_12: 'Conecte sistemas externos a Tago usando nossa API RESTful fácil de usar',
  PRICING_HELP_13: 'Conecte seu dispositivo usando nosso conector para Sigfox, provedores LoRa e outros provedores de rede',
  PRICING_HELP_14: 'Integre sua solução com Googlesheets, Excel, Zendesk, Twitter e centenas de serviços por meio do Microsoft Flow',
  PRICING_HELP_15: 'Identifique mais oportunidades de vendas integrando seu CRM com a Tago',
  PRICING_HELP_16: 'O Tago pode ser conectada a qualquer protocolo. Nosso middleware pode converter de UDP, TCP/IP ou conectar-se a vários formatos de banco de dados.',

  PRICING_SCALE_CONFIDENCE: 'Scale with confidence',
  PRICING_MONITORING_EVERY_TRANSACTION_AUDIT_LOG: 'Monitore todas as transações com Log de Auditoria',
  PRICING_SRIPTS_THAT_GRANT_DIFFERENT_LEVELS_ACCESS: 'Scripts concedem diferentes níveis de acesso',
  PRICING_ADD_USERS_MANAGE_ACCOUNT: 'Adicione usuários para gerenciar sua conta',

  PRICING_HELP_17: 'Nosso registro de auditoria irá acompanhar o que e quem acessou sua conta, que tipo de operações foram feitas e quando. A versão inicial oferece alguns recursos.',
  PRICING_HELP_18: 'Novos usuários terão acesso ao seu aplicativo com base no nível que você conceder a eles.',
  PRICING_HELP_19: 'Não cobramos pelos usuários finais, você pode compartilhar seu aplicativo sem nenhum custo para você ou seu cliente. Você pode adicionar mais usuários para gerenciar sua conta. Um usuário adicional para o plano Starter e 10 para Scale',

  PRICING_BACK_UP_YOUR_DATA: 'Faça backup de seus dados',
  PRICING_DOWNLOAD_YOUR_DATA: 'Baixe seus dados',
  PRICING_DATA_RETENTION_POLICY: 'Política de retenção de dados',
  PRICING_LIMITED_30_DAYS: 'limitado a 30 dias',
  PRICING_OFF_LINE_DATA_BACKUP_REDUCES_STORAGE_COST: 'Backup de dados off-line reduz o custo de armazenamento',
  PRICING_MAXIMUM_OUTPUT_DATA_TRANSACTIONS_PER_HOUR: 'Maxímo saída de dados por hora',
  PRICING_MAXIMUM_INPUT_DATA_TRANSACTIONS_PER_HOUR: 'Maxímo enviado de dados por hora',

  PRICING_HELP_20: 'Faça o download de seus dados no formato .csv, JSON ou XML.',
  PRICING_HELP_21: 'Você pode determinar por quanto tempo os dados on-line devem ser mantidos.',
  PRICING_HELP_22: 'Você pode configurar cada depósito de dados para backup conforme necessário. Custo de armazenamento off-line é uma fração do custo on-line.',

  BRAND_ENGAGEMENT: 'Engajamento da marca',
  ADD_YOUR_LOGO_YOUR_APPLICATION: 'Adicione seu logotipo na aplicação',
  WHITE_LABEL_VERSION: 'Versão white label',

  PRICING_HELP_23: 'Adicione o logotipo usando nossos widgets de imagem e vídeo em segundos',
  PRICING_HELP_24: 'Adicione seu próprio logotipo, cores e URL para engajar os clientes com sua marca. Um add-ons é necessário.',
};
