module.exports = {
  PRICING: 'Planos',
  PRICING_DESCRIPTION1: 'Nossos preços flexíveis são compostos pelo Plano de ferramentas e Serviços selecionados durante o mês. Todos os valores são expressos em Dólar Americano(USD)',
  PRICING_DESCRIPTION2: 'Cada plano é formado por uma série de características ideal para o estágio e tamanho do seu projeto.',
  FREE: 'Free',
  FREE_VALUE: '0',
  STARTER: 'Starter',
  STARTER_VALUE: '49',
  SCALE: 'Scale',
  SCALE_VALUE: '199',
  ENTERPRISE: 'Enterprise',
  ENTERPRISE_VALUE: '399',
  GET_STARTED_PLAN: 'Comece Agora',
  OUR_PLANS: 'Nossos Planos',
  OUR_PLANS_DESCRIPTION: 'Selecione o plano baseado na ferramentas que voce precisar para sua solução. Altere seu plano a medida que sua aplicação vai crescendo. Todos os valores são expressos em Dólar Americano (USD).',
  PLAN_FEATURES: 'Características',
  DEVICE_MANAGEMENT: 'Gerenciamento de Dispositivos',
  DEVICE_MANAGEMENT_SPAN_FREE: 'Conecte até 5 dispositivos',
  DASHBOARD_CREATION: 'Criação de Painéis',
  DASHBOARD_CREATION_SPAN_FREE: 'Crie até 5 painéis',
  NATIVE_SHARE_CAPABILITY: 'Compartilhação nativa de dados',
  RUN_ANALYSIS: 'Execução de código em tempo-real',
  RUN_ANALYSIS_SPAN_FREE: 'rode até 250 scripts/hora',
  API_REQUESTS: 'Requisições controlada de API',
  API_REQUESTS_SPAN_FREE: 'até 250 / hora',
  API_REQUESTS_SPAN_STARTER: 'até 10,000 / hora',
  API_REQUESTS_SPAN_SCALE_ENTERPRISE: '+ 10,000 / hora',
  CONFIGURABLE_MAX_REQUEST: 'Controle de limite de acesso',
  DATA_RETENTION_CONTROL: 'Controle de Retenção de Dados',
  DATA_RETENTION_CONTROL_SPAN_FREE: 'limitado a 30 dias',
  AUTOMATIC_DATA_BACKUP: 'Backup Automático',
  TAGS_MANAGEMENT: 'Gerenciamento de Etiquetas',
  USER_PROFILE_MANAGEMENT: 'Gerenciamento de Usuários',
  USER_PROFILE_MANAGEMENT_STARTER: 'Adicione mais 1 usuário',
  USER_PROFILE_MANAGEMENT_SCALE: 'Adicione até 5 usuários',
  USER_PROFILE_MANAGEMENT_ENTERPRISE: 'Número ilimitado de usuários',
  COMPLETE_AUDIT_LOG: 'Log de Auditoria',
  COMPLETE_AUDIT_LOG_STARTER: 'limitado somente aos logs da conta',
  EMBED_WIDGET_CREATION: 'Criação de Widget embarcados',
  SLA: 'SLA',
  PREMIUM_WIDGETS: 'Widgets Prêmio',
  PRIVATE_SLACK_CHANNEL: 'Canal Privado no Slack',
  CUSTOMIZED_MIDDLEWARE_FOR_ANY_DEVICE: 'Servidor de Middleware Customizado',
  REALESE_SOLUTION_EXPLORE: 'Publicaçāo no Explore',
  WHITELABEL_VERSION: 'Versão WhiteLabel',
  SERVICE_USAGE: 'Uso dos Serviços',
  SERVICE_USAGE_DESCRIPTION: 'Pague somente pelos serviços alocados. Não cobramos por números de dispositivos, painéis, ou usuários. Os custos do uso são cobrados mensalmente baseado na transações realizadas e na quantidade de dados armazenadas.',
  SERVICE: 'Serviço',
  COST: 'Custo (USD)',
  UNIT: 'Unidade',
  ANALYSIS_RUNNING_SRIPTS: 'Analysis (execução de código)',
  ANALYSIS_RUNNING_SRIPTS_SPAN: 'Execute códigos para processar dados dos seus dispositivos. Cada execução deve ser concluida em até 30s.',
  ANALYSIS_RUNNING_SRIPTS_COST: '$0.100',
  ANALYSIS_RUNNING_SRIPTS_UNIT: '1,000 execuções',
  USAGE_API_REQUESTS: 'Requisições',
  USAGE_API_REQUESTS_SPAN: 'Qualquer acesso feito pelas APIs usando POST, GET ou DELETE',
  USAGE_API_REQUESTS_COST: '$0.025',
  USAGE_API_REQUESTS_UNIT: '1,000 requisições',
  STORAGE_ONLINE_DATA: 'Armazenamento - Online',
  STORAGE_ONLINE_DATA_SPAN: 'Dados online estão sempre disponiveis para visualização e processamento.',
  STORAGE_ONLINE_DATA_COST: '$0.015',
  STORAGE_ONLINE_DATA_UNIT: '1,000 requisições',
  STORAGE_ONLINE_BACKUP: 'Armazenamento - Backup',
  STORAGE_ONLINE_BACKUP_SPAN: 'Dados de backup são mantidos offline.',
  STORAGE_ONLINE_BACKUP_COST: '$0.005',
  STORAGE_ONLINE_BACKUP_UNIT: '1,000 registros',
  USAGE_SMS: 'SMS',
  USAGE_SMS_SPAN: 'Preços para envio de SMS nos EUA e Canadá (entre em contato para outros países).',
  USAGE_SMS_COST: '$0.025',
  USAGE_SMS_UNIT: '1 unidade',
  USAGE_EMAIL: 'E-mail',
  USAGE_EMAIL_COST: '$0.025',
  USAGE_EMAIL_UNIT: '1,000 unidades',
  CONTACT_SALES_TEAM_TALK: 'Contate nosso time de Vendas sobre descontos para alto volume de uso.',
  PRICING_TALK_TO_SALES: 'Fale com Vendas',
  PRICING_EXAMPLES: 'Estimativa de Preços',
  PRICING_EXAMPLE_1: 'Exemplo 1',
  PRICING_EXAMPLE_1_DESCRIPTION: 'Se você seleciona o plano Starter, adiciona 100 dispositivos que enviam (POST) um pacote de dados de 4 variáveis por hora, seus custos podem ser estimados como descrito a seguir:',
  PRICING_EXAMPLE_1_MONTHLY_PLAN: 'Plano selecionado:',
  PRICING_EXAMPLE_1_MONTHLY_PLAN_VALUE: 'Starter $49',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE: 'Uso mensal dos serviços:',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE1: 'Numero de Transações de Entradas de dados = 4 * 100 = 400/h.',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE2: 'Recomendação do serviço Transações de Entradas de dados = 5,000/h',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE3: 'Custo mensal das Transações de Entradas de dados= $0',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE4: 'Número de registros armazenados mensalmente = 4 * 100 * 24 * 30 = 288,000',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE5: 'Recomendação do serviço de Armazenamento = 1,000,000',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE6: 'Custo mensal do armazenamento = $15',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE7: 'Sub-total mensal do uso dos serviços = $ 0 + $15 = $15',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES: 'Custo mensal total:',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES_VALUE1: 'Custo mensal total = Custo do Plano + custo do uso = $49 + $15 = USD $ 64',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES_VALUE2: 'ou seja USD $0.64 / dispositivo',
  PRICING_EXAMPLE_2: 'Exemplo 2',
  PRICING_EXAMPLE_2_DESCRIPTION1: 'Você seleciona o plano Scale e adiciona 1,000 dispositivos que enviam um pacote de dados de 4 variáveis por hora.  ',
  PRICING_EXAMPLE_2_DESCRIPTION2: 'Seus custos podem ser estimados como descrito a seguir:',
  PRICING_EXAMPLE_2_MONTHLY_PLAN: 'Plano selecionado:',
  PRICING_EXAMPLE_2_MONTHLY_PLAN_VALUE: 'Scale $199',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE: 'Uso mensal dos serviços:',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE1: 'Numero de Transações de Entradas de dados = 4 * 1,000 = 4,000/h.',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE2: 'Recomendação do serviço Transações de Entradas de dados = 5,000/h',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE3: 'Custo mensal das Transações de Entradas de dados= $0',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE4: 'Número de registros armazenados mensalmente = 4 * 1,000 * 24 * 30 = 2,880,000',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE5: 'Recomendação do serviço de Armazenamento = 3,000,000',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE6: 'Custo mensal do armazenamento = $40',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE7: '',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE8: '',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE9: 'Sub-total mensal do uso dos serviços = $0 + $40 = $40',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE10: '',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES: 'Custo mensal total:',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES_VALUE1: 'Custo mensal total = Custo do Plano + custo do uso = $199 + $40= USD $239',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES_VALUE2: 'ou seja USD $0.23 / dispositivo',
  FREQUENTLY_ASKED_QUESTIONS: 'Perguntas frequentes',
  PRICING_QUESTION1: 'Pelo que será cobrado?',
  PRICING_RESPONSE1: 'Diferente de outros provedores, o TagoIO não cobra pelo número de dispositivos, painéis ou até usuários. Nosso modelo é baseado no uso real dos serviços, ou em outras palavras, o sistema cobra pelos Serviços alocados para o mês e pelas ferramentas que são disponibilizados dependendo do seu plano. Assim, a fatura mensal será uma soma do plano que você selecionou mais os serviços. Você também pode incluir alguns complementos, como os planos de Suporte.',
  PRICING_QUESTION2: 'Qual é o ciclo de faturamento da TagoIO?',
  PRICING_RESPONSE2: 'O TagoIO fecha o período de cobrança à meia-noite do último dia de cada mês. Geralmente, as faturas estão disponíveis nos primeiros quatro dias do mês subsequente. ',
  PRICING_QUESTION3: 'Se eu fizer o upgrade do meu plano, como isso será cobrado?',
  PRICING_RESPONSE3: 'Cobramos proporcionalmente uma única vez no momento da atualização pelo lembrete equivalente do ciclo de faturamento. Por exemplo, se você fizer upgrade do plano Gratuito para o plano Iniciante quando houver 10 dias restantes no mês, cobraremos 1/3 do preço mensal do Starter imediatamente ao confirmar a atualização. No próximo mês, cobraremos o preço total do plano inicial. Além disso, qualquer uso de serviço e complementos serão adicionados à próxima fatura.',
  PRICING_QUESTION4: 'Quais são as formas de pagamento aceitas?',
  PRICING_RESPONSE4: 'A TagoIO aceita a maioria dos principais cartões de crédito para pagamento. Em casos específicos, poderemos cobrar os clientes diretamente, converse com nossa equipe de vendas para mais detalhes.',
  PRICING_QUESTION5: 'A TagoIO armazena dados do cartão de crédito?',
  PRICING_RESPONSE5: 'Não. Os dados do seu cartão de crédito não são salvos em nossos servidores. De fato, todas as informações vão diretamente do seu computador para o nosso provedor de serviços de pagamento (Stripe).',
  PRICING_QUESTION6: 'Se eu fizer downgrade do meu plano, quando será efetuada de fato a atualização?',
  PRICING_RESPONSE6: 'Nós faremos o downgrade para o novo plano selecionado na próxima data de renovação. Sua assinatura permanecerá ativa no nível atual até o final do período de faturamento que você já pagou.',
  PRICING_QUESTION7: 'Se eu fizer downgrade para um plano gratuito, o que acontecerá com os dados armazenados na TagoIO?',
  PRICING_RESPONSE7: 'Primeiro, sua assinatura permanecerá ativa no nível atual até o final do período de faturamento que você já pagou. Então, enquanto no plano gratuito, nosso sistema forçará a política de retenção de dados por 30 dias - ou seja, todos os dados com registro de data e hora mais antigos serão removidos. Recomendamos que você planeje essa operação com cuidado para evitar a perda de dados indesejados.',
  PRICING_QUESTION8: 'Como o tempo limite de análise é definido?',
  PRICING_RESPONSE8: 'Quando a análise executa seu script, o tempo de execução deve ser menor que o tempo limite definido para o seu plano. Você pode monitorar o status usando o recurso Console.',
  PRICING_ADDITIONAL_COAST: 'Custos adicionais',
  PRICING_ALL_FEATURES: 'Todos recursos',
  PRICING_COLLAPSE_ALL: 'Esconder todos',
  PRICING_EXPAND_ALL: 'Mostrar todos',
  PRICING_NOT_INCLUDED: 'Não incluído',
  PRICING_SOME_FEATURES: 'Alguns recursos',
  PRICING_MANAGE_DEVICES: 'Gerenciamento de Dispositivos',
  PRICING_CONNECT_UNLIMITED_NUMBER_DEVICES: 'Numero máximo de dispositivos',
  PRICING_UP_TO: 'até',
  PRICING_TAGS_FOR_MANAGEMENT: 'Tags para gerenciamento',
  PRICING_HELP_1: 'Não cobramos com base no número de dispositivos conectados. Cada dispositivo recebe um token exclusivo para acessar sua conta.',
  PRICING_HELP_2: 'Gerencie todos os seus dispositivos usando Tags e organize-os por grupos.',
  PRICING_HELP_3: 'Cada vez que um dispositivo envia um registro de dado, ele é contado como uma transação de Entrada de Dados.',
  PRICING_CREATE_DASHBOARDS: 'Criação de painéis',
  PRICING_BUILD_UNLIMITED_NUMBER_DASHBOARDS: 'Numero máximo de paineis',
  PRICING_PREMIUM_WIDGETS: 'Premium widgets',
  PRICING_EMBEDDED_WIDGETS: 'Embedded widgets',
  PRICING_HELP_4: 'Use nossas ferramentas poderosas e fáceis de usar para criar ótimas visualizaçoões de dados.',
  PRICING_HELP_5: 'Utilize widgets avançados que facilitam a interação dos usuários com seu aplicativo.',
  PRICING_HELP_6: 'Adicione widgets no seu site ou portal. A versão Scale permite remover a marca d\'água \'Runs on Tago\'.',
  PRICING_GO_MOBILE: 'Utilização no celular',
  PRICING_MOBILE_APP_ANDROIND_IOS: 'Aplicação para celular - Android & iOS',
  PRICING_HELP_7: 'TagoIO mobile está disponível gratuitamente para todos os usuários sem custo.',
  PRICING_RUN_ANALYSIS_REAL_TIME: 'Execução de análises em tempo real',
  PRICING_RUN_SCRIPTS_ANALYZE_DATA: 'Execução de scripts para analisar dados',
  PRICING_RUN_MACHINE_LEARNING_REAL_TIME: 'Execução machine learning em tempo real',
  PRICING_HELP_8: 'Faça o upload do seu próprio script na Análise da Tago para processar dados em tempo real.',
  PRICING_HELP_9: 'Fale com nosso suporte técnico para usar o Machine Learning para fazer previsões que trarão valor adicional aos suas aplicações.',
  PRICING_SHARE_YOUR_APPLICATION_AND_DATA: 'Compatilhamento aplicação e seus dados',
  PRICING_NATIVE_SHARING_FOR_DASHBOARDS: 'Compartilhamento nativo de Painéis',
  PRICING_NATIVE_SHARING_FOR_DATA_BUCKETS: 'Compartilhamento nativo de Buckets',
  PRICING_HELP_10: 'Com um clique, voce compartilha painéis com qualquer pessoa, pública ou privada. Usuários sem conta na TagoIO receberāo convites',
  PRICING_HELP_11: 'Com um clique, a TagoIO permite compartilhar seus dados com qualquer pessoa com segurança.',
  PRICING_AUTOMATE_EXPAND_SOLUTIONS_WITH_INTEGRATION: 'Automatize e expanda soluções com integração',
  PRICING_CONNECT_ANY_APP: 'Conecte-se a qualquer aplicativo',
  PRICING_CONNECT_SIGFOX_LORAWAN: 'Conecte-se com Sigfox, LoRaWan...',
  PRICING_NATIVE_INTEGRATION_MICROSOFT_FLOW: 'Integração nativa com Microsoft Flow',
  PRICING_NATIVE_INTEGRATION_CRM: 'Integração nativa com CRMs',
  PRICING_INTEGRATED_CUSTOMIZED_MIDDLEWARE: 'Integrado com middleware customizado',
  PRICING_HELP_12: 'Conecte sistemas externos a Tago usando nossa API RESTful fácil de usar',
  PRICING_HELP_13: 'Conecte seu dispositivo usando nosso conector para Sigfox, provedores LoRa e outros provedores de rede',
  PRICING_HELP_14: 'Integre sua solução com Googlesheets, Excel, Zendesk, Twitter e centenas de serviços por meio do Microsoft Flow',
  PRICING_HELP_15: 'Identifique mais oportunidades de vendas integrando seu CRM com a Tago',
  PRICING_HELP_16: 'Conecte a qualquer protocolo. Nosso middleware pode converter de UDP, TCP/IP ou conectar-se a vários formatos de banco de dados.',
  PRICING_SCALE_CONFIDENCE: 'Escale com segurança',
  PRICING_MONITORING_EVERY_TRANSACTION_AUDIT_LOG: 'Monitore todas as transações com Log de Auditoria',
  PRICING_SRIPTS_THAT_GRANT_DIFFERENT_LEVELS_ACCESS: 'Scripts concedem diferentes níveis de acesso',
  PRICING_ADD_USERS_MANAGE_ACCOUNT: 'Adicione usuários para gerenciar sua conta',
  PRICING_HELP_17: 'O registro de auditoria irá acompanhar quem acessou sua conta, que tipo de operações foram feitas e quando. O plano Starter oferece alguns recursos.',
  PRICING_HELP_18: 'Novos usuários terão acesso ao seu aplicativo com base no nível que você conceder a eles.',
  PRICING_HELP_19: 'Não cobramos pelos usuários finais, você pode compartilhar seu aplicativo sem nenhum custo para você ou seu cliente. Um usuário desenvolvedor adicional para o plano Starter e 10 para Scale',
  PRICING_BACK_UP_YOUR_DATA: 'Faça backup de seus dados',
  PRICING_DOWNLOAD_YOUR_DATA: 'Baixe seus dados',
  PRICING_DATA_RETENTION_POLICY: 'Política de retenção de dados',
  PRICING_LIMITED_30_DAYS: 'limitado a 30 dias',
  PRICING_OFF_LINE_DATA_BACKUP_REDUCES_STORAGE_COST: 'Backup de dados off-line reduz o custo de armazenamento',
  PRICING_MAXIMUM_OUTPUT_DATA_TRANSACTIONS_PER_HOUR: 'Máxima saída de dados por hora',
  PRICING_MAXIMUM_INPUT_DATA_TRANSACTIONS_PER_HOUR: 'Máxima entrada de dados por hora',
  PRICING_HELP_20: 'Abaixe seus dados nos formatos .csv, JSON ou XML.',
  PRICING_HELP_21: 'Determine por quanto tempo os dados devem ser mantidos.',
  PRICING_HELP_22: 'Configure seu backup conforme necessário. Custo de armazenamento off-line é uma fração do custo on-line.',
  BRAND_ENGAGEMENT: 'TagoRun - Publicando sua Aplicação',
  ADD_YOUR_LOGO_YOUR_APPLICATION: 'Adicione seu logotipo na aplicação',
  WHITE_LABEL_VERSION: 'Versão white-label',
  PRICING_HELP_23: 'Adicione o logotipo usando nossos widgets de imagem e vídeo',
  PRICING_HELP_24: 'Adicione seu próprio logotipo, cores e URL para engajar os clientes com sua marca.',
  PRICING_SERVICES_MAXIMUM_INPUT_PER_HOUR: 'Máxima entrada de dados por hora',
  PRICING_SERVICES_MAXIMUM_OUTPUT_PER_HOUR: 'Máxima saída de dados por hora',
  PRICING_SERVICES_TOTAL_NUMBER_OF_REGISTERS: 'Quantidade de dados disponiveis',
  PRICING_SERVICES_MAXIMUM_RUN_PER_HOUR: 'Máxima execução por hora',
  PRICING_SERVICES_MAXIMUM_PER_MONTH: 'Máxima execução por mês',
  PRICING_SERVICES_DATA_INPUT_TRANSACTIONS: 'Transações de entrada de dados',
  PRICING_SERVICES_DATA_OUTPUT_TRANSACTIONS: 'Transações de saída de dados',
  PRICING_SERVICES_ANALYSIS_RUNS: 'Execuções de análises',
  PRICING_SERVICES_DATA_REGISTERS_STORED: 'Dados armazenados',
  PRICING_SERVICES_SMS_SENT: 'SMS',
  PRICING_SERVICES_E_MAIL_SENT: 'E-Mail',
  PRICING_SERVICES_USAGE_ALLOC: 'Preços flexíveis e acessíveis',
  PRICING_SERVICES_USAGE_LOCATION_DESC: 'Você paga apenas pelos serviços contratados. Não cobramos por dispositivos, painéis ou usuários que utilizam seus painéis. Estime seu custo mensal usando as barras de configuração com base no uso estimado ou usando nossa Calculadora abaixo.',
  PRICING_FOR_DEVELOPERS_STUDENTS: 'Para desenvolvedores e estudantes que começam com a TagoIO',
  PRICING_FOR_DEVELOPERS_BUSINESSES: 'Para desenvolvedores e empresas que estão se preparando para liberar aplicativos',
  PRICING_FOR_BUSINESSES_READY_TO_SCALE: 'Para empresas prontas para ampliar aplicativos e otimizar suas operações',
  PRICING_ESTIMATED_MONTHLY_COST: 'Estimativa do custo mensal',
  PRICING_THIS_IS_PART_OF_SERVICES: 'O plano faz parte dos Serviços e precisa ser selecionado para o período (consulte os preços abaixo para um período de provisionamento de um mês)',
  PRICING_THIS_PAGE_IS_PROVIDED: 'Esta página é fornecida apenas para fins informativos e não tem garantia de estar livre de erros, nem está sujeita a quaisquer outras garantias.',
  PRICING_CALCULATOR: 'Calculadora de Preços',
  PRICING_CALCULATOR_HMANYDE: 'Quantos dispositivos?',
  PRICING_CALCULATOR_HMANYREG: 'Quantos registros enviados por pacote?',
  PRICING_CALCULATOR_HOFTENDATA: 'Qual a frequência de envio de dados?',
  PRICING_CALCULATOR_HOFTENDATA_SEC: 'Segundos',
  PRICING_CALCULATOR_HOFTENDATA_MIN: 'Minutos',
  PRICING_CALCULATOR_HOFTENDATA_HOUR: 'Horas',
  PRICING_CALCULATOR_HWILLRUNAN: 'Deve rodar uma Analysis para cada dado?',
  PRICING_CALCULATOR_YES: 'Sim',
  PRICING_CALCULATOR_NO: 'Não',
  PRICING_CALCULATOR_HMSMS: 'Quantos SMS devem ser enviados por hora?',
  PRICING_CALCULATOR_HMEMAIL: 'Quantos Emails devem ser enviados por hora?',
  PRICING_CALCULATOR_SERVNAME: 'Nome do Serviço',
  PRICING_CALCULATOR_CALCUSE: 'Uso Calculado',
  PRICING_CALCULATOR_H: '/h',
  PRICING_CALCULATOR_MO: '/mês',
  PRICING_CALCULATOR_REGISTERS: 'Registros',
  PRICING_CALCULATOR_TALKSALES: 'Fale com Vendas',
  PRICING_CALCULATOR_SHOWPRICES: 'Atualize o Preço Estimado',
  PRICING_CALCULATOR_INFO: 'Use nossa calculadora para estimar seu custo mensal. Um registro é contado para cada variável (ex. Temperatura) incluindo seu metadata (ex. localização). Para simplificar, assumimos que cada Analysis fará a leitura de 10 registros por vez, o que significa 10 Transaçoes de Data Output por Analysis. E também para o exemplo os registros são mantidos por 1 mês. Clique no botão Atualize o Preço Estimado para atualizar os cálculos. Leia mais sobre como as transações de cada serviço são',
  PRICING_CALCULATOR_LINK_INFO: 'calculados aqui',
  PRICING_DESCRIPTION: 'O modelo de precificação do TagoIO é flexível e baseado no Plano e Serviços provisionados para sua aplicação. Você paga apenas pelos serviços que seleciona e pode usar nossa calculadora de preços para estimar seu custo mensal com base nas características de seu projeto.',
  PRICING_MAXIMUM_POLICIES: 'Numero máximo de políticas',
  PRICING_MAXIMUM_USERS: 'Numero máximo de usuários',
};
