module.exports = {
  ACCOUNT_CREATED: 'Account created',
  BY_CREATING_AN_ACCOUNT_YOU_AGREE_OUR: 'By creating an account you agree to our',
  COMPANY: 'company',
  FIRST_NAME: 'first name',
  I_AM_A: 'I am',
  I_WANT_TO_RECEIVE_NEWS_ABOUT_TAGO: 'I want to receive news about Tago',
  I_WILL_BUILD_APPLICATIONS_TAGO: 'I will build applications on Tago',
  LAST_NAME: 'last name',
  PASSWORD_MUST_CONTAIN_AT_LEAST_SIX_CHARACTERS: 'Password must contain at least 6 characters',
  RETURN_TO_LOGIN_PAGE: 'Return to the login page',
  SIGN_IN_TO_YOUR_ACCOUNT: 'sign in to your account',
  SIGN_UP: 'Sign up',
  TERMS_AND_CONDITIONS: 'Terms & Conditions',
  WE_JUST_NEED_TO_CONFIRM_YOUR_EMAIL: 'We just need to confirm your e-mail. Check your e-mail box for details',
};
