env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  allowImportExportEverywhere: true
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  arrow-parens: 0
  arrow-body-style: 0
  camelcase: 0
  class-methods-use-this: 0

  global-require: 0

  import/no-dynamic-require: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0

  no-restricted-globals: 0
  no-dynamic-import: 0
