env:
  browser: true
  commonjs: true
  es6: true
  jasmine: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  arrow-body-style: 0
  arrow-parens: 0
  camelcase: 0
  class-methods-use-this: 0

  import/extensions: 0
  import/imports-first: 0
  import/newline-after-import: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0

  jasmine/new-line-before-expect: 0
  jsx-a11y/href-no-hash: 0
  jsx-a11y/anchor-has-content: 0
  jsx-a11y/label-has-for: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/no-noninteractive-tabindex: 0

  react/forbid-prop-types: 0
  react/no-multi-comp: 0
  react/prefer-stateless-function: 0
  react/no-string-refs: 1
  no-restricted-globals: 0
