module.exports = {
  CONTACT_US_FOOTER: 'Contato',
  TAGO_NAME: 'Tago LLC',
  TAGO_ADDRESS: '1017 Main Campus Drive, Sala 2300',
  TAGO_CITY: 'Raleigh, Carolina do Norte, 27606 - Estados Unidos',
  TAGO_PHONE_TEXT: 'Fone:',
  TAGO_PHONE_NUMBER: '(800) 607-7410',
  TAGO_PHONE_HREF: 'tel:8006077410',
  TAGO_EMAIL_TEXT: 'E-mail:',
  TAGO_EMAIL_ADRESS: 'contact@tago.io',
  TAGO_EMAIL_HREF: 'mailto:contact@tago.io',
  TAGO_RESERVED_SYMBOL: '©',
  TAGO_RESERVED: ' - TAGO LLC. TODOS OS DIREITOS RESERVADOS',
  ABOUT_US: 'Sobre nós',
  ABOUT_US_DESCRIPTION: 'A TagoIO oferece uma plataforma de IoT na nuvem de ponta a ponta que transforma a maneira como as empresas criam valor a partir de dispositivos conectados, tornando seus processos efetivos e inteligentes.',
  OUR_LINKS_FOOTER: 'Links úteis',
  TERMS_SUPPORT_FOOTER: 'Suporte',
  PRIVACY_FOOTER: 'Termos de Privacidade',
  FAQ_FOOTER: 'FAQ',
  BLOG_FOOTER: 'Blog',
  DOCUMENTATION_FOOTER: 'Documentação',
  COMMUNITY_FOOTER: 'Comunidade',
  GITHUB_FOOTER: 'GitHub',
  API_FOOTER: 'API',
};
