module.exports = {
  ACCEPT: 'Aceitar',
  ACCEPTED: 'Aceito',
  ACCOUNT: 'conta',
  ALL: 'Todos',
  APPLICATION: 'Aplicação',
  APPLICATIONS: 'Aplicações',
  APRIL: 'Abril',
  ARE_YOU_SURE: 'Você tem certeza',
  AUDIT_LOG: 'Log de auditoria',
  AUGUST: 'Agosto',
  BACK: 'Voltar',
  BACKGROUND_IMAGE: 'Imagem de fundo',
  CANCEL: 'Cancelar',
  CLEAR: 'Limpar',
  CLICK: 'Clique',
  CLOSE: 'Fechar',
  COLLAPSE: 'Recolher',
  COMMA: 'Vírgula',
  SEMICOLON: 'Ponto e vírgula',
  COMPANY: 'Empresa',
  CUSTOM: 'Personalizado',
  DATE_FORMAT: 'Formato da data',
  DAY: 'Dia',
  DASHBOARD: 'Painel',
  DASHBOARDS: 'Painéis',
  DECEMBER: 'Dezembro',
  DECLINE: 'Recusar',
  DECLINED: 'Recusado',
  DELETE: 'Excluir',
  DEVELOPER: 'Desenvolvedor',
  DEVICES: 'Dispositivos',
  DOT: 'Ponto',
  EMAIL: 'E-mail',
  END_DATE: 'Data final',
  ENTER_EMBED_URL: 'entre com a url do embed',
  ENTER_IMAGE_URL: 'entre com a url da imagem',
  ENTER_NAME: 'entre com o nome',
  ENTER_EMAIL: 'entre com o email',
  ENTER_LABEL: 'entre com o rótulo',
  ENTER_YOUR_EMAIL: 'enter com seu email',
  EXPAND: 'Expandir',
  FEBRUARY: 'Fevereiro',
  FILTER: 'filtrar',
  FINISH: 'Finalizar',
  FREE: 'gratuita',
  FRIDAY: 'Sexta',
  FROM: 'De',
  GENERAL_INFORMATION: 'Informações gerais',
  GO_TO: 'Ir para',
  HERE: 'aqui',
  HOUR: 'Hora',
  IGNORE: 'Ignorar',
  IMAGE: 'Imagem',
  INDEFINITELY: 'Indefinidamente',
  INFORMATION: 'Informação',
  INVITE: 'Convidar',
  JANUARY: 'Janeiro',
  JULY: 'Julho',
  JUNE: 'Junho',
  LANGUAGE: 'Idioma',
  LOCATION: 'localização',
  MARCH: 'Março',
  MAY: 'Maio',
  MINUTE: 'Minuto',
  MONDAY: 'Segunda',
  MONTH: 'Mês',
  MORE: 'Mais',
  MY_ACCOUNT: 'Minha conta',
  MY_BILLING: 'Meu faturamento',
  NAME: 'Nome',
  NEXT: 'Próximo',
  NO: 'Não',
  NO_OPTIONS: 'Sem opções',
  NOTIFICATIONS: 'Notificações',
  NOVEMBER: 'Novembro',
  OCTOBER: 'Outubro',
  OF_PAGINATION: 'De',
  OR: 'ou',
  REFUSED: 'Recusado',
  PASSWORD: 'senha',
  PENDING: 'Pendente',
  PLAN: 'Plano',
  PHONE: 'Telefone',
  PLEASE_CHECK_YOUR_EMAIL: 'Favor, verifique seu email',
  PLEASE_ENTER_YOUR_EMAIL: 'Favor, digite seu email',
  PLEASE_ENTER_REQUIRED_FIELDS: 'Favor, preencher os campos obrigatórios',
  PREVIOUS: 'Anterior',
  SATURDAY: 'Sábado',
  SAVE: 'Salvar',
  SECOND: 'Segundo',
  SELECT_ALL: 'Selecionar tudo',
  SELECT_FILE: 'Selecione um arquivo',
  SELECT_VALUE: 'selecione um valor',
  SELECT_IMAGE: 'selecione uma imagem',
  SEPTEMBER: 'Setembro',
  SERVICES: 'Serviços',
  SHARE: 'Compartilhar',
  SIGN_OUT: 'Sair',
  SOUND: 'Som',
  START_DATE: 'Data inicial',
  SUBMIT: 'Enviar',
  SUNDAY: 'Domingo',
  THIS_FIELD_IS_REQUIRED: 'Esse campo é obrigatório',
  THIS_FIELD_REQUIRES_AT_LEAST_THREE_CHARACTERS: 'Esse campo requer ao menos 3 letras',
  THIS_FIELD_REQUIRES_VALID_HTTPS_URL: 'Esse campo requer uma url HTTPS válida',
  TIME_FORMAT: 'Formato do tempo',
  TIMEZONE: 'Fuso horário',
  THURSDAY: 'Quinta',
  TUESDAY: 'Terça',
  UNDO: 'Desfazer',
  VALUE: 'Valor',
  VARIABLE: 'Variável',
  WEDNESDAY: 'Quarta',
  WEEK: 'Semana',
  YEAR: 'Ano',
  YES: 'Sim',
  CONFIGURATION: 'Configurar',
  DASHBOARDS_SHARE_DASHBOARD: 'Compartilhar',
  DUPLICATE_DASHBOARD: 'Duplicar',
  BUILD_TEMPLATE: 'Distribuir',
  DASHBOARDS_DELETE_DASHBOARD: 'Remover',
  DISMISS: 'Dispensar',
  NOT_A_DEVELOPER: 'Não é um desenvolvedor?',
  A_DEVELOPER: 'Você é um desenvolvedor? Clique aqui',
  NOTIFICATION: 'Notificação',
  SHARE_DASHBOARDS: 'Compartilhar painéis',
  WELCOME: 'Olá, como vai',
  REALTIME: 'Conexão',
  CONNECTED: 'Conectado',
  DISCONNECTED: 'Desconectado',
  WELCOME_DEVELOPER: 'Bem vindo Desenvolvedor',
  CHANGE_MY_SETTINGS: 'Alterar minhas configurações',
  EXPLORE: 'Explorar',
  CLICK_HERE: 'Clique aqui',
  IGNORED: 'Ignorado',
  MAP: 'Mapa',
  SATELLITE: 'Satélite',
  NEW_HERE: 'Novo por aqui?',
  ALREADY_HAVE_AN_ACCOUNT: 'Já tem uma conta?',
  PUBLIC_DASHBOARD: 'Painél Publico',
  UNLIMITED: 'Ilimitado',
  ADD_PROFILES: 'Adicionar Perfis',
  USER_MANAGEMENT: 'Gestão de usuários',
  ACCESS_MANAGEMENT: 'Gestão de acesso',

  CONFIRM_YOUR_E_MAIL_BEFORE_PROCEEDING: 'Confirme sua conta antes do primeiro acesso.',
  ACCOUNT_CREATION_HAS_BEEN_SUBMITTED: 'Conta criada e submetida para aprovação',
  YOUR_ACCOUNT_WAS_CREATED: 'Sua conta foi criada!',
  YOU_WILL_BE_NOTIFIED_WHEN_IT_IS_ACTIVATED: 'Você será notificado quando a conta estiver ativa.',

  NO_NOTIFICATIONS: 'Nenhuma notificação',
  NO_DASHBOARDS: 'Nenhum painel',
  NO_CONTENT: 'Sem conteúdo',

  MAP_BASIC: 'Mapa Basico',
  MAP_DARK: 'Mapa Escuro',
  MAP_LIGHT: 'Mapa Claro',

  AGREE_WITH: "Eu concordo com os",
  DYNAMIC_TABLE_ROW_DELETED: "A linha foi excluída com sucesso.",
  DYNAMIC_TABLE_ROW_EDITED: "Linha editada com sucesso!",
  DYNAMIC_TABLE_SEARCH: "buscar",
  LAST_UPDATE_AT: "Última atualização",
  PRESET_CALENDAR_CUSTOM: "Personalizado",
  PRESET_CALENDAR_DAY: "Dia",
  PRESET_CALENDAR_MINUTE: "Minuto",
  PRESET_CALENDAR_MONTH: "Mês",
  PRESET_CALENDAR_SECOND: "Segundo",
  PRESET_CALENDAR_WEEK: "Semana",
  PRESET_CALENDAR_YEAR: "Ano",
  PRESET_CALENDAR_FOREVER: "Sempre",

  EXPORT_CSV_DOWNLOAD: "Baixar arquivo",
  EXPORT_CSV_MODAL_TITLE: "Exportar CSV",
  EXPORT_CSV_SELECT_SEPARATOR: "Selecione o separador para o arquivo CSV",
  SEMICOLON: "Ponto e vírgula",

  NOTIFICATION_CLICK_ON: "Clique em",
  NOTIFICATION_CONFIRMATION_READ_ALL_CONFIRM: "Sim, marcar todas notificações como lidas",
  NOTIFICATION_CONFIRMATION_READ_ALL_DESC:
    "Quer realmente marcar todas as notificações como lidas? Isso pode demorar um pouco dependendo da quantidade de notificações.",
  NOTIFICATION_DELETE: "Deletar notificação",
  NOTIFICATION_FILTERED_BY: "Filtrado por:",
  NOTIFICATION_MARK_ALL_AS_READ: "Marcar todas as notificações como lidas",
  NOTIFICATION_MARK_AS_READ: "Marcar como lída",
  NOTIFICATION_MARK_AS_UNREAD: "Marcar como não lída",
  NOTIFICATION_NONE: "Você não possui notificações",
  NOTIFICATION_NOT_FOUND: "Nenhuma notificação encontrada",
  NOTIFICATION_SHOW_ALL: "Mostrar todas notificações",
  NOTIFICATION_SHOW_UNREAD: "Mostrar somente notificações não lidas",
  NOTIFICATION_TO_SEE_ALL: "para ver todas as notificações.",
  NOTIFICATION_UNREAD: "Não lidas",
  NOTIFICATION_YOUVE_READ_ALL: "Você leu todas!",

  DELETE_ACCOUNT: "Excluir conta",
  ARE_YOU_SURE_DELETE_ACCOUNT: "Tem certeza? A exclusão de uma conta é uma ação irreversível.",
  CONFIRM_DELETE_ACCOUNT: "Sim, excluir minha conta",
  DELETE_ACCOUNT_MESSAGE: "Uma solicitação para excluir a conta foi enviada!",
  MOBILE_RUN_ACCOUNT_SETTINGS: "Configurações da conta",
  MOBILE_RUN_DELETE_ACCOUNT: "Excluir conta",
  MOBILE_SETTINGS_DORELLY_DELETE_ACCOUNT: "Tem certeza? A exclusão de uma conta é uma ação irreversível.",

  "2FA_AUTHENTICATION": "Autenticação de dois fatores",
  SECURITY_PREFERENCES: "Preferências de segurança",
  APP_AUTHENTICATOR: "Aplicativo autenticador",
  SMS: "SMS",
  "2FA_CONFIGURED": "Configurado",
  "2FA_YOU_HAVE_ENABLED": "Você tem a autenticação de dois fatores habilitada.",
  "2FA_APP_AUTHENTICATOR_TIP": "Seu aplicativo exibirá um código de autenticação.",
  "2FA_6_DIGIT_CODE": "Código de 6 digitos",
  "2FA_CANT_ACCESS_DEVICE": "Não consegue acessar seu dispositivo de dois fatores?",
  "2FA_CODE_INCORRECT": "O código que você digitou está incorreto",
  "2FA_ADD": "Adicionar autenticação de dois fatores",
  "2FA_INTRODUCTION":
    "A autenticação de dois fatores é uma camada extra de segurança usada ao fazer login em sites ou aplicativos.",
  "2FA_INTRODUCTION_REINFORCEMENT":
    "Após ser configurado, a única maneira de alguém entrar na sua conta é se souber a senha e tiver acesso ao código de autenticação.",
  "2FA_HOW_TO_APP_AUTHENTICATOR":
    "Use um aplicativo em seu telefone para obter quando solicitado códigos de autenticação de dois fatores. Recomendamos o uso de TOTP baseado em nuvem, como: 1Password, Microsoft Authenticator, Google Authenticator.",
  CONFIRM_THIS_ACTION_BY_PASSWORD: "Confirme esta ação digitando sua senha",
  PASSWORD_INCORRECT: "A senha que você digitou está incorreta",
  "2FA_ENABLED_WARNING":
    "Por motivos de segurança, uma vez habilitada a autenticação de dois fatores, se você perder suas credenciais de autenticação, a única maneira de recuperá-las é entrar em contato com o suporte.",
  "2FA_APP_AUTHENTICATOR_CONFIG":
    "Digitalize a imagem abaixo com o aplicativo de autenticação de dois fatores em seu telefone. Se você não puder usar um código QR, digite o seguinte código de texto:",
  "2FA_YOU_ARE_ENABLING": "Você está habilitando a autenticação de dois fatores",
  "2FA_ADD_METHOD": "Adicionar método de autenticação",
  "2FA_SETTINGS_BEEN_SAVED":
    "As configurações do autenticador de dois fatores foram salvas. Se você fez outras alterações em seu perfil, clique em Salvar",
  "2FA_SENT_SMS": "Enviamos um SMS com o código de autenticação para o seu telefone",
  MAY_TAKE_A_MINUTE: "Pode demorar até 1 minuto para chegar.",
  "2FA_HAVENT_RECEIVED_CODE": "Não recebeu um código? Envie um novamente.",
  "2FA_YOU_WILL_RECEIVE_SMS_FOR": "Você receberá um SMS com o código de autenticação quando solicitado em:",
  COUNTRY_CODE: "Código do país",
  PHONE_NUMBER: "Número de telefone",
  "2FA_PHONE_CHANGE": "Isso altera as informações de telefone da sua conta.",
  "2FA_WE_HAVE_SENT_YOU_CODE": "Enviamos um novo código. Se isso ainda não funcionar, entre em contato com o suporte",
  "2FA_SENT_EMAIL": "Enviamos um código de autenticação para o seu e-mail.",
  "2FA_YOU_WILL_RECEIVE_EMAIL_FOR": "Você receberá um e-mail com o código de autenticação quando solicitado em:",
  "2FA_REQUEST_NEW_CODE": "Solicitar um novo código",
  "2FA_ENDING_PHONE": "Telefone terminando em",
  "2FA_SENDING_EMAIL_TO": "Enviar um email para",
  "2FA_OR_TYPE_CODE_AGAIN": "Ou digite o código novamente",
  "2FA_TOO_MANY_REQUESTS": "Você fez muitas requisições. E-mail e SMS foram temporariamente desativados.",
  "2FA_REMOVE": "Remover autenticação de dois fatores",
  "2FA_APP_AUTHENTICATOR_REMOVE": "Você removerá seu método Aplicativo autenticador.",
  "2FA_EMAIL_REMOVE": "Você vai remover seu método de e-mail.",
  "2FA_SMS_REMOVE": "Você vai remover seu método SMS.",
  "2FA_REMOVE_MESSAGE": "Depois disso, você simplesmente usará sua senha para entrar.",
  PASSWORD_MIN_LENGTH: "Deve conter a quantidade mínima de caracteres",
  MUST_CONTAIN_SPECIAL_CHARACTERS: "Deve conter pelo menos um carácter especial (@, !, &, …)",
  MUST_CONTAIN_MIX_LETTERS_NUMBERS: "Deve conter uma combinação de letras e números",
  MUST_CONTAIN_UPPER_LOWER_CASE_CHARACTERS: "Deve conter letras maiúsculas e minúsculas",
  STRONG_PASSWORD: "Bom trabalho. Esta é uma excelente senha",
};
