module.exports = {
  ACCEPT: 'Aceitar',
  ACCEPTED: 'Aceito',
  ACCOUNT: 'conta',
  ALL: 'Todos',
  APPLICATION: 'Aplicação',
  APPLICATIONS: 'Aplicações',
  APRIL: 'Abril',
  ARE_YOU_SURE: 'Você tem certeza',
  AUDIT_LOG: 'Log de auditoria',
  AUGUST: 'Agosto',
  BACK: 'Voltar',
  CANCEL: 'Cancelar',
  CLEAR: 'Limpar',
  CLICK: 'Clique',
  CLOSE: 'Fechar',
  COLLAPSE: 'Recolher',
  COMMA: 'Vírgula',
  COMPANY: 'Empresa',
  CUSTOM: 'Personalizado',
  DAY: 'Dia',
  DASHBOARD: 'Painel',
  DASHBOARDS: 'Painéis',
  DECEMBER: 'Dezembro',
  DECLINE: 'Recusar',
  DECLINED: 'Recusado',
  DEVELOPER: 'Desenvolvedor',
  DEVICES: 'Dispositivos',
  DOT: 'Ponto',
  EMAIL: 'E-mail',
  END_DATE: 'Data final',
  ENTER_EMAIL: 'entre com o email',
  ENTER_YOUR_EMAIL: 'enter com seu email',
  EXPAND: 'Expandir',
  FEBRUARY: 'Fevereiro',
  FILTER: 'filtrar',
  FINISH: 'Finalizar',
  FREE: 'gratuita',
  FRIDAY: 'Sexta',
  FROM: 'De',
  GENERAL_INFORMATION: 'Informações gerais',
  GO_TO: 'Ir para',
  HERE: 'aqui',
  HOUR: 'Hora',
  IGNORE: 'Ignorar',
  INDEFINITELY: 'Indefinidamente',
  INFORMATION: 'Informação',
  INVITE: 'Convidar',
  JANUARY: 'Janeiro',
  JULY: 'Julho',
  JUNE: 'Junho',
  LANGUAGE: 'Idioma',
  LOCATION: 'localização',
  MARCH: 'Março',
  MAY: 'Maio',
  MINUTE: 'Minuto',
  MONDAY: 'Segunda',
  MONTH: 'Mês',
  MORE: 'Mais',
  MY_ACCOUNT: 'Minha conta',
  MY_BILLING: 'Meu faturamento',
  NAME: 'Nome',
  NEXT: 'Próximo',
  NO: 'Não',
  NO_OPTIONS: 'Sem opções',
  NOTIFICATIONS: 'Notificações',
  NOVEMBER: 'Novembro',
  OCTOBER: 'Outubro',
  OF_PAGINATION: 'De',
  OR: 'ou',
  REFUSED: 'Recusado',
  PASSWORD: 'senha',
  PENDING: 'Pendente',
  PLAN: 'Plano',
  PHONE: 'Telefone',
  PLEASE_CHECK_YOUR_EMAIL: 'Favor, verifique seu email',
  PLEASE_ENTER_YOUR_EMAIL: 'Favor, digite seu email',
  PLEASE_ENTER_REQUIRED_FIELDS: 'Favor, preencher os campos obrigatórios',
  PREVIOUS: 'Anterior',
  SATURDAY: 'Sábado',
  SAVE: 'Salvar',
  SECOND: 'Segundo',
  SELECT_ALL: 'Selecionar tudo',
  SELECT_FILE: 'Selecione um arquivo',
  SELECT_VALUE: 'selecione um valor',
  SEPTEMBER: 'Setembro',
  SERVICES: 'Serviços',
  SHARE: 'Compartilhar',
  SIGN_OUT: 'Sair',
  SOUND: 'Som',
  START_DATE: 'Data inicial',
  SUBMIT: 'Enviar',
  SUNDAY: 'Domingo',
  THIS_FIELD_IS_REQUIRED: 'Esse campo é obrigatório',
  THIS_FIELD_REQUIRES_AT_LEAST_THREE_CHARACTERS: 'Esse campo requer ao menos 3 letras',
  TIMEZONE: 'Fuso horário',
  THURSDAY: 'Quinta',
  TUESDAY: 'Terça',
  UNDO: 'Desfazer',
  VALUE: 'Valor',
  VARIABLE: 'Variável',
  WEDNESDAY: 'Quarta',
  WEEK: 'Semana',
  YEAR: 'Ano',
  YES: 'Sim',
  CONFIGURATION: 'Configurar',
  DASHBOARDS_SHARE_DASHBOARD: 'Compartilhar',
  DUPLICATE_DASHBOARD: 'Duplicar',
  BUILD_TEMPLATE: 'Distribuir',
  DASHBOARDS_DELETE_DASHBOARD: 'Remover',
  DISMISS: 'Dispensar',
  NOT_A_DEVELOPER: 'Não é um desenvolvedor?',
  A_DEVELOPER: 'Você é um desenvolvedor? Clique aqui',
  NOTIFICATION: 'Notificação',
  SHARE_DASHBOARDS: 'Compartilhar painéis',
  WELCOME: 'Olá, como vai',
  REALTIME: 'Conexão',
  CONNECTED: 'Conectado',
  DISCONNECTED: 'Desconectado',
  WELCOME_DEVELOPER: 'Bem vindo Desenvolvedor',
  CHANGE_MY_SETTINGS: 'Alterar minhas configurações',
  EXPLORE: 'Explorar',
  CLICK_HERE: 'Clique aqui',
  IGNORED: 'Ignorado',
  MAP: 'Mapa',
  SATELLITE: 'Satélite',
  NEW_HERE: 'Novo por aqui?',
  ALREADY_HAVE_AN_ACCOUNT: 'Já tem uma conta?',
  PUBLIC_DASHBOARD: 'Painél Publico',
  UNLIMITED: 'Ilimitado',
  ADD_PROFILES: 'Adicionar Perfis',
  USER_MANAGEMENT: 'Gestão de usuários',
  ACCESS_MANAGEMENT: 'Gestão de acesso',

  CONFIRM_YOUR_E_MAIL_BEFORE_PROCEEDING: 'Confirme sua conta antes do primeiro acesso.',
  ACCOUNT_CREATION_HAS_BEEN_SUBMITTED: 'Conta criada e submetida para aprovação',
  YOUR_ACCOUNT_WAS_CREATED: 'Sua conta foi criada!',
  YOU_WILL_BE_NOTIFIED_WHEN_IT_IS_ACTIVATED: 'Você será notificado quando a conta estiver ativa.',

  NO_NOTIFICATIONS: 'Nenhuma notificação',
  NO_DASHBOARDS: 'Nenhum painel',
};
