module.exports = {
  TAGORUN_TITLE: 'TagoRUN',
  TAGORUN_DESCRIPTION: 'O TagoRUN funciona como um portal IoT customizado para clientes. É a melhor maneira para os usuários finais terem acesso a aplicações IoT utilizando domínios personalizados e recursos white label. Você pode personalizar cores, logos, e-mails e botões para engajar mais clientes com uma aplicação IoT com a sua própria marca.',
  TAGORUN_SUBTITLE: 'Publique a sua própria plataforma',
  TAGORUN_PAGE_TITLE: 'A melhor maneira para os seus usuários finais acessarem as suas aplicações IoT',
  TAGORUN_BUTTON: 'Iniciar',

  TAGORUN_SECTION1_TITLE: 'Aproveite ao máximo o TagoRUN',
  TAGORUN_SECTION1_SUBTITLE: 'Gratuito para usar. Acessível para expandir',
  TAGORUN_SECTION1_ITEM1_TITLE: 'Adicione sua marca gratuitamente em minutos',
  TAGORUN_SECTION1_ITEM1_DESCRIPTION: 'Customize seu TagoRUN adicionando sua marca dentro da plataforma, na página de signup, e no App Mobile sem nenhum custo. Apenas selecione as cores, textos, imagens e envie a sua logo.',
  TAGORUN_SECTION1_ITEM2_TITLE: 'Tenha o controle total dos seus usuários',
  TAGORUN_SECTION1_ITEM2_DESCRIPTION: 'Defina o tipo de acesso que cada usuário terá na sua plataforma. Rastreie como eles interagem com a sua solução.',
  TAGORUN_SECTION1_ITEM3_TITLE: 'Customize o seu domínio e seus e-mails',
  TAGORUN_SECTION1_ITEM3_DESCRIPTION: 'Seus clientes podem se increver no seu domínio em vez de tago.io. Nossa marca também pode ser removida',
  TAGORUN_SECTION1_ITEM4_TITLE: 'Acesse módulos de GPS e Wi-Fi',
  TAGORUN_SECTION1_ITEM4_DESCRIPTION: 'Rastreie a localização dos usuários finais a partir dos dispositivos móveis. Simples configuração nativa de dispositivos por Wi-Fi.',

  TAGORUN_SECTION2_TITLE: 'Recursos poderosos que vão além do whitelabel',
  TAGORUN_SECTION2_ROW1_TITLE: 'Obtenha insight dos usuários finais',
  TAGORUN_SECTION2_ROW1_DESCRIPTION1: 'Utilize os melhores serviços de análise que permitem você analisar detalhadamente sobre os seus usuários TagoRUN. Você pode integrar facilmente a sua aplicação TagoRUN com as ferramentas do Google Analytics ou com o Zoho SalesIQ.',
  TAGORUN_SECTION2_ROW1_DESCRIPTION2: ' Aprenda sobre o Google Analytics e TagoRUN',
  TAGORUN_SECTION2_ROW2_TITLE: 'Acesse recursos móveis',
  TAGORUN_SECTION2_ROW2_DESCRIPTION: 'Aproveite o GPS disponível no dispositivo móvel, que funciona como um dispositivo IoT gratuito, para criar soluções para seus clientes sem nenhum custo adicional. Utilize o nosso recurso de provisionamento nativo que facilita para os seus usuários finais registrar os dispositivos Wi-Fi na rede deles',
  TAGORUN_SECTION2_ROW3_TITLE: 'Assuma o controle total de sua aplicação',
  TAGORUN_SECTION2_ROW3_DESCRIPTION: 'Determine como os seus usuários acessarão sua aplicação IoT e o nível de acesso para cada um deles. Trabalhando com os nossos módulos de Gerenciamento de Usuários e Políticas de acessos, você pode criar políticas individuais, para grupos, ou até mesmo para organizações externas.',
  TAGORUN_SECTION2_ROW4_TITLE: 'Interaja mais com seus clientes',
  TAGORUN_SECTION2_ROW4_DESCRIPTION: 'Envie mensagens personalizadas para os seus usuários finais por meio do sistema de notificações e e-mails. Adicione chats, bots, chamadas, acesso remoto à tela e muito mais. Personalize o seu próprio modelo de e-mail para receber seus novos usuários, quando eles ativarem a conta ou até mesmo quando eles redefinirem a senha.',
  TAGORUN_SECTION2_ROW5_TITLE: 'Domínio personalizado & White label',
  TAGORUN_SECTION2_ROW5_DESCRIPTION: 'Seus clientes se inscreverão no portal utilizando a sua própria URL, ex. iot.minhaempresa.com, quando você adicionar o add-on de Domínio personalizado. A cor da sua empresa, logo, tema, fundo, e configurações dos botões, substituirão a marca TagoIO.',

  TAGORUN_FAQ_QUESTION1: 'Como eu posso começar a usar o TagoRUN?',
  TAGORUN_FAQ_ANSWER1_PART1: 'Primeiramente, construa sua aplicação dentro do admin TagoIO (admin.tago.io) conectando os seus dispositivos, criando dashboards, relatórios e tudo que você precisar para a sua aplicação. Após, configure a aparência e opções para o seu TagoRUN e as políticas de acesso para usuários finais. Assista nossos vídeos e tutoriais, ou entre em contato. Você pode encontrar mais informações na nossa ',
  TAGORUN_FAQ_ANSWER1_PART2: 'documentação',

  TAGORUN_FAQ_QUESTION2: 'Eu preciso publicar minha aplicação IoT utilizando TagoRUN?',
  TAGORUN_FAQ_ANSWER2: 'Não necessariamente. Você poderá usar o admin TagoIO para você e seu time. a TagoIO por si só funciona muito bem para uso pessoal, para um time pequeno ou para membros da mesma organização. Entretanto, nós recomendamos utilizar o TagoRUN para publicar suas soluções quando elas forem direcionadas a usuários finais, assim não apenas facilitando você a gerenciar os acessos, mas também facilitando o uso deles. E por fim, TagoRUN permite que seus usuários sempre tenham a sua marca em mente!',

  TAGORUN_FAQ_QUESTION3: 'Quanto custa o TagoRUN?',
  TAGORUN_FAQ_ANSWER3_PART1: 'TagoRUN é gratuito, com a maioria dos recursos disponíveis. Suas soluções irão funcionar dentro do nosso domínio, run.tago.io (ex. minhaempresa.run.tago.io). Se você quiser remover a nossa logo e qualquer referência à TagoIO, selecione o add-on "Custom Domain". A nossa marca será removida e a sua solução poderá funcionar no seu próprio domínio (ex. iot.minhaempresa.com), até mesmo seus e-mails serão enviados pelo seu DNS. Preços estão disponíveis ',
  TAGORUN_FAQ_ANSWER3_PART2: 'aqui',

  TAGORUN_FAQ_QUESTION4: 'Como TagoRUN funciona com o TagoIO admin? ',
  TAGORUN_FAQ_ANSWER4: 'TagoRUN é um dos enumeros módulos da plataforma TagoIO que funciona com os nossos recursos “Access Management” e “User Management”; permitindo que você entregue a melhor experiência possível para os seus usuários finais (clientes).',

  TAGORUN_FAQ_QUESTION5: 'Eu posso ter um App Mobile publicado no meu nome?',
  TAGORUN_FAQ_ANSWER5_PART1: 'Sim. Nosso App Mobile TagoRUN é gratuito e pronto para você avaliar suas soluções, sendo para você mesmo ou para os seus clientes. Se você quiser remover a marca TagoIO completamente, nós podemos customizar e publicar um App Mobile no seu nome. Os seus clientes irão encontrar o seu App com o nome da sua empresa, sem nenhuma mensão da TagoIO. ',
  TAGORUN_FAQ_ANSWER5_PART2: 'Entre em contato',
  TAGORUN_FAQ_ANSWER5_PART3: ' para mais informações.',
};
