module.exports = {
  NOTIFICATIONS_FROM_INSTALL: 'Application successfully installed',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'New user registered',
  NOTIFICATIONS_SEARCH: 'search notifications',
  NOTIFICATIONS_FROM_USER_REGISTERED: '$0 just created an account on Tago. The item you shared is available for him to accept.',
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: 'Oops... $0 is now registered on Tago, but something went wrong with the sharing. Try to share again.',
  ONLY_UNREAD: 'Only unread',
  OTHER_USERS: 'Other Users',
  RESEND_EMAIL_CONFIRMATION: 'Resend confirmation email',
  TAGO_SYSTEM: 'Tago System',
  YOU_REALLY_WANT_EXIT: 'Do you really want to exit',
  YOUR_EMAIL_HASNT_BEEN_CONFIRMED: 'Your email hasn’t been confirmed yet. Confirm your email to use all TagoIO features.',
  TEMPLATE_TAB_NAME: 'Distribute the template of this $0',
  TEMPLATE_TAB_DESCRIPTION: 'Send the generated URL to others so they can access your $0 through a customized install page.',
  TEMPLATE_TAB_LINK_DESCRIPTION: 'Create a link that contains the template of this $0. Share the link with anyone.',
  TEMPLATE_TAB_URL_PLACEHOLDER: 'build your template to generate an url',
  TEMPLATE_LAST_GENERATED_AT: 'Last generated at',
  CUSTOMIZE_TEMPLATE_TITLE: 'Customize the page',
  CUSTOMIZE_TEMPLATE_DESCRIPTION: 'Add a logo and an image that better represents your template.',
  CUSTOMIZE_TEMPLATE_DESCRIPTION2: 'Images will be shown when users access the page using the generated URL.',
  TEMPLATE_LABEL_TITLE: 'Title of the page',
  TEMPLATE_PLACEHOLDER_TITLE: 'The title of the page',
  TEMPLATE_LABEL_LOGO: 'Logo of the page',
  TEMPLATE_PLACEHOLDER_LOGO: 'https url of the logo',
  TEMPLATE_LABEL_MAIN_IMG: 'Main image of the page',
  TEMPLATE_PLACEHOLDER_MAIN_IMG: 'https url of the main image',
  TEMPLATE_ANALYSIS_SETUP_TITLE: 'If you use environment variables, describe each "variable value" here.',
  TEMPLATE_ANALYSIS_SETUP_DESCRIPTION: 'Whoever receives this analysis will use this information to configure the variable value',
  TEMPLATE_DASHBOARD_SETUP_TITLE: 'Enter a description for each device',
  TEMPLATE_DASHBOARD_SETUP_DESCRIPTION: 'This information will help the user to select the right device in his/her account. (e.g. GPS Calamp LMU3030, Generator GRX2000, …).',
  TEMPLATE_BUILD_TEMPLATE: 'Build Template',
  SETUP_LIST_DESCRIPTION_ANALYSIS: 'enter a description for this "variable value"',
  SETUP_LIST_DESCRIPTION_DASHBOARD: 'enter a detailed description for this device',
  COPIED: 'Copied',
  COPY: 'Copy',
  NOTIFICATION_PROFILE_SHARE: '$0 wants to share a profile with you',
  NOTIFICATION_BUCKET_SHARE: '$0 wants to share the bucket $1 with you',
  NOTIFICATION_DASHBOARD_SHARE: '$0 wants to share the dashboard $1 with you',
  NEW_USER_RESENT_CONFIRMATION_EMAIL: 'We\'ve sent an email to <b>$0</b>. Please, confirm your email to get access to all features!',
  DASHBOARD_ACCEPTED_NOTIFICATION: 'The dashboard was added to the <b>left sidebar</b>.',
  PROFILE_ACCEPTED_NOTIFICATION: 'The profile was accepted!<br /><b>Please logout</b> to get access to $0\'s account.',
  BUCKET_ACCEPTED_NOTIFICATION: 'The bucket was accepted and added to the <b>bucket list</b>.',
  GO_TO_DASHBOARD: 'Go to dashboard',
  HOME_END_USER_INTRO: 'TagoIO is the best tools for users to interact with devices connected to their applications. Just select a dashboard and follow the directions to operate the application.',
  NOT_A_DEV_DESCRIPTION: 'If you are not a developer, use our Simple View. It is easier to use!',
  CHANGE_TO_SIMPLE_USER_VIEW: 'Change to Simple View',
  CHANGE_TO_DEVELOPER_VIEW: 'Change to developer',
  A_DEV_DESCRIPTION: 'I’m a developer, and will build applications in the platform.',
};
