module.exports = {
  ABOUT_THIS_SHARING: 'Sobre este intercambio',
  ALLOW_SHARE_WITH_OTHERS: 'Permitir compartir con otros',
  CANCEL_SHARING: 'Cancelar compartir',
  CREATE_MORE_DASHBOARDS: 'crear más tableros',
  DASHBOARD_ID: 'ID del tablero',
  DASHBOARD_NAME: 'Nombre del tablero',
  DASHBOARD_SHARED_BY: 'Tablero compartido por',
  DELETE_DASHBOARD: 'Eliminar panel',
  ENTER_NAME_DASHBOARD: 'ingrese el nombre del tablero',
  INVITED_BY: 'Invitado por $0$',
  INVITE_USER: 'Invitar usuario',
  LAST_ACCESS: 'Ultimo acceso',
  MAKE_DASHBOARD_VISIBLE: 'Hacer este panel visible',
  MORE_ABOUT_DASHBOARD: 'Más sobre este tablero',
  ONCE_YOU_DELETE_DASHBOARD: 'Una vez que eliminas un tablero, no hay vuelta atrás. Por favor, estar seguro',
  REGISTERED_AT: 'Registrado en',
  REMOVE_INVITE: 'Eliminar invitación',
  SHARE_EXPIRES_AT: 'Compartir expira en',
  SHARE_IT_DURING: 'Compártelo durante',
  SHARE_PRIVATE: 'Compartir privado',
  SHARED_WITH: 'Compartido con',
  THIS_DASHBOARD_HAS_BEEN_SHARED: 'Este panel se ha compartido contigo (no puedes editarlo) Este panel se ha compartido contigo (no puedes editarlo)',
  USER_DOESNT_HAVE_AN_ACCOUNT_YET: 'El usuario aún no tiene una cuenta',
  WHEN_HIDDEN_THE_DASHBOARD_WILL_NOT_LISTED: 'Cuando está oculto, el tablero no aparecerá en la barra de menú de la izquierda',
  WHEN_YOU_SHARE_DASHBOARD_OTHERS: 'Cuando compartes este panel, otros no podrán editarlo.',
  YOU_ARE_CURRENTLY_SHARING_DASHBOARD: 'Actualmente está compartiendo este panel con otros usuarios. Si continúa, también se eliminará de su vista',
  YOU_CANNOT_MANUALLY_REMOVE_DASHBOARDS: 'No puede eliminar paneles de aplicaciones manualmente desde Aplicaciones',
  YOU_NOT_SHARING_THIS_DASHBOARD_PRIVATELY: 'No estás compartiendo este panel de forma privada',
  YOU_DONT_HAVE_PERMISSION_ACCESS_PAGE: 'No tienes permiso para acceder a esta página',
  YOU_SHARED_DASHBOARD_WITH_EXPIRATION_DATE_GREATER: 'Compartió un panel con una fecha de vencimiento que es mayor que la fecha de vencimiento de la acción que se hizo para usted. La parte por $0$ vencerá en: $1$.',
  YOU_REALLY_WANT_DELETE_DASHBOARD: '¿De verdad quieres eliminar este tablero?',
  YOU_REALLY_WANT_DELETE_SHARE: '¿De verdad quieres eliminar esta intercambio?',
  YOU_REALLY_WANT_CANCEL_SHARING: '¿De verdad quieres cancelar el intercambio?',
  YOUR_PLAN_ALLOWS_YOU_CREATE_UP: 'Su plan le permite crear hasta 5 paneles',
  LIST_OF_USERS_INVITED: 'Lista de usuários convidados',
  YOU_ARE_NOT_ALLOWED_TO_SHARE_THIS_DASHBOARD: 'No se permite compartir este panel',
  ONCE_YOU_REMOVE_FROM_YOUR_LIST: 'Después de quitar panel $0 de tu lista, ya no podrás verlo',
  YOU_REALLY_WANT_REMOVE_FROM_YOUR_LIST: '¿Realmente quieres eliminar este panel de tu lista',
  DUPLICATE_DASHBOARD_WITH_NAME: 'Duplicar "$0"',
  DUPLICATE_DASHBOARD_MESSAGE_WITH_NAME: 'Estás duplicando "$0" en tu cuenta. Siéntase libre de establecer un nuevo nombre para este panel',
  ONCE_YOU_DUPLICATE_THIS_DASHBOARD: 'Una vez que duplique este panel, se creará una copia en su cuenta sin ningún dato.',
  KEEP_THE_SAME_DEVICES: 'Mantener los mismos dispositivos',
  THE_DASHBOARD_WAS_DELETED: 'El tablero de control $0 fue eliminado.',
  THE_DASHBOARD_WAS_REMOVED: 'El tablero de mandos $0 fue eliminado.',
};
