module.exports = {
  TAGO_HOME: 'Tago - Início',
  BANNER_TITLE: 'Crie mais valor conectando seu produto com a Tago',
  BANNER_DESCRIPTION: 'Extraia mais informações e otimize o seu processo.',
  GET_STARTED_HOME: 'Comece agora',
  WATCH_IT_IN_ACTION: 'Entenda como funciona',
  WATCH_IT_IN_ACTION_YOUTUBEVIDEO: 'Nf6IO7Yqhgw',
  TAGO_DIVULGE_EVENTS_REGISTER: 'Registre-se já!',
  TAGO_PLATFORM: 'Plataforma Tago',
  TAGO_PLATFORM_DESCRIPTION: 'A Tago oferece as ferramentas para o seu negócio, gerenciando seus dispositivos, armazenando dados, executando análises de dados e integrando diversos serviços em tempo real. Ele combina tudo com um aplicativo e um sistema de gerenciamento de usuários extremamente ágil, sendo simples e fácil de usar.',
  TAGO_BRINGS_ALL_FEATURES: 'A Tago possui todos os recursos para construir sua solução',
  BUILD_YOUR_APPLICATION_IN_ON_TIME: 'Construa Aplicações',
  BUILD_YOUR_APPLICATION_IN_ON_TIME_DESCRIPTION: 'Use nossos templates para iniciar rapidamente, colaborar com outros, e criar sua aplicação rapidamente!',
  SHARE_YOUR_SOLUTIONS_EASILY: 'Compartilhe facilmente',
  SHARE_YOUR_SOLUTIONS_EASILY_DESCRIPTION: 'Compartilhe aplicações com qualquer um de forma privada ou usando links públicos',
  SCALE_UP_SMOOTHLY: 'Escale sua aplicação de forma rápida',
  SCALE_UP_SMOOTHLY_DESCRIPTION: 'Gerencie novos usuários e dispositivos individualmente ou em remessas. Use nossos scripts para automatizar o processo',
  CONNECT_ANY_DEVICE: 'Conecte qualquer dispositivo',
  CONNECT_ANY_DEVICE_DESCRIPTION: 'Conecte seus próprios dispositivos com WiFi, LoRa, Sigfox, GPRS, LTE, BLE, Zigbee, e outros',
  LEARN_ABOUT_OUR_PRODUCT: 'Conheça detalhes do nosso produto',
  OUR_CUSTOMERS: 'Companhias que já utilizam a TagoIO',
  OUR_CUSTOMERS_SAY_IT_BEST: 'Depoimentos de nossos clientes',
  JULIO_ALMEIDA: 'Julio Almeida',
  JULIO_ALMEIDA_COMPANY: 'SW Dev - Agrusdata',
  JULIO_ALMEIDA_DESCRIPTION: 'Depois de compararmos várias plataformas de IoT, optamos pela Tago devido aos seus fortes recursos de gerenciamento de dispositivos e dados, e a solução intuitiva e fácil de usar para criação de painéis. Ao executar nossas análises no Tago, conseguimos fornecer uma solução robusta.',
  ERIC_HOOG: 'Eric Hoog',
  ERIC_HOOG_COMPANY: 'CEO - Zquel',
  ERIC_HOOG_DESCRIPTION: 'TagoIO ajudou tremendamente no desenvolvimento de nossos produtos. Sua versatilidade e facilidade de uso nos ajudaram a atingir as metas de nossos produtos com muito mais rapidez do que outras alternativas.',
  BRENT_WARD: 'Brent Ward',
  BRENT_WARD_COMPANY: 'VP, Device Solutions Inc',
  BRENT_WARD_DESCRIPTION: 'A Tago tem sido fundamental no fornecimento de elementos críticos para nossa plataforma de Monitoramento/Controle Remoto Cellio IoT. A capacidade de costumizar a hospedagem de dados, painéis, aplicativos móveis, alertas e notificações permitiu o desenvolvimento de uma solução completa e pronta para uso, o que provou ser extremamente flexível, desejável e valiosa para nossos clientes corporativos.',

  INDUSTRIAL_AUTOMATION: 'Automação Industrial',
  SMART_IRRIGATION: 'Irrigação Inteligente',
  WAREHOUSE_INDOOR_LOCATION: 'Localização interna de Depósito',
  COMPOSE: 'Composição',
  REFRIGERATED: 'Refrigeração',
  TELEMATICS: 'Telemática',

  MAIN_TITLE_HOME_PAGE: 'Crie Rapidamente Suas Próprias Soluções IoT',
  SUB_TITLE_HOME_PAGE: 'Painéis, Analíticas, Armazenamento, Notificações, Dispositivos e Gerenciamento de usuários inclusos',
  WHAT_IS_TAGO_IO: 'O que é a TagoIO?',
  CHECK_TAGO_FEATURES: 'Dê uma olhada nas funções!',
  CHECK_PRODUCT_FEATURES: 'Veja detalhes do produto',
  VIEW_DASHBOARD: 'Ver Painel',
  HOW_DOES_IT_WORK: 'Como funciona?',
  GET_DASHBOARD: 'Adquirir Painel',
  WHAT_CAN_I_DO_TITLE: 'O que posso fazer com a TagoIO?',
  WHAT_CAN_I_DO_DESCRIPTION: 'Alguns exemplos de como a TagoIO cria valor ' +
      'para aplicações diferentes, adicione-os na sua conta para vê-los em ação.',
  ENTER_EMAIL_GAIN_ACCESS: 'Por favor insira seu e-mail para adquirir acesso ao painel $0',
  GOT_IT: 'Entendi',
  WE_ARE_WAITING_FOR_YOU: 'Estamos esperando por você!',
  WE_SENT_YOU_EMAIL: 'We\'ve sent you an e-mail with the chosen dashboard, all you have to do is accept it!',
};
