module.exports = {
  PRICING: 'Planos',
  PRICING_DESCRIPTION1: 'TagoIO pricing is flexible and based on the Plan and Services provisioned for your application',
  PRICING_DESCRIPTION2: 'Choose the plan most suitable for the stage and size of your project',
  FREE: 'Free',
  FREE_VALUE: '0',
  STARTER: 'Starter',
  STARTER_VALUE: '49',
  SCALE: 'Scale',
  SCALE_VALUE: '199',
  ENTERPRISE: 'Enterprise',
  ENTERPRISE_VALUE: '399',
  GET_STARTED_PLAN: 'Get Started',
  OUR_PLANS: 'Our Plans',
  OUR_PLANS_DESCRIPTION: 'Select the plan based on the set of tools that you need for your application. Upgrade at any time as your application grows',
  PLAN_FEATURES: 'FEATURES',
  DEVICE_MANAGEMENT: 'Device Management',
  DEVICE_MANAGEMENT_SPAN_FREE: 'connect up to 5 devices',
  DASHBOARD_CREATION: 'Dashboard creation',
  DASHBOARD_CREATION_SPAN_FREE: 'build up to 5 dashboards',
  NATIVE_SHARE_CAPABILITY: 'Native Share Capability',
  RUN_ANALYSIS: 'Run your analysis in real-time',
  RUN_ANALYSIS_SPAN_FREE: 'run up to 250 scripts /h',
  API_REQUESTS: 'Data Input Transactions per hour',
  API_REQUESTS_SPAN_FREE: 'up to 5,000/h  or  500/min ',
  API_REQUESTS_SPAN_STARTER: 'customized',
  API_REQUESTS_SPAN_SCALE_ENTERPRISE: 'customized',
  CONFIGURABLE_MAX_REQUEST: 'Configurable max request per device',
  DATA_RETENTION_CONTROL: 'Data Retention Control',
  DATA_RETENTION_CONTROL_SPAN_FREE: 'data stored for 1 mo',
  AUTOMATIC_DATA_BACKUP: 'Automatic Data Backup',
  TAGS_MANAGEMENT: 'Tags Management',
  USER_PROFILE_MANAGEMENT: 'User Profile Management (Developers)',
  USER_PROFILE_MANAGEMENT_STARTER: 'Add 1 more user',
  USER_PROFILE_MANAGEMENT_SCALE: 'Add up to 10 users',
  USER_PROFILE_MANAGEMENT_ENTERPRISE: 'unlimited users',
  COMPLETE_AUDIT_LOG: 'Complete Audit Log',
  COMPLETE_AUDIT_LOG_STARTER: 'limited to account logs',
  EMBED_WIDGET_CREATION: 'Embed Widget Creation',
  SLA: 'SLA',
  PREMIUM_WIDGETS: 'Premium Widgets',
  PRIVATE_SLACK_CHANNEL: 'Private Slack Channel',
  CUSTOMIZED_MIDDLEWARE_FOR_ANY_DEVICE: 'Customized Middleware for any device',
  REALESE_SOLUTION_EXPLORE: 'Release solution to Explore',
  WHITELABEL_VERSION: 'WhiteLabel Version',
  SERVICE_USAGE: 'Services Usage',
  SERVICE_USAGE_DESCRIPTION: "You pay only for the services that you provision for the month. We don't charge by devices, dashboards or users that access your dashboards. Estimate your monthly cost using the setting bars based on your expected usage.",
  SERVICE: 'Service',
  COST: 'Cost (USD)',
  UNIT: 'Unit',
  ANALYSIS_RUNNING_SRIPTS: 'Analysis (running scripts)',
  ANALYSIS_RUNNING_SRIPTS_SPAN: 'Run scripts to process data sent by devices or other services connected to Tago. Each run should be executed before the Timeout expires (normally set at 30 sec).',
  ANALYSIS_RUNNING_SRIPTS_COST: '$0.100',
  ANALYSIS_RUNNING_SRIPTS_UNIT: '1,000 runs',
  USAGE_API_REQUESTS: 'API Request',
  USAGE_API_REQUESTS_SPAN: 'Any access done through API to POST/GET/DELETE data',
  USAGE_API_REQUESTS_COST: '$0.025',
  USAGE_API_REQUESTS_UNIT: '1,000 requests',
  STORAGE_ONLINE_DATA: 'Storage - Online Data',
  STORAGE_ONLINE_DATA_SPAN: 'Online data is always available in buckets for visualization and data processing.',
  STORAGE_ONLINE_DATA_COST: '$0.015',
  STORAGE_ONLINE_DATA_UNIT: '1,000 registers',
  STORAGE_ONLINE_BACKUP: 'Storage - Offline Backup',
  STORAGE_ONLINE_BACKUP_SPAN: 'Backed up data is kept offline at lower cost.',
  STORAGE_ONLINE_BACKUP_COST: '$0.005',
  STORAGE_ONLINE_BACKUP_UNIT: '1,000 registers',
  USAGE_SMS: 'SMS',
  USAGE_SMS_SPAN: 'Price to send messages in US, Canada (contact us for other countries).',
  USAGE_SMS_COST: '$0.025',
  USAGE_SMS_UNIT: '1 unit',
  USAGE_EMAIL: 'Email',
  USAGE_EMAIL_COST: '$0.025',
  USAGE_EMAIL_UNIT: '1,000 units',
  CONTACT_SALES_TEAM_TALK: 'Contact our sales team to talk about our tier pricing or high volume of transactions.',
  PRICING_TALK_TO_SALES: 'Talk to Sales',
  PRICING_EXAMPLES: 'Pricing Examples',
  PRICING_EXAMPLE_1: 'Pricing Example 1',
  PRICING_EXAMPLE_1_DESCRIPTION: 'If you selected the Start plan, added 1,000 devices that sends a package of 4 variables at every 1 hour to store the data (real-time and action verification to be done separately), your charges would be estimated as follows:',
  PRICING_EXAMPLE_1_MONTHLY_PLAN: 'Monthly Plan:',
  PRICING_EXAMPLE_1_MONTHLY_PLAN_VALUE: 'Starter $49',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE: 'Monthly Services:',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE1: 'Number of Data Input Transactions = 4 * 1,000 = 4,000/h',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE2: 'Recommended provision = 5,000/h',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE3: 'Monthly cost for Data Input Transaction = $0',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE4: 'Number of register (month) = 4 * 1,000 * 24 * 30 = 2,880,000',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE5: 'Recommended provision = 3 Million registers',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE6: 'Monthly cost for the Data storage = $ 40',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE7: 'The monthly cost for Services usage = $0 + $40 = $40',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES: 'Total monthly charges:',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES_VALUE1: 'Estimated monthly charges = Plan + Services charges = $49 + $40 = $89',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES_VALUE2: 'or about $0.09 / device / mo',
  PRICING_EXAMPLE_2: 'Pricing Example 2',
  PRICING_EXAMPLE_2_DESCRIPTION1: 'If you selected the Starter Plan, added 1,000 devices that sends a package of 4 variables at every 1 hour each.',
  PRICING_EXAMPLE_2_DESCRIPTION2: 'In addition, you setup the Analysis to execute a script each time a data package arrives. In this case, devices should enable the \'Action\' verification that will trigger the Analysis (adding one transaction per register that arrives).  Your charges would be estimated as follows:',
  PRICING_EXAMPLE_2_MONTHLY_PLAN: 'Monthly Plan:',
  PRICING_EXAMPLE_2_MONTHLY_PLAN_VALUE: 'Scale $49',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE: 'Monthly Services:',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE1: 'Number of Data Input Transactions = 4 * 1,000 * 2 = 8,000/h  (1 additional transaction per register to verify Actions)',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE2: 'Recommended provision = 10,000/h',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE3: 'Monthly cost for Data Input Transaction = $20',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE4: 'Number of register (month) = 4 * 1,000 * 24 * 30 = 2,880,000',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE5: 'Recommended provision = 3 Million registers',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE6: 'Monthly cost for the Data storage = $ 40',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE7: 'Number of Analysis runs = 1,000/h',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE8: 'Monthly cost for Analysis runs = $ 55',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE9: 'The monthly cost for Services = $20 + $40 + $55 = $115',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE10: '---',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES: 'Total monthly charges:',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES_VALUE1: 'Estimated monthly charges = Plan + Services charges = $49 + $115 = $165',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES_VALUE2: 'or about $0.16 /device /mo',
  FREQUENTLY_ASKED_QUESTIONS: 'Frequently Asked Questions',
  PRICING_QUESTION1: 'For what will I be charged for?',
  PRICING_RESPONSE1: "Different from other providers, Tago doesn't charge by the number of devices, dashboards, or even for end users. Our model is based on Plan and Services provisioned in your account. The amount will be committed until the last day of the month and the billing renewed automatically in the following month. You can also include some add-ons, such as support plans.",
  PRICING_QUESTION2: "What is Tago's billing cycle?",
  PRICING_RESPONSE2: 'Tago closes the billing period at midnight on the last day of each month. Invoices are generally available with the first four days of the month.',
  PRICING_QUESTION3: 'If I upgrade my plan, how will that be billed?',
  PRICING_RESPONSE3: 'We make a one-time prorated charge at the time of the upgrade for the equivalent reminder of the billing cycle. For example, if you upgrade from the Free plan to the Starter plan when there is 10 remaining days in the month, we will charge 1/3 of the Starter monthly pricing immediately when you confirm the upgrade. In the next month, we will charge the full price of the Starter plan and the provisioned services.',
  PRICING_QUESTION4: 'What are the payment methods accepted?',
  PRICING_RESPONSE4: 'Tago accepts most major credit cards for payment. In specific cases we may be able to invoice customers directly, talk to our sales team for questions.',
  PRICING_QUESTION5: 'Do you save credit card details?',
  PRICING_RESPONSE5: 'No. Your credit card details are not saved on our servers. In fact, all information goes directly from your computer to our payment service provider (Stripe).',
  PRICING_QUESTION6: 'If I downgrade my plan, when will the changes be put into effect?',
  PRICING_RESPONSE6: 'We will downgrade you to the new selected plan at your next renewal date. Your current subscription will remain active at its current level through the end of the billing period that you’ve already paid for.',
  PRICING_QUESTION7: 'If I downgrade to a free plan, what will happen with the data stored in my buckets?',
  PRICING_RESPONSE7: 'First, your subscription will remain active at its current level through the end of the billing period that you’ve already paid for. Then, while in the free plan, our system will force the 30-days data retention policy - i.e. all data with timestamp older than that will be removed. So, we highly recommend that you plan this operation carefully to prevent undesired data lost.',
  PRICING_QUESTION8: 'How is the Analysis Timeout defined?',
  PRICING_RESPONSE8: 'When the Analysis runs your script, the execution time should be less than the Timeout defined for your plan. You can monitor the status using the Console feature.',

  PRICING_ADDITIONAL_COAST: 'Additional Cost',
  PRICING_ALL_FEATURES: 'All features',
  PRICING_COLLAPSE_ALL: 'Collapse All',
  PRICING_EXPAND_ALL: 'Expand All',
  PRICING_NOT_INCLUDED: 'Not Included',
  PRICING_SOME_FEATURES: 'Some features',

  PRICING_MANAGE_DEVICES: 'Manage Devices',
  PRICING_CONNECT_UNLIMITED_NUMBER_DEVICES: 'Connect unlimited number of devices',
  PRICING_UP_TO: 'up to',
  PRICING_TAGS_FOR_MANAGEMENT: 'Tags for management',
  PRICING_NUMBER_API_REQUESTS_PER_HOUR: 'Maximum Data Input Transactions per hour',

  PRICING_HELP_1: "We don't charge based on the number of devices connected. Each device receives a unique token.",
  PRICING_HELP_2: 'Organize all your devices by groups using Tags.',
  PRICING_HELP_3: 'Each register inside a data package posted to TagoIO is counted as one transaction',

  PRICING_CREATE_DASHBOARDS: 'Create Dashboards',
  PRICING_BUILD_UNLIMITED_NUMBER_DASHBOARDS: 'Build unlimited number of dashboards',
  PRICING_PREMIUM_WIDGETS: 'Premium widgets',
  PRICING_EMBEDDED_WIDGETS: 'Embedded widgets',

  PRICING_HELP_4: 'Use our powerful and easy to use tools to build great ways to visualize data.',
  PRICING_HELP_5: 'Use advanced widgets that make easier for users to interact with your application.',
  PRICING_HELP_6: "Embed widget on your own website. Scale Plan allows you to remove 'Runs on Tago' water mark.",

  PRICING_GO_MOBILE: 'Go Mobile',
  PRICING_MOBILE_APP_ANDROIND_IOS: 'Mobile app - Android & iOS',

  PRICING_HELP_7: 'TagoIO mobile App is available for free to all users.',

  PRICING_RUN_ANALYSIS_REAL_TIME: 'Run Analysis in real-time',
  PRICING_RUN_SCRIPTS_ANALYZE_DATA: 'Run scripts to analyze data',
  PRICING_RUN_MACHINE_LEARNING_REAL_TIME: 'Run machine learning in real-time',

  PRICING_HELP_8: "Build and run scripts on TagoIO to process data in real-time.",
  PRICING_HELP_9: 'Talk to our technical support about how to use Machine Learning in your application.',

  PRICING_SHARE_YOUR_APPLICATION_AND_DATA: 'Share your application and data',
  PRICING_NATIVE_SHARING_FOR_DASHBOARDS: 'Native sharing for dashboards',
  PRICING_NATIVE_SHARING_FOR_DATA_BUCKETS: 'Native sharing for data buckets',

  PRICING_HELP_10: 'One-click sharing: share dashboards with anyone, publically or privately.',
  PRICING_HELP_11: 'One-click sharing: share your data with anyone securely.',

  PRICING_AUTOMATE_EXPAND_SOLUTIONS_WITH_INTEGRATION: 'Automate and expand solutions with integration',
  PRICING_CONNECT_ANY_APP: 'Connect to any App',
  PRICING_CONNECT_SIGFOX_LORAWAN: 'Connect to Sigfox, LoRa,...',
  PRICING_NATIVE_INTEGRATION_MICROSOFT_FLOW: 'Native integration with Microsoft Flow',
  PRICING_NATIVE_INTEGRATION_CRM: 'Native integration with CRM',
  PRICING_INTEGRATED_CUSTOMIZED_MIDDLEWARE: 'Protocol translator',

  PRICING_HELP_12: 'Connect to external systems using our RESTfull API',
  PRICING_HELP_13: 'Connect devices using connectors for Sigfox, LoRa and other network providers',
  PRICING_HELP_14: 'Integrate with GoogleSheets, Excel, Zendesk, Twitter, and hundreds of services through Microsoft Flow',
  PRICING_HELP_15: 'Indentify sales opportunities by integrating your CRM with TagoIO',
  PRICING_HELP_16: 'TagoIO connects to any protocol. Convert from UDP, TCP/IP, or connect to any database formats.',

  PRICING_SCALE_CONFIDENCE: 'Scale with confidence',
  PRICING_MONITORING_EVERY_TRANSACTION_AUDIT_LOG: 'Monitore all transactions with Audit Log',
  PRICING_SRIPTS_THAT_GRANT_DIFFERENT_LEVELS_ACCESS: 'Grant different levels of access for users',
  PRICING_ADD_USERS_MANAGE_ACCOUNT: 'Manage more users in your account',

  PRICING_HELP_17: 'Audit Log tracks all operations executed and who accessed your account. Starter Plan offers some capabilities.',
  PRICING_HELP_18: 'Users access your application based on the level you grant to them.',
  PRICING_HELP_19: "We don't charge for final users, you can share your application at no cost. Add users to manage your account. One additional user for the Starter plan, and 10 for Scale.",

  PRICING_BACK_UP_YOUR_DATA: 'Back up your data',
  PRICING_DOWNLOAD_YOUR_DATA: 'Easy data downloading',
  PRICING_DATA_RETENTION_POLICY: 'Data retention policy',
  PRICING_LIMITED_30_DAYS: 'limited to 30 days',
  PRICING_OFF_LINE_DATA_BACKUP_REDUCES_STORAGE_COST: 'Off-line data backup reduces storage cost',

  PRICING_HELP_20: 'Download your data in .csv, JSON, or XML formats.',
  PRICING_HELP_21: 'Define how long your online data should be kept in the data buckets.',
  PRICING_HELP_22: 'Configure data buckets to back-up as needed.',

  BRAND_ENGAGEMENT: 'Brand engagement',
  ADD_YOUR_LOGO_YOUR_APPLICATION: 'Add your logo in your application',
  WHITE_LABEL_VERSION: 'White label version',

  PRICING_HELP_23: 'Add logo using our image and video widgets in seconds',
  PRICING_HELP_24: 'Add your own logo, colors, and url to engage customers with your brand.',

  PRICING_SERVICES_MAXIMUM_INPUT_PER_HOUR: 'Maximum input per hour',
  PRICING_SERVICES_MAXIMUM_OUTPUT_PER_HOUR: 'Maximum output per hour',
  PRICING_SERVICES_TOTAL_NUMBER_OF_REGISTERS: 'Quantity of registers available',
  PRICING_SERVICES_MAXIMUM_RUN_PER_HOUR: 'Maximum runs per hour',
  PRICING_SERVICES_MAXIMUM_PER_MONTH: 'Maximum per month',

  PRICING_SERVICES_DATA_INPUT_TRANSACTIONS: 'Data Input Transactions',
  PRICING_SERVICES_DATA_OUTPUT_TRANSACTIONS: 'Data Output Transactions',
  PRICING_SERVICES_ANALYSIS_RUNS: 'Analysis Runs',
  PRICING_SERVICES_DATA_REGISTERS_STORED: 'Registers Storage',
  PRICING_SERVICES_SMS_SENT: 'SMS',
  PRICING_SERVICES_E_MAIL_SENT: 'E-Mail',
  PRICING_SERVICES_USAGE_ALLOC: 'Flexible and Affordable Prices​',
};
