module.exports = {
  PRICING: 'Planos',
  PRICING_DESCRIPTION1: 'Tago pricing is based on the plan you select and the usage of services perfomed during a one-month period',
  PRICING_DESCRIPTION2: 'We offer all the tools that you will need to build and manage the best application in your industry. Each of our plan is composed by a set of features suitable for different stages and sizes of your project',
  FREE: 'Free',
  FREE_VALUE: '0',
  STARTER: 'Starter',
  STARTER_VALUE: '49',
  SCALE: 'Scale',
  SCALE_VALUE: '199',
  ENTERPRISE: 'Enterprise',
  ENTERPRISE_VALUE: '399',
  GET_STARTED_PLAN: 'Get Started',
  OUR_PLANS: 'Our Plans',
  OUR_PLANS_DESCRIPTION: 'Select the plan based on the set of tools that you need for your application. Upgrade at any time as your application grows',
  PLAN_FEATURES: 'FEATURES',
  DEVICE_MANAGEMENT: 'Device Management',
  DEVICE_MANAGEMENT_SPAN_FREE: 'connect up to 5 devices',
  DASHBOARD_CREATION: 'Dashboard creation',
  DASHBOARD_CREATION_SPAN_FREE: 'build up to 5 dashboards',
  NATIVE_SHARE_CAPABILITY: 'Native Share Capability',
  RUN_ANALYSIS: 'Run your analysis in real-time',
  RUN_ANALYSIS_SPAN_FREE: 'run up to 250 scripts / hour',
  API_REQUESTS: 'API Requests per hour',
  API_REQUESTS_SPAN_FREE: 'up to 250 / hour',
  API_REQUESTS_SPAN_STARTER: 'up 10,000 / hour',
  API_REQUESTS_SPAN_SCALE_ENTERPRISE: '10,000 + / hour',
  CONFIGURABLE_MAX_REQUEST: 'Configurable max request per device',
  DATA_RETENTION_CONTROL: 'Data Retention Control',
  DATA_RETENTION_CONTROL_SPAN_FREE: 'data stored for 1 mo',
  AUTOMATIC_DATA_BACKUP: 'Automatic Data Backup',
  TAGS_MANAGEMENT: 'Tags Management',
  USER_PROFILE_MANAGEMENT: 'User Profile Management',
  USER_PROFILE_MANAGEMENT_STARTER: 'Add 1 more user',
  USER_PROFILE_MANAGEMENT_SCALE: 'Add up to 5 users',
  USER_PROFILE_MANAGEMENT_ENTERPRISE: 'unlimited users',
  COMPLETE_AUDIT_LOG: 'Complete Audit Log',
  COMPLETE_AUDIT_LOG_STARTER: 'limited to account logs',
  EMBED_WIDGET_CREATION: 'Embed Widget Creation',
  SLA: 'SLA',
  PREMIUM_WIDGETS: 'Premium Widgets',
  PRIVATE_SLACK_CHANNEL: 'Private Slack Channel',
  CUSTOMIZED_MIDDLEWARE_FOR_ANY_DEVICE: 'Customized Middleware for any device',
  REALESE_SOLUTION_EXPLORE: 'Release solution to Explore',
  WHITELABEL_VERSION: 'WhiteLabel Version',
  SERVICE_USAGE: 'Services Usage',
  SERVICE_USAGE_DESCRIPTION: "Pay only for the services that you use. We don't charge by the number of devices, dashboards or users that access your dashboards. Monthly bill is based on the number of transactions and data stored during the period.",
  SERVICE: 'Service',
  COST: 'Cost (USD)',
  UNIT: 'Unit',
  ANALYSIS_RUNNING_SRIPTS: 'Analysis (running scripts)',
  ANALYSIS_RUNNING_SRIPTS_SPAN: 'Run scripts to process data sent by devices or other services connected to Tago. Each run should be executed before the Timeout expires (normally set at 30 sec).',
  ANALYSIS_RUNNING_SRIPTS_COST: '$0.100',
  ANALYSIS_RUNNING_SRIPTS_UNIT: '1,000 runs',
  USAGE_API_REQUESTS: 'API Request',
  USAGE_API_REQUESTS_SPAN: 'Any access done through API to POST/GET/DELETE data',
  USAGE_API_REQUESTS_COST: '$0.025',
  USAGE_API_REQUESTS_UNIT: '1,000 requests',
  STORAGE_ONLINE_DATA: 'Storage - Online Data',
  STORAGE_ONLINE_DATA_SPAN: 'Online data is always available in buckets for visualization and data processing.',
  STORAGE_ONLINE_DATA_COST: '$0.015',
  STORAGE_ONLINE_DATA_UNIT: '1,000 registers',
  STORAGE_ONLINE_BACKUP: 'Storage - Offline Backup',
  STORAGE_ONLINE_BACKUP_SPAN: 'Backed up data is kept offline at lower cost.',
  STORAGE_ONLINE_BACKUP_COST: '$0.005',
  STORAGE_ONLINE_BACKUP_UNIT: '1,000 registers',
  USAGE_SMS: 'SMS',
  USAGE_SMS_SPAN: 'Price to send messages in US, Canada (contact us for other countries).',
  USAGE_SMS_COST: '$0.025',
  USAGE_SMS_UNIT: '1 unit',
  USAGE_EMAIL: 'Email',
  USAGE_EMAIL_COST: '$0.025',
  USAGE_EMAIL_UNIT: '1,000 units',
  CONTACT_SALES_TEAM_TALK: 'Contact our sales team to talk about our tier pricing or high volume of transactions.',
  PRICING_TALK_TO_SALES: 'Talk to Sales',
  PRICING_EXAMPLES: 'Pricing Examples',
  PRICING_EXAMPLE_1: 'Pricing Example 1',
  PRICING_EXAMPLE_1_DESCRIPTION: 'If you selected the Start plan, added 1,000 devices that sent (POST) a package of 6 variables at every 1 hour each, your charges would be calculated as follows:',
  PRICING_EXAMPLE_1_MONTHLY_PLAN: 'Monthly Plan:',
  PRICING_EXAMPLE_1_MONTHLY_PLAN_VALUE: 'Starter $49',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE: 'Monthly Services Usage:',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE1: 'The monthly API Requests prices is $0.025 per 1,000/requests.',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE2: 'The number of requests (month) = 1,000 * 24 * 30 = 720,000',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE3: 'The monthly cost for API Requests = 720,000 * 0.025/1000 = $18.00',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE4: 'The monthly Data Storage price is $0.015 per 1,000/register',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE5: 'The number of register (month) = 6 * 1,000 * 24 * 30 = 4,320,000',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE6: 'The monthly cost for the Online Data storage = 4,320,000 * $0.015 = $64.80',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_USAGE_VALUE7: 'The monthly cost for Services usage = $18.00 + $64.80 = $82.80',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES: 'Total monthly charges:',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES_VALUE1: 'Total monthly charges = Plan charges + Usage charges = $49 + $82.80 = $131.80',
  PRICING_EXAMPLE_1_MONTHLY_SERVICE_CHARGES_VALUE2: 'or about $0.12 / device / mo',
  PRICING_EXAMPLE_2: 'Pricing Example 2',
  PRICING_EXAMPLE_2_DESCRIPTION1: 'If you selected the Scale plan, added 1,000 devices that sent (POST) a package of 6 variables at every 1 hour each.',
  PRICING_EXAMPLE_2_DESCRIPTION2: 'In addition, you setup the Analysis to run your own script each time a data package is sent by the devices. Your charges would be calculated as follows:',
  PRICING_EXAMPLE_2_MONTHLY_PLAN: 'Monthly Plan:',
  PRICING_EXAMPLE_2_MONTHLY_PLAN_VALUE: 'Scale $199',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE: 'Monthly Services Usage:',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE1: 'The monthly API Requests prices is $0.025 per 1,000/requests.',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE2: 'The number of requests (month) = 1,000 * 24 * 30 = 720,000',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE3: 'The monthly cost for API Requests = 720,000 * $0.025/1000 = $18.00',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE4: 'The monthly Data Storage price is $0.015 per 1,000/register',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE5: 'The number of register (month) = 6 * 1,000 * 24 * 30 = 432,000',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE6: 'The monthly cost for the Online Data storage = 432,000 * $0.015 = $64.80',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE7: 'The monthly Analysis Runs price is $0.10 per 1,000/register',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE8: 'The number of analysis run (month) = 1,000 * 24 * 30 = 720,000',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE9: 'The monthly cost for the Analysis executed  = 720,000 * $0.10 = $72.00',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_USAGE_VALUE10: 'The monthly cost for Services usage = $18.00 + $64.80 + $72.00 = $154.80',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES: 'Total monthly charges:',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES_VALUE1: 'Total monthly charges = Plan charges + Usage charges = $199 + $154.80 = $353.80',
  PRICING_EXAMPLE_2_MONTHLY_SERVICE_CHARGES_VALUE2: 'or about $0.35 / device / mo',
  FREQUENTLY_ASKED_QUESTIONS: 'Frequently Asked Questions',
  PRICING_QUESTION1: 'For what I will be charged for?',
  PRICING_RESPONSE1: "Different from other providers, Tago doesn't charge by the number devices, dashboards, or even for end users. Our model is based on the real usage of the services, or in other words the system charges by transactions, and by the tools that are made available for you depending on your plan.  So, the monthly bill will be a sum of the plan that you selected plus the real usage of the services. You can also include some add-ons, such as the support plans.",
  PRICING_QUESTION2: 'What is the billing cycle of Tago?',
  PRICING_RESPONSE2: 'Tago closes the billing period at midnight on the last day of each month. Invoices are generally available with the first four days of the month.',
  PRICING_QUESTION3: 'If I upgrade my plan, how will that be billed?',
  PRICING_RESPONSE3: 'We make a one-time prorated charge at the time of the upgrade for the equivalent reminder of the billing cycle. For example, if you upgrade from the Free plan to the Starter plan when there is 10 remaining days in the month, we will charge 1/3 of the Starter monthly pricing immediately when you confirm the upgrade. In the next month, we will charge the full price of the Starter plan. Also, any service usage and add-ons will be added to that next bill.',
  PRICING_QUESTION4: 'What are the payment methods accepted?',
  PRICING_RESPONSE4: 'Tago accepts most major credit cards for payment. In specific cases we may be able to invoice customers directly, talk to our sales team for questions.',
  PRICING_QUESTION5: 'Do you save credit card details?',
  PRICING_RESPONSE5: 'No. Your credit card details are not saved on our servers. In fact, all information goes directly from your computer to our payment service provider (Stripe).',
  PRICING_QUESTION6: 'If I downgrade my plan, when will I see the change to be effective?',
  PRICING_RESPONSE6: 'We will downgrade you to the new selected plan at your next renewal date. Your subscription will remain active at its current level through the end of the billing period that you’ve already paid for.',
  PRICING_QUESTION7: 'If I downgrade to a free plan, what will happen with the data stored in my buckets?',
  PRICING_RESPONSE7: 'First, your subscription will remain active at its current level through the end of the billing period that you’ve already paid for. Then, while in the free plan, our system will force the 30-days data retention policy - i.e. all data with timestamp older than that will be removed. So, we highly recommend that you plan this operation carefully to prevent undesired data lost.',
  PRICING_QUESTION8: 'How is the Analysis Timeout defined?',
  PRICING_RESPONSE8: 'When the Analysis runs your script, the execution time should be less than the Timeout defined for your plan. You can monitor the status using the Console feature.',
};
