module.exports = {
  CONTACT_US: 'Contact-us',
  CONTACT_US_DESCRIPTION: 'Send us your contact information and we’ll respond to you as soon as possible.',
  CONTACT_US_QUESTION: 'Have a question for us?',
  CONTACT_US_QUESTION_PLACEHOLDER_FIRST_NAME: 'First Name',
  CONTACT_US_QUESTION_PLACEHOLDER_LAST_NAME: 'Last Name',
  CONTACT_US_QUESTION_PLACEHOLDER_PHONE: 'Phone',
  CONTACT_US_QUESTION_PLACEHOLDER_COMPANY_NAME: 'Company Name',
  CONTACT_US_QUESTION_PLACEHOLDER_EMAIL: 'E-mail',
  CONTACT_US_QUESTION_PLACEHOLDER_SUBJECT: 'Subject',
  CONTACT_US_QUESTION_PLACEHOLDER_LEAVE_MESSAGE: 'Leave a Message',
  CONTACT_US_QUESTION_BUTTON: 'Send Message',
  CONTACT_US_BY_PHONE: 'or just call us:',
  CONTACT_US_BY_PHONE_VALUE: '(800) 607-7410',
  CONTACT_US_BY_PHONE_HREF: 'tel:8006077410',
  CONTACT_US_SUPPORT: 'Support',
  CONTACT_US_SUPPORT_DESCRIPTION: 'Need support from our tech team?',
  CONTACT_US_SUPPORT_SLACK: 'Access our open community or your private business channel on Slack.',
  CONTACT_US_SUPPORT_SLACK_LINK: 'Check our slack',
  CONTACT_US_SUPPORT_DEVELOPER_PAGE: 'Check our developer page with 24/7 & free access.',
  CONTACT_US_SUPPORT_DEVELOPER_PAGE_LINK: 'Check our Developers Page',
  CONTACT_US_SUPPORT_SMS: 'Or just call us:',
  CONTACT_US_SUPPORT_SMS_VALUE: '(800) 607-7410',
  CONTACT_US_SUPPORT_SMS_HREF: 'tel:8006077410',
  CONTACT_US_SUPPORT_SMS_POINT: '.',
  CONTACT_US_SUPPORT_EMAIL_SMS: 'Contact-us',
  CONTACT_US_META: 'Send us your questions or comments with your contact information and we, our technical or business teams, will respond as soon as possible.',
};
