module.exports = {
  ADD_MARKER: 'Add Pin to this Layer',
  ADD_LAYER: 'Add layer',
  DEFINE_LABEL_TO_APPEAR_TOOLBOX: 'Define a label to appear in toolbox',
  DEFINE_EMBED_TO_APPEAR_TOOLBOX: 'Define a embed to appear in toolbox',
  DEFINE_IMAGE_EMBED_APPEAR_TOOLBOX: 'Define an image or an embed to appear in toolbox',
  DO_YOU_REALLY_DELETE_LAYER: 'Do you really want to delete this layer',
  DO_YOU_REALLY_DELETE_PIN: 'Do you really want to delete this pin?',
  EDIT_LAYER: 'Edit layer',
  EDIT_MARKER: 'Edit Pin',
  ENTER_VALUE_VARIABLE: 'enter the value of this pin',
  ICON_MARKER: 'Define an icon and color for this pin',
  IMAGE_MARKER: 'Define an image to appear in toolbox',
  VALUE_MARKER: 'Define the value for this pin',
  VARIABLE_MARKER: 'Define where this pin will be stored',
};
