module.exports = {
  TAGO_HOME: 'TagoIO - Home',
  BANNER_TITLE: 'Get more from your connected product',
  BANNER_DESCRIPTION: ' You will be amazed to learn how quickly and easily you can integrate data with TagoIO.',
  GET_STARTED_HOME: 'Get Started',
  WATCH_IT_IN_ACTION: 'Watch it in action',
  WATCH_IT_IN_ACTION_YOUTUBEVIDEO: 'neVrwqkIb3E',
  TAGO_DIVULGE_EVENTS_REGISTER: 'Register today!',
  TAGO_PLATFORM: 'TagoIO Platform',
  TAGO_PLATFORM_DESCRIPTION: 'TagoIO offers the tools for your business to manage devices, store data, run analytics, and integrate services. It combines everything with an easy-to-use application and user management system.',
  TAGO_BRINGS_ALL_FEATURES: 'TagoIO brings all the features to build your solution',
  BUILD_YOUR_APPLICATION_IN_ON_TIME: 'Build Applications',
  BUILD_YOUR_APPLICATION_IN_ON_TIME_DESCRIPTION: 'Use our templates to start quickly, collaborate with others, and get it done at no time',
  SHARE_YOUR_SOLUTIONS_EASILY: 'Integrate Solutions',
  SHARE_YOUR_SOLUTIONS_EASILY_DESCRIPTION: 'Combine your data with external systems using smart scripts and powerful API\'s',
  SCALE_UP_SMOOTHLY: 'Scale Up Smoothly',
  SCALE_UP_SMOOTHLY_DESCRIPTION: 'Manage thousands of users and devices easily. Learn from our Developer Page',
  CONNECT_ANY_DEVICE: 'Connect Any Device',
  CONNECT_ANY_DEVICE_DESCRIPTION: 'Connect any device over WiFi, LoRa, Sigfox, GPRS, LTE, BLE, Zigbee, and more',
  LEARN_ABOUT_OUR_PRODUCT: 'Learn about our Product',
  OUR_CUSTOMERS: 'Companies already helped with TagoIO',
  OUR_CUSTOMERS_SAY_IT_BEST: 'Our customers say it best',
  JULIO_ALMEIDA: 'Julio Almeida',
  JULIO_ALMEIDA_COMPANY: 'SW Dev - Agrusdata',
  JULIO_ALMEIDA_DESCRIPTION: 'After we have compared several IoT platforms, we opted for TagoIO due to its strong capabilities for device and data management, and the intuitive UX for dashboard creation. By running our analytics on TagoIO we were able to deliver a robust solution.',
  ERIC_HOOG: 'Eric Hoog',
  ERIC_HOOG_COMPANY: 'CEO - Zquel',
  ERIC_HOOG_DESCRIPTION: 'TagoIO has helped tremendously in our product development. It\'s versatility and ease of use have helped us achieve our product goals much faster than other alternatives.',
  BRENT_WARD: 'Brent Ward',
  BRENT_WARD_COMPANY: 'VP Biz Dev, Device Solutions Inc',
  BRENT_WARD_DESCRIPTION: 'TagoIO has been instrumental in providing critical elements for our Cellio IIoT Remote Monitoring/Control platform. The ability to white label their data hosting, dashboarding, mobile apps, alerts, and notifications have enabled us to provide a complete end-to-end out-of-the-box solution that has proven to be extremely flexible, desirable, and valuable to our corporate customers.',
  INDUSTRIAL_AUTOMATION: 'Industrial automation',
  SMART_IRRIGATION: 'Smart Irrigation',
  WAREHOUSE_INDOOR_LOCATION: 'Warehouse Indoor Location',
  COMPOSE: 'Compose',
  REFRIGERATED: 'Refrigerated',
  TELEMATICS: 'Telematics',
  MAIN_TITLE_HOME_PAGE: 'Easily Create Your Own IoT Solutions',
  SUB_TITLE_HOME_PAGE: 'Dashboard, Analytics, Storage, Notification, Device and User Management Included.',
  WHAT_IS_TAGO_IO: 'What is TagoIO?',
  CHECK_TAGO_FEATURES: 'TagoIO Features',
  CHECK_PRODUCT_FEATURES: 'Check Out Product Details',
  VIEW_DASHBOARD: 'View dashboard',
  HOW_DOES_IT_WORK: 'How does it Work?',
  GET_DASHBOARD: 'Get dashboard',
  WHAT_CAN_I_DO_TITLE: 'What can I do with TagoIO?',
  WHAT_CAN_I_DO_DESCRIPTION: 'Some examples of how TagoIO creates value for different applications. Enter your e-mail to get a demo dashboard.',
  ENTER_EMAIL_GAIN_ACCESS: 'Please enter your e-mail below to gain access to the $0 dashboard',
  GOT_IT: 'Got it',
  WE_ARE_WAITING_FOR_YOU: 'We are waiting for you!',
  WE_SENT_YOU_EMAIL: 'We\'ve sent you an e-mail with the chosen dashboard, all you have to do is accept it!',
  HOME_DESCRIPTION: 'TagoIO offers an end-to-end cloud platform that transforms the way businesses create value from connected products and user interactions with the Internet of Things.',
  VIDEOS_DESCRIPTION: 'Watch these videos that contains training, webinars, demos, and how-to build IoT applications quickly and with confidence.',
  PRODUCT_DETAILS: 'Product Details',
  DEVELOPER_AREA: 'Developer Area',
  WATCH_VIDEO: 'Watch video',
};
