module.exports = {
  CREATE_ACCOUNT: 'Créer un compte',
  ENTER_YOUR_EMAIL_ADDRESS_RESEND_YOUR_CONFIRMATION: "Entrez votre adresse e-mail pour renvoyer votre confirmation. Vous devrez peut-être vérifier votre dossier spam.",
  ENTER_YOUR_EMAIL_ADDRESS_RESEND_YOUR_CONFIRMATION_WL: "Entrez votre adresse e-mail pour renvoyer votre confirmation.",
  ENTER_YOUR_EMAIL_ADDRESS_RESET_YOUR_PASSWORD: "Entrez votre adresse e-mail pour réinitialiser votre mot de passe. Vous devrez peut-être vérifier votre dossier spam.",
  ENTER_YOUR_EMAIL_ADDRESS_RESET_YOUR_PASSWORD_WL: "Entrez votre adresse e-mail pour réinitialiser votre mot de passe.",
  FORGOT_YOUR_PASSWORD: 'Mot de passe oublié',
  RESEND_CONFIRMATION_EMAIL: 'Renvoyer un courriel de confirmation',
  RESEND_EMAIL: "Ré-envoyer l'email",
  RESET_PASSWORD: 'Réinitialiser le mot de passe',
  SELECT_PROFILE: 'Sélectionnez un profil partagé avec vous',
  SIGN_IN: "S'inscrire",
  VERIFY_YOU_HAVE_VERIFIED_YOUR_ACCOUNT: 'Vérifiez que vous avez validé votre compte',
  SELECT_YOUR_PROFILE: 'Sélectionnez l\'un de vos profils',
};
