module.exports = {
  ACCOUNT_SETTINGS: 'Paramètres du compte',
  ACCOUNT_TYPE: 'Type de compte',
  ALL_OTHER_EVENTS: 'Tous les autres événements',
  ARE_YOU_SURE_YOU_WANT_CHANGE_YOUR_ACCOUNT: 'Êtes-vous sûr de vouloir modifier votre compte pour',
  CHANGE_YOUR_PASSWORD: 'Changez votre mot de passe',
  CONFIRM_PASSWORD: 'Confirmez le mot de passe',
  CONFIRM_YOUR_PASSWORD: 'Confirmez votre mot de passe',
  DECIMAL_SEPARATOR: 'Séparateur décimal',
  DEVELOPER_FULL_VIEW: 'Développeur (vue complète avec tous les outils disponibles)',
  ENTER_YOUR_NAME: 'Entrez votre nom',
  ENTER_YOUR_PASSWORD: 'Tapez votre mot de passe',
  ENTER_YOUR_PHONE_NUMBER: 'Entrez votre numéro de téléphone',
  FINAL_USER: 'Utilisateur Final',
  HIDE_TOUR: 'Masquer le bouton \'Tour\'',
  IT_WILL_BE_APPLIED_ONLY_TO_NUMBER: 'Il sera appliqué uniquement au format numérique dans tous les tableaux de bord.',
  I_AM_USER_FINAL_USER: 'Je suis un',
  I_AM_DEVELOPER: 'Je suis un',
  I_WILL_BUILD_APPLICATIONS_TAGO: 'Je vais construire des applications sur Tago',
  I_WILL_ONLY_USE_APPLICATIONS: 'Je n\'utiliserai que les applications',
  MIDDLEWARE: 'Middleware',
  NEW_PASSWORD: 'Nnouveau mot de passe',
  RECEIVE_NEWSLATTER: 'Recevoir la newsletter',
  SAFARI_IE_NOT_SUPPORT_BROWSER_NOTIFICATION_SOUND: 'Safari et IE ne prennent pas en charge la notification et le son du navigateur',
  SHOW_NOTIFICATION_FROM: 'Afficher la notification de',
  SHOW_LAST_UPDATE_AT: 'Afficher la dernière mise à jour à',
  SHOW_LAST_UPDATE_AT_HELP: 'Définir où les informations sur la dernière mise à jour seront affichées.',
  USAGE_STATISTICS: 'Statistiques d\'utilisation',
  USER_ONLY: 'Seulement utilisateur',
  USER_REDUCE_VIEW: 'Utilisateur (vue réduite)',
  USERS_MANAGEMENT: 'Gestion des utilisateurs',
  TOKENS: 'Jetons',
  VIEW_MODE: 'Mode d\'affichage Admin',
  VISUALIZATION_PREFERENCES: 'Préférences de visualisation',
  WE_OCCASIONALLY_SEND_NEWSLETTERS_WITH_RELEVANT_TOPICS: 'Nous envoyons occasionnellement des bulletins d\'information avec des sujets pertinents',
  WIDGET_MENU: 'Menu widget',
  WIDGET_FOOTER: 'Widget footer',
  YOU_NEED_ENTER_SAME_PASSWORD_TWICE: 'Vous devez entrer le même mot de passe deux fois',
  ACCOUNT_TYPE_DESCRIPTION: 'Ici, vous pouvez définir le type de compte que vous allez utiliser.',
  ACCOUNT_TYPE_FINAL_USER_DESCRIPTION: 'Vous n’utiliserez pas TagoIO pour créer des applications, mais pour les utiliser. Utilisez cette option si vous ne savez pas ce que vous faites.',
  ACCOUNT_TYPE_DEVELOPER_DESCRIPTION: 'Vous utiliserez TagoIO pour créer des applications. L\'utilisation de cette option permet d\'accéder aux nouvelles fonctionnalités de la plateforme.',
  ENTER_YOUR_COMPANY: 'Entrez ici votre entreprise',
  THIS_RULE_WILL_BE_APPLIED_TO_ALL: 'Cette règle sera appliquée à tous les widgets activés par le développeur.',
  TIME_FORMAT_TOOLTIP: "C'est le format de l'heure qui sera appliqué à votre compte.",
  DATE_FORMAT_TOOLTIP: "C'est le format de date qui sera appliqué à votre compte.",
};
