module.exports = {
  RESOURCES_DEVELOPERS: 'Developers',
  RESOURCES_DEVELOPERS_SUBTITLE: 'Resources for you to develop your application on TagoIO',
  RESOURCES_DEVELOPERS_DOCUMENTATION: 'Documentation',
  RESOURCES_DEVELOPERS_DOCUMENTATION_DESCRIPTION: 'Access all documentation - from getting started to advanced features.',
  RESOURCES_DEVELOPERS_DOCUMENTATION_LINK1: 'Getting Started',
  RESOURCES_DEVELOPERS_DOCUMENTATION_LINK2: 'Concepts',
  RESOURCES_DEVELOPERS_DOCUMENTATION_LINK3: 'Tutorials',
  RESOURCES_DEVELOPERS_DOCUMENTATION_LINK4: 'MQTT',
  RESOURCES_DEVELOPERS_SDK: 'SDK',
  RESOURCES_DEVELOPERS_SDK_DESCRIPTION: 'Develop faster using our SDK for the language your need.',
  RESOURCES_DEVELOPERS_SDK_LINK1: 'NodeJS',
  RESOURCES_DEVELOPERS_SDK_LINK2: 'Java',
  RESOURCES_DEVELOPERS_SDK_LINK3: 'Python',
  RESOURCES_DEVELOPERS_GITHUB: 'Github',
  RESOURCES_DEVELOPERS_DESCRIPTION: 'Access several libraries available on Github. Download, customize, and run them in your application.',
  RESOURCES_DEVELOPERS_LINK1: 'Repositories',
  RESOURCES_DEVELOPERS_COMMUNITY: 'Community',
  RESOURCES_DEVELOPERS_COMMUNITY_DESCRIPTION: 'Join our TagoIO community on Slack to get help from anyone, including our developers.',
  RESOURCES_DEVELOPERS_COMMUNITY_LINK1: 'Slack',
  RESOURCES_DEVELOPERS_CHANGELOG: 'Changelog',
  RESOURCES_DEVELOPERS_CHANGELOG_DESCRIPTION: 'Don\'t miss the latest updates done in our back-end or front-end.',
  RESOURCES_DEVELOPERS_CHANGELOG_LINK1: 'Back-end Changelog',
  RESOURCES_DEVELOPERS_CHANGELOG_LINK2: 'Front-end Changelog',
  RESOURCES_DEVELOPERS_SYSTEM_STATUS: 'System Status',
  RESOURCES_DEVELOPERS_SYSTEM_STATUS_DESCRIPTION: 'Get updated status for all TagoIO services in real-time. Reports include uptime and average access time for Get and Post methods.',
  RESOURCES_DEVELOPERS_SYSTEM_STATUS_LINK1: 'System Status Report',
  RESOURCES_DEVELOPERS_DOWNLOADS: 'Download',
  RESOURCES_DEVELOPERS_DOWNLOADS_DESCRIPTION: 'Accelerate your learning curve using our Launch Guide and Best Practices documents.',
  RESOURCES_DEVELOPERS_DOWNLOADS_LINK1: 'Launch Guide',
  RESOURCES_DEVELOPERS_DOWNLOADS_LINK2: 'Dashboard Best Practices',
  RESOURCES_DEVELOPERS_DOWNLOADS_LINK3: 'Analysis Best Practices',
  RESOURCES_PARTNERS: 'Our Partners',
  RESOURCES_PARTNERS_DESCRIPTION: 'Our partners can leverage their hardware, firmware, application, and network expertise to help you to create the best solution built on TagoIO platform',
  RESOURCES_VIDEOS: 'Videos',
  RESOURCES_VIDEOS_DESCRIPTION: 'Videos to help you build the best connected product',
  RESOURCES_FAQ: 'Frequently asked questions',
  RESOURCES_FAQ_DESCRIPTION: 'If you need more information, these FAQs can help',
  RESOURCES_FAQ_QUESTION1: 'Which web browser does TagoIO Admin work with?',
  RESOURCES_FAQ_ANSWER1: 'TagoIO Admin is optimized for Chrome (latest version), Firefox (latest version), Safari (latest version), Edge, and with some limitations for Internet Explorer 11. Also, it works with Chrome on Android (latest version), and Safari on iOS (latest version).',
  RESOURCES_FAQ_QUESTION2: 'Where is my data stored?',
  RESOURCES_FAQ_ANSWER2: 'TagoIO database is located on servers in the United States. We are planing to add servers in other regions (Europe, Japan, Brazil...) soon, so that users can keep all data in their own region. It is important to remember that users can download all data to their own servers, and define a retention period to define how long data should be kept at TagoIO.',
  RESOURCES_FAQ_QUESTION3: 'How can I know which users are accessing my applications?',
  RESOURCES_FAQ_ANSWER3: 'By using our Whitelabel edition, your applications and users will be separated to an area controlled by your master account. You will know who signed up, and will be able to grant or deny access to each one. This information will be available only for you.',
  RESOURCES_FAQ_QUESTION4: 'In what languages is TagoIO available?',
  RESOURCES_FAQ_ANSWER4: 'TagoIO is fully supported in English for Developers. And for end users (User View) TagoIO is also available in Spanish, Portuguese and French. Select the desired language in Account Settings > Visualization Preferences, under MyAccount option.',
  RESOURCES_FAQ_QUESTION5: 'Is an on-premises version available?',
  RESOURCES_FAQ_ANSWER5: 'TagoIO runs on cloud so that customers can get the best of redundancy, uptime with the minimum of overhead and costs. There is no on-premises version yet (for installation).',
  RESOURCES_FAQ_QUESTION6: 'Is TagoIO HIPAA and FedRAMP compliant?',
  RESOURCES_FAQ_ANSWER6: 'Our roadmap includes TagoIO certification for HIPPA (Health Insurance Portability and Accountability Act of 1996) and FedRAMP (Federal Risk and Authorization Management Program ). Contact us if any of these compliances are required for your project.',
  DEVELOPERS_DESCRIPTION: 'Our knowledge area contains rich resources for you to quickly develop IoT solutions using TagoIO tools.',
};
