module.exports = {
  ACCOUNT_SETTINGS: 'Account Settings',
  ACCOUNT_TYPE: 'Account Type',
  ALL_OTHER_EVENTS: 'All other events',
  ARE_YOU_SURE_YOU_WANT_CHANGE_YOUR_ACCOUNT: 'Are you sure you want to change your account to',
  CHANGE_YOUR_PASSWORD: 'Change your password',
  CONFIRM_PASSWORD: 'Confirm password',
  CONFIRM_YOUR_PASSWORD: 'confirm your password',
  DEVELOPER_FULL_VIEW: 'Developer (Full view with all tools available)',
  ENTER_YOUR_NAME: 'enter your name',
  ENTER_YOUR_PASSWORD: 'enter your password',
  ENTER_YOUR_PHONE_NUMBER: 'enter your phone number',
  FINAL_USER: 'Final User',
  HIDE_TOUR: "Hide button 'Tour'",
  I_AM_USER_FINAL_USER: 'I am a',
  I_AM_DEVELOPER: 'I am a',
  I_WILL_BUILD_APPLICATIONS_TAGO: 'I will build applications on Tago',
  I_WILL_ONLY_USE_APPLICATIONS: 'I will only use the applications',
  MIDDLEWARE: 'Middleware',
  NEW_PASSWORD: 'New password',
  RECEIVE_NEWSLATTER: 'Receive newsletter',
  SAFARI_IE_NOT_SUPPORT_BROWSER_NOTIFICATION_SOUND: 'Safari and IE does not support browser notification and sound',
  SHOW_NOTIFICATION_FROM: 'Show notification from',
  SHOW_LAST_UPDATE_AT: 'Show last updated at',
  USAGE_STATISTICS: 'Usage Statistics',
  USER_ONLY: 'User only',
  USER_REDUCE_VIEW: 'User (reduced view)',
  USERS_MANAGEMENT: 'Users Management',
  TOKENS: 'Tokens',
  VIEW_MODE: 'Admin visualization mode',
  VISUALIZATION_PREFERENCES: 'Visualization Preferences',
  WE_OCCASIONALLY_SEND_NEWSLETTERS_WITH_RELEVANT_TOPICS: 'We occasionally send newsletters with relevant topics',
  WIDGET_MENU: 'Widget menu',
  WIDGET_FOOTER: 'Widget footer',
  YOU_NEED_ENTER_SAME_PASSWORD_TWICE: 'You need to enter the same password twice',
};
