module.exports = {
  SELECT: 'Selecionar',
  SELECTED_PLAN: 'Plano selecionado',
  VISIT_THIS_DEMO_NOW: 'Veja o demo agora',
  PER_MONTH: 'mes',
  GO_TO_DOCUMENTATION: 'Vá para a documentação',
  VIDEO: 'Video',
  FEATURES_UNLIMITED: 'Ilimitado',
  PARTNER_DETAIL_VISIT_COMPANY_WEBSITE: 'Visite o website',
  PARTNER_DETAIL_VISIT_COMPANY_TUTORIAL: 'Visite o tutorial do Produto',
  PARTNER_DETAIL_PRODUCTS_SERVICES_INTEGRATED_TAGO: 'Produtos and serviços integrados com a Tago',
  PLAN: 'Plano',
  SERVICES: 'Serviços',
  HOW_PARTNER_INTEGRATES_WITH_TAGO: 'Como $0 se integra com a TagoIO',
};
