module.exports = {
  TAGORUN_TITLE: 'TagoRUN',
  TAGORUN_DESCRIPTION: 'TagoRUN works as a customized IoT portal for customers. It is the best way for end-users to access Internet of Things applications by using custom domain and white label features. You can customize colors, logo, e-mail, and buttons to engage more customers with your own IoT branded solution.',
  TAGORUN_SUBTITLE: 'Deploy your own platform',
  TAGORUN_PAGE_TITLE: 'The best way for end-users to access your IoT applications',
  TAGORUN_BUTTON: 'Get Started',

  TAGORUN_SECTION1_TITLE: 'Take full advantage of TagoRUN',
  TAGORUN_SECTION1_SUBTITLE: 'Free to use. Affordable to expand',
  TAGORUN_SECTION1_ITEM1_TITLE: 'Add your brand in minutes for free',
  TAGORUN_SECTION1_ITEM1_DESCRIPTION: 'Customize your TagoRUN by adding your brand inside the platform, signup, and mobile App at no cost. Just select the colors, texts, images, and upload your logo.',
  TAGORUN_SECTION1_ITEM2_TITLE: 'Have full control of your users',
  TAGORUN_SECTION1_ITEM2_DESCRIPTION: 'Define the type of access that each user will have in your platform. Track how they interact with your solution.',
  TAGORUN_SECTION1_ITEM3_TITLE: 'Customize your domain and e-mails',
  TAGORUN_SECTION1_ITEM3_DESCRIPTION: 'Your customers can sign up in your domain instead of tago.io. Our brand can also be removed.',
  TAGORUN_SECTION1_ITEM4_TITLE: 'Access GPS and Wi-Fi modules',
  TAGORUN_SECTION1_ITEM4_DESCRIPTION: 'Track the location of end-users from their mobile devices. Simple native Wi-Fi provision setup available.',

  TAGORUN_SECTION2_TITLE: 'Powerful features that go beyond whitelabel',
  TAGORUN_SECTION2_ROW1_TITLE: 'Get insight from end-users',
  TAGORUN_SECTION2_ROW1_DESCRIPTION1: 'Use the best analytics services that allow you to analyze in-depth details about your TagoRUN’s users. You can easily integrate your TagoRUN application with Google Analytics or Zoho SalesIQ tools. ',
  TAGORUN_SECTION2_ROW1_DESCRIPTION2: 'Learn about Google Analytics and TagoRUN',
  TAGORUN_SECTION2_ROW2_TITLE: 'Access mobile features',
  TAGORUN_SECTION2_ROW2_DESCRIPTION: 'Take advantage of the GPS available in mobile devices, that works as a free IoT device, to create solutions for your customers without any additional cost. Use our native provisioning feature that makes it easy for end-users to register Wi-Fi devices on their network.',
  TAGORUN_SECTION2_ROW3_TITLE: 'Take full control of your application',
  TAGORUN_SECTION2_ROW3_DESCRIPTION: 'Determine how users will access your IoT application and the level of access for each one. By working with our User Management and Access management modules, you can create policies for individuals, groups, or even external organizations.',
  TAGORUN_SECTION2_ROW4_TITLE: 'Engage more with your customers',
  TAGORUN_SECTION2_ROW4_DESCRIPTION: 'Send customized messages to your end-user through our notification and e-mail systems. Add chats, bots, calls, remote screen access, and more. Customize your own unique email template for welcoming your new users, when activating their accounts or even resetting their passwords.',
  TAGORUN_SECTION2_ROW5_TITLE: 'Custom domain & white label',
  TAGORUN_SECTION2_ROW5_DESCRIPTION: 'Your customers will sign up in the portal using your own URL, e.g. iot.mycompany.com, when you add the Custom Domain add-on. Your company’s colors, logo, theme, background, and button settings all replace the TagoIO branding.',

  TAGORUN_FAQ_QUESTION1: 'How can I get started with TagoRUN?',
  TAGORUN_FAQ_ANSWER1_PART1: 'First, build your application in the TagoIO admin (admin.tago.io) by connecting IoT devices, creating dashboards, reports and all you’ll need for your application. Then, configure the appearance and settings for your TagoRUN and set up the access policies for end-users. Watch our videos and tutorials, or contact us. More information can be found in our ',
  TAGORUN_FAQ_ANSWER1_PART2: 'documentation',

  TAGORUN_FAQ_QUESTION2: 'Do I have to deploy my IoT solution with TagoRUN?',
  TAGORUN_FAQ_ANSWER2: 'Not necessarily. You may want to only use the TagoIO admin for you and your team. TagoIO by itself works very well when used for personal use, a small team, or for members of the same organization. However, we highly recommend to deploy with TagoRUN when solutions are aimed for end-users as it not only makes it easier for you to manage their access, but also for them to use it. Finally, TagoRUN allows your users to always have your brand in mind!',

  TAGORUN_FAQ_QUESTION3: 'How much does TagoRUN cost?',
  TAGORUN_FAQ_ANSWER3_PART1: 'TagoRUN is free, with most features available. Your solutions will run under our domain, .run.tago.io (e.g. mycompany.run.tago.io). If you want to remove our logo and any reference to TagoIO, select the Custom Domain add-on. It will remove our brand and allow your solution to run in your own domain (e.g. iot.mycompany.com), even your emails will be sent from your DNS. Prices are available ',
  TAGORUN_FAQ_ANSWER3_PART2: 'here',

  TAGORUN_FAQ_QUESTION4: 'How does TagoRUN works with TagoIO admin? ',
  TAGORUN_FAQ_ANSWER4: 'TagoRUN is one of the various modules from the TagoIO platform that works with our “Access Management” and “User Management” features; thus enabling you to deliver the best user experience possible for your end-users (customers).',

  TAGORUN_FAQ_QUESTION5: 'Can I have a mobile App launched alongside my brand?',
  TAGORUN_FAQ_ANSWER5_PART1: 'Yes. Our TagoRUN mobile app is free and ready for you to evaluate solutions, either by yourself or with your customers. If you want to remove TagoIO branding completely, we can customize and deploy a mobile App on your behalf. Customers will find them under your company name, without any mention of TagoIO. ',
  TAGORUN_FAQ_ANSWER5_PART2: 'Contact us',
  TAGORUN_FAQ_ANSWER5_PART3: ' for more information.',
};
