module.exports = {
  NOTIFICATIONS_FROM_INSTALL: 'Aplicação instalada com sucesso',
  NOTIFICATIONS_FROM_USER_REGISTERED: '$0 conta criada na tago. O item que você compartilhou está disponível para ele aceitar.',
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: 'Oops... $0 está registrado na Tago, mas algo deu errado com o compartilhamento. Tente compartilhar novamente.',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'Novo usuário registrado',
  NOTIFICATIONS_SEARCH: 'filtrar notificações',
  ONLY_UNREAD: 'Somente não lidas',
  OTHER_USERS: 'Outros usuários',
  RESEND_EMAIL_CONFIRMATION: 'Reenviar email de confirmação',
  TAGO_SYSTEM: 'Sistema Tago',
  YOU_REALLY_WANT_EXIT: 'Você realmente deseja sair',
  YOUR_EMAIL_HASNT_BEEN_CONFIRMED: 'Seu email ainda não foi confirmado. Confirme seu e-mail para usar todos os recursos do TagoIO.',
  TEMPLATE_TAB_NAME: 'Distribute the template of this $0',
  TEMPLATE_TAB_DESCRIPTION: 'Send the generated URL to others so they can access your $0 through a customized install page.',
  TEMPLATE_TAB_LINK_DESCRIPTION: 'Create a link that contains the template of this $0. Share the link with anyone.',
  TEMPLATE_TAB_URL_PLACEHOLDER: 'build your template to generate an url',
  TEMPLATE_LAST_GENERATED_AT: 'Last generated at',
  CUSTOMIZE_TEMPLATE_TITLE: 'Customize the page',
  CUSTOMIZE_TEMPLATE_DESCRIPTION: 'Add a logo and an image that better represents your template.',
  CUSTOMIZE_TEMPLATE_DESCRIPTION2: 'Images will be shown when users access the page using the generated URL.',
  TEMPLATE_LABEL_TITLE: 'Title of the page',
  TEMPLATE_PLACEHOLDER_TITLE: 'The title of the page',
  TEMPLATE_LABEL_LOGO: 'Logo of the page',
  TEMPLATE_PLACEHOLDER_LOGO: 'https url of the logo',
  TEMPLATE_LABEL_MAIN_IMG: 'Main image of the page',
  TEMPLATE_PLACEHOLDER_MAIN_IMG: 'https url of the main image',
  TEMPLATE_ANALYSIS_SETUP_TITLE: 'If you use environment variables, describe each "variable value" here.',
  TEMPLATE_ANALYSIS_SETUP_DESCRIPTION: 'Whoever receives this analysis will use this information to configure the variable value',
  TEMPLATE_DASHBOARD_SETUP_TITLE: 'Enter a description for each device',
  TEMPLATE_DASHBOARD_SETUP_DESCRIPTION: 'This information will help the user to select the right device in his/her account. (e.g. GPS Calamp LMU3030, Generator GRX2000, …).',
  TEMPLATE_BUILD_TEMPLATE: 'Build Template',
  SETUP_LIST_DESCRIPTION_ANALYSIS: 'enter a description for this "variable value"',
  SETUP_LIST_DESCRIPTION_DASHBOARD: 'enter a detailed description for this device',
  COPIED: 'Copied',
  COPY: 'Copy',
  NOTIFICATION_PROFILE_SHARE: '$0 quer compartilhar um perfil com você',
  NOTIFICATION_BUCKET_SHARE: '$0 quer compartilhar o depósito de $1 com você',
  NOTIFICATION_DASHBOARD_SHARE: '$0 quer compartilhar o painel $1 com você',
  NEW_USER_RESENT_CONFIRMATION_EMAIL: 'Enviamos um email para <b> $0</b>. Por favor, confirme seu email para ter acesso a todos os recursos!',
  DASHBOARD_ACCEPTED_NOTIFICATION: 'O painel foi adicionado à <b> barra lateral esquerda</b>.',
  PROFILE_ACCEPTED_NOTIFICATION: 'O perfil foi aceito! <br /> <b> Por favor, faça logout</b> para ter acesso à conta de $0.',
  BUCKET_ACCEPTED_NOTIFICATION: 'O intervalo foi aceito e adicionado à <b> lista de intervalos</b>.',
  GO_TO_DASHBOARD: 'Ir para o painel',
  HOME_END_USER_INTRO: 'Saiba como interagir com dispositivos conectados a seus aplicativos. Basta selecionar um painel e seguir as instruções para operar o aplicativo.',
  NOT_A_DEV_DESCRIPTION: 'Se você não é um desenvolvedor, use nosso modo de exibição simples. É mais fácil de usar!',
  CHANGE_TO_SIMPLE_USER_VIEW: 'Alterar para exibição simples',
  CHANGE_TO_DEVELOPER_VIEW: 'Alterar para desenvolvedor',
  A_DEV_DESCRIPTION: 'Sou desenvolvedor e desenvolverei aplicativos na plataforma.',
  DASHBOARD_DESCRIPTION_HOME: 'Um painel é onde todas as informações de um aplicativo estão localizadas. Para acessar um painel, selecione um no menu do lado esquerdo.',
  EXPLORE_DESCRIPTION_HOME: 'Explore é onde você pode ver exemplos de painéis. Para acessá-lo, clique na opção explorar no menu do lado esquerdo',
  NOTIFICATION_DESCRIPTION_HOME: 'Notificações são onde você recebe informações importantes sobre os painéis e sua conta. Como estão as regras do lado direito do sistema.',
  SHARE_DASHBOARDS_DESCRIPTION_HOME: 'Você pode compartilhar painéis com outros usuários, concedendo a eles o acesso para visualizar e interagir com um painel.',
  USER_ACCOUNT_DESCRIPTION_HOME: 'Você pode alterar as informações de sua conta na parte superior direita da página, onde seu nome aparece.',
  HOME_END_USER_INTRO_TITLE: 'Saiba mais sobre os recursos',
  REALTIME_INFO_HOME: 'Este status mostra se o seu navegador está conectado ao servidor em tempo real, útil para alguns widgets',
};
