module.exports = {
  NOTIFICATIONS_FROM_INSTALL: 'Aplicação instalada com sucesso',
  NOTIFICATIONS_FROM_USER_REGISTERED: '$0 conta criada na tago. O item que você compartilhou está disponível para ele aceitar.',
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: 'Oops... $0 está registrado na Tago, mas algo deu errado com o compartilhamento. Tente compartilhar novamente.',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'Novo usuário registrado',
  NOTIFICATIONS_SEARCH: 'filtrar notificações',
  ONLY_UNREAD: 'Somente não lidas',
  OTHER_USERS: 'Outros usuários',
  RESEND_EMAIL_CONFIRMATION: 'Reenviar email de confirmação',
  TAGO_SYSTEM: 'Sistema Tago',
  YOU_REALLY_WANT_EXIT: 'Você realmente deseja sair',
  YOUR_EMAIL_HASNT_BEEN_CONFIRMED: 'Seu email ainda não foi confirmado. Confirme seu e-mail para usar todos os recursos do TagoIO.',
  
  TEMPLATE_TAB_NAME: 'Distribute the template of this $0',
  TEMPLATE_TAB_DESCRIPTION: 'Send the generated URL to others so they can access your $0 through a customized install page.',
  TEMPLATE_TAB_LINK_DESCRIPTION: 'Create a link that contains the template of this $0. Share the link with anyone.',
  TEMPLATE_TAB_URL_PLACEHOLDER: 'build your template to generate an url',
  TEMPLATE_LAST_GENERATED_AT: 'Last generated at',
  CUSTOMIZE_TEMPLATE_TITLE: 'Customize the page',
  CUSTOMIZE_TEMPLATE_DESCRIPTION: 'Add a logo and an image that better represents your template.',
  CUSTOMIZE_TEMPLATE_DESCRIPTION2: 'Images will be shown when users access the page using the generated URL.',
  TEMPLATE_LABEL_TITLE: 'Title of the page',
  TEMPLATE_PLACEHOLDER_TITLE: 'The title of the page',
  TEMPLATE_LABEL_LOGO: 'Logo of the page',
  TEMPLATE_PLACEHOLDER_LOGO: 'https url of the logo',
  TEMPLATE_LABEL_MAIN_IMG: 'Main image of the page',
  TEMPLATE_PLACEHOLDER_MAIN_IMG: 'https url of the main image',
  TEMPLATE_ANALYSIS_SETUP_TITLE: 'If you use environment variables, describe each "variable value" here.',
  TEMPLATE_ANALYSIS_SETUP_DESCRIPTION: 'Whoever receives this analysis will use this information to configure the variable value',
  TEMPLATE_DASHBOARD_SETUP_TITLE: 'Enter a description for each device',
  TEMPLATE_DASHBOARD_SETUP_DESCRIPTION: 'This information will help the user to select the right device in his/her account. (e.g. GPS Calamp LMU3030, Generator GRX2000, …).',
  TEMPLATE_BUILD_TEMPLATE: 'Build Template',
  SETUP_LIST_DESCRIPTION_ANALYSIS: 'enter a description for this "variable value"',
  SETUP_LIST_DESCRIPTION_DASHBOARD: 'enter a detailed description for this device',
  COPIED: 'Copied',
  COPY: 'Copy',
};
