module.exports = {
  APRIL: 'Abril',
  AUGUST: 'Agosto',
  DECEMBER: 'Dezembro',
  FEBRUARY: 'Fevereiro',
  FRIDAY: 'Sexta',
  JANUARY: 'Janeiro',
  JULY: 'Julho',
  JUNE: 'Junho',
  MARCH: 'Março',
  MAY: 'Maio',
  MONDAY: 'Segunda',
  NOTIFICATIONS_FROM_INSTALL: 'Aplicação instalada com sucesso',
  NOTIFICATIONS_FROM_USER_REGISTERED: '$0$ conta criada na tago. O item que você compartilhou está disponível para ele aceitar.',
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: 'Oops... $0$ está registrado na Tago, mas algo deu errado com o compartilhamento. Tente compartilhar novamente.',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'Novo usuário registrado',
  NOTIFICATIONS_SEARCH: 'filtrar notificações',
  NOVEMBER: 'Novembro',
  OCTOBER: 'Outubro',
  ONLY_UNREAD: 'Somente não lidas',
  OTHER_USERS: 'Outros usuários',
  SATURDAY: 'Sábado',
  SEPTEMBER: 'Setembro',
  SUNDAY: 'Domingo',
  TAGO_SYSTEM: 'Sistema Tago',
  THURSDAY: 'Quinta',
  TUESDAY: 'Terça',
  WEDNESDAY: 'Quarta',
  YOU_REALLY_WANT_EXIT: 'Você realmente deseja sair',
};
