module.exports = {
  CREATE_ACCOUNT: 'crie uma conta',
  ENTER_YOUR_EMAIL_ADDRESS_RESEND_YOUR_CONFIRMATION: 'Digite seu endereço de email para reenviar sua confirmação. Talvez seja necessário verificar sua pasta de spam.',
  ENTER_YOUR_EMAIL_ADDRESS_RESEND_YOUR_CONFIRMATION_WL: 'Digite seu endereço de email para reenviar sua confirmação.',
  ENTER_YOUR_EMAIL_ADDRESS_RESET_YOUR_PASSWORD: 'Digite seu endereço de email para redefinir sua senha. Talvez seja necessário verificar sua pasta de spam.',
  ENTER_YOUR_EMAIL_ADDRESS_RESET_YOUR_PASSWORD_WL: 'Digite seu endereço de email para redefinir sua senha.',
  FORGOT_YOUR_PASSWORD: 'Redefinir senha',
  RESEND_CONFIRMATION_EMAIL: 'Reenviar email de confirmação',
  RESEND_EMAIL: 'Reenviar email',
  RESET_PASSWORD: 'Redefinir senha',
  SELECT_PROFILE: 'Selecione um perfil compartilhado com você',
  SIGN_IN: 'Autentique-se',
  VERIFY_YOU_HAVE_VERIFIED_YOUR_ACCOUNT: 'Verifique se você validou sua conta no email',
  SELECT_YOUR_PROFILE: 'Selecione um de seus perfis',
};
