module.exports = {
  HOME: 'Home',
  USE_CASES: 'Use Cases',
  PRICING: 'Pricing',
  PRODUCT: 'Product',
  FEATURES: 'Features',
  CONNECTIVITY: 'Connectivity',
  INTEGRATION: 'Integration',
  CUSTOMIZATION: 'Customization',
  RESOURCES: 'Resources',
  DEVELOPERS: 'Developers',
  PARTNERS: 'Partners',
  VIDEOS: 'Videos',
  FAQ: 'FAQ',
  BLOG: 'Blog',
  CONTACT_US: 'Contact-us',
  TALK_TO_SALES: 'Talk to Sales',
  CUSTOMER_SUPPORT: 'Customer Support',
  SIGN_IN: 'Sign In',
  GET_STARTED: 'Get Started',
  TAGORUN: 'TagoRUN',
};
