module.exports = {
  ACCOUNT_SETTINGS: 'Configuraciones de la cuenta',
  ACCOUNT_TYPE: 'Tipo de cuenta',
  ALL_OTHER_EVENTS: 'Todos los demás eventos',
  ARE_YOU_SURE_YOU_WANT_CHANGE_YOUR_ACCOUNT: '¿Seguro que quieres cambiar tu cuenta a',
  CHANGE_YOUR_PASSWORD: 'cambia tu contraseña',
  CONFIRM_PASSWORD: 'Confirmar contraseña',
  CONFIRM_YOUR_PASSWORD: 'confirmar la contraseña',
  DECIMAL_SEPARATOR: 'Separador decimal',
  DEVELOPER_FULL_VIEW: 'Desarrollador (vista completa con todas las herramientas disponibles)',
  ENTER_YOUR_NAME: 'Ingrese su nombre',
  ENTER_YOUR_PASSWORD: 'Ingrese la contraseña',
  ENTER_YOUR_PHONE_NUMBER: 'Ingrese su número telefónico',
  FINAL_USER: 'Usuario Final',
  HIDE_TOUR: 'Botón ocultar \'Tour\'',
  IT_WILL_BE_APPLIED_ONLY_TO_NUMBER: 'Se aplicará solo al formato Número en todos los tableros',
  I_AM_USER_FINAL_USER: 'Soy un',
  I_AM_DEVELOPER: 'Soy un',
  I_WILL_BUILD_APPLICATIONS_TAGO: 'Construiré aplicaciones en Tago',
  I_WILL_ONLY_USE_APPLICATIONS: 'Solo usaré las aplicaciones',
  MIDDLEWARE: 'Middleware',
  NEW_PASSWORD: 'Nueva contraseña',
  RECEIVE_NEWSLATTER: 'Recibir boletín informativo',
  SAFARI_IE_NOT_SUPPORT_BROWSER_NOTIFICATION_SOUND: 'Safari y IE no son compatibles con la notificación y el sonido del navegador',
  SHOW_NOTIFICATION_FROM: 'Mostrar notificación de',
  SHOW_LAST_UPDATE_AT: 'Mostrar la última actualización en',
  SHOW_LAST_UPDATE_AT_HELP: 'Definir dónde se mostrará la información sobre la última actualización.',
  USAGE_STATISTICS: 'Estadísticas de uso',
  USER_ONLY: 'Solo usuario',
  USER_REDUCE_VIEW: 'Usuario (vista reducida)',
  USERS_MANAGEMENT: 'Gestión de usuarios',
  TOKENS: 'Tokens',
  VIEW_MODE: 'Modo de vista Admin',
  VISUALIZATION_PREFERENCES: 'Preferencias de visualización',
  WE_OCCASIONALLY_SEND_NEWSLETTERS_WITH_RELEVANT_TOPICS: 'Ocasionalmente enviamos boletines informativos con temas relevantes',
  WIDGET_MENU: 'Widget de menú',
  WIDGET_FOOTER: 'Pie de página del widget',
  YOU_NEED_ENTER_SAME_PASSWORD_TWICE: 'Debes ingresar la misma contraseña dos veces',
  ACCOUNT_TYPE_DESCRIPTION: 'Aquí puede definir qué tipo de cuenta va a utilizar.',
  ACCOUNT_TYPE_FINAL_USER_DESCRIPTION: 'No usarás TagoIO para crear aplicaciones, solo para usarlas. Utilice esta opción si no sabe lo que está haciendo.',
  ACCOUNT_TYPE_DEVELOPER_DESCRIPTION: 'Estarás usando TagoIO para crear aplicaciones. El uso de esta opción otorga acceso a nuevas funciones en la plataforma.',
  ENTER_YOUR_COMPANY: 'Entra aquí tu empresa',
  THIS_RULE_WILL_BE_APPLIED_TO_ALL: 'Esta regla se aplicará a todos los widgets habilitados por el desarrollador',
  TIME_FORMAT_TOOLTIP: "Este es el formato de hora que se aplicará en su cuenta.",
  DATE_FORMAT_TOOLTIP: "Este es el formato de fecha que se aplicará en su cuenta.",
};
