module.exports = {
  COMMUM_NEXT: 'Próximo',

  WELCOME_GET_STARTED: 'Primeros pasos',
  WELCOME_CONNECT_DEVICE: 'Conecta tu dispositivo',
  WELCOME_CONNECT_DEVICE_DESC: 'Conecte cualquier dispositivo para el que ya hemos creado un controlador. Siga nuestras pautas para conectar su propio dispositivo fácilmente.',
  WELCOME_BUILD_APP: 'Construir su aplicación',
  WELCOME_BUILD_APP_DESC: 'Combine datos de diferentes tipos de dispositivos dentro de tu propia aplicación. Acceda a su cuenta en www.tago.io y comience a construir ahora.​',
  WELCOME_SHARE_ANY: 'Comparte con quien quieras',
  WELCOME_SHARE_ANY_DESC: 'Comparta sus tableros con cualquier persona mediante el uso de la opción privada o pública. Otros recibirán actualizaciones en tiempo real.',

  LOGIN_EMAIL: 'Dirección E-mail',
  LOGIN_PASSWORD: 'Contraseña',
  LOGIN_BTN_SIGNIN: 'iniciar Sesión',
  LOGIN_BTN_SIGNUP: 'Crea una Cuenta',

  SECTION_DASHBOARD: 'Tableros',
  SECTION_DASHBOARD_INFO: 'Información del Tablero',
  SECTION_EXPLORE: 'Explorar',
  SECTION_NOTIFICATION: 'Notificaciones',
  SECTION_SETTINGS: 'Ajustes',
  SECTION_SHAREPRIVATE: 'Compartir Privado',
  SECTION_APPINFO: 'Información de Aplicación',
  SECTION_DEVICES: 'Dispositivos',

  SETTINGS_TOUCHID: 'Habilitar TouchID',
  SETTINGS_NOTIFICATIONS: 'Notificaciones',
  SETTINGS_FULLSCREEN: 'Pantalla completa en horizoltal',
  SETTINGS_KEEPAWAKE: 'Mantener Despierto',
  SETTINGS_LOGOUT: 'Cerrar Sesión',
  SETTINGS_VERSION: 'Versión:',

  NOTIFICATIONS_ACCEPTED: 'Aceptado',
  NOTIFICATIONS_DECLINED: 'Rechazado',
  NOTIFICATIONS_ACCEPT: 'Aceptar',
  NOTIFICATIONS_DECLINE: 'Declinar',
  NOTIFICATIONS_IGNORE: 'Ignorar',
  NOTIFICATIONS_GOTODASH: 'Ir al tablero',
  NOTIFICATIONS_APPSETTINGS: 'Ajustes de la aplicación',
  NOTIFICATIONS_NEWUSERREGISTERED: 'Nuevo usuario registrado',
  NOTIFICATIONS_NEWUSERREGISTERED_DESC: '$0$ acaba de crear una cuenta en Tago. El ítem que compartiste está disponible para que él lo acepte',
  NOTIFICATIONS_SHAREPROFILE: 'Perfil compartir',
  NOTIFICATIONS_SHAREPROFILE_DESC: '$0$ desea compartir el perfil contigo',
  NOTIFICATIONS_SHAREREQUEST_DASH: 'Solicitud de Compartir - Tablero',
  NOTIFICATIONS_SHAREREQUEST_DASH_DESC: '$0$ desea compartir el tablero $1$ contigo',
  NOTIFICATIONS_SHAREREQUEST_BUCKET: 'Solicitud de Compartir - Bucket',
  NOTIFICATIONS_SHAREREQUEST_BUCKET_DESC: '${notification.ref_from.name} desea compartir un bucket ${notification.ref_id.name} contigo',

  EXPLORER_SHOWALL: 'Mostrar Todo',
  EXPLORER_TRANSPORTATION: 'Transporte',
  EXPLORER_HOME: 'Home',
  EXPLORER_AGRICULTURE: 'Agricultura',
  EXPLORER_ENERGY: 'Energía',
  EXPLORER_INDUSTRIAL: 'Industrial',
  EXPLORER_ALREADYADDED: 'Ya agregado',
  EXPLORER_BY: 'Por',
  EXPLORER_FILTERCATEGORY: 'Filtrar por categoría',
  EXPLORER_SEARCHFORMODEL: 'Busque por modelo, marca o aplicación...',
  EXPLORER_CANCEL: 'Cancelar',
  EPLORER_COMPATIBLE: 'Dispositivos Compatibles:',
  EXPLORER_HOWTOALERT: 'Cómo Instalar',
  EXPLORER_HOWTOINSTALL: '¿Cómo instalar esta aplicación?',
  EXPLORER_ADDAPPLI: 'Agregar aplicación',
  EXPLORER_CONFIGURE: 'Configurar',
  EXPLORER_DOWANTCONT: '¿Quieres continuar?',
  EXPLORER_THISACTIONWILL: 'Esta acción lo agregará a su lista de tableros',
  EXPLORER_NO: 'No',
  EXPLORER_YES: 'Si',
  EXPLORER_ENTERPIN: 'Esto requiere un código PIN. Ingrese el código proporcionado por el creador.',
  EXPLORER_ENTERCODE: 'Ingrese el código requerido...',
  EXPLORER_ADD: 'Añadir',
  EXPLORER_OOPS: 'Oops, algo salió mal',
  EXPLORER_BACK: 'Atrás',
  EXPLORER_DONE: '¡Hecho!',
  EXPLORER_YOUWILLRECEIVE: 'Recibirás una notificación cuando esté disponible en tu cuenta. No te preocupes, solo demorará unos segundos.',
  EXPLORER_BACKTOEXPLORE: 'Volver a explorar',
  EXPLORER_LOADING: 'Estamos trabajando en ello...',

  DASHBOARD_SHARE: 'Compartir',
  DASHBOARD_SHARE_ONEHOUR: 'Compartir por una hora',
  DASHBOARD_SHARE_ENDDAY: 'Compartir hasta el final del día',
  DASHBOARD_SHARE_INDEF: 'Compartir Indefinidamente',
  DASHBOARD_SHARE_CANCEL: 'Cancelar',
  DASHBOARD_SHARE_EMAIL: 'Ingrese el e-mail del usuario',
  DASHBOARD_SHARE_INVITE: 'Invitar',
  DASHBOARD_SHARE_ALLOWOTHERS: 'Permitir que el usuario comparta con otros?',
  DASHBOARD_SHARE_NO: 'No',
  DASHBOARD_SHARE_YES: 'Si',
  DASHBOARD_SHARE_INVEMAIL: 'Estructura de email no válida',
  DASHBOARD_SHARE_TRYA: 'Inténtalo de nuevo',
  DASHBOARD_SHARE_YOUSHARE: 'Compartió un tablero con una fecha de vencimiento que es mayor que la fecha de vencimiento del compartido que se hizo para usted. Compartido para:',
  DASHBOARD_SHARE_WILLEXP: 'expirará en: $0$',
  DASHBOARD_SHARE_OK: 'OK',
  DASHBOARD_SHARE_SHARESUCESS: 'Compartir exitoso',
  DASHBOARD_SHARE_FAIL: 'Compartir fallido',
  DASHBOARD_SHARE_USERINVITED: 'El usuario ha sido invitado a acceder a este tablero.',
  DASHBOARD_SHARE_NOTALLOWED: 'No tienes derechos para compartir este tablero. Pide a $0$ para enviarlo nuevamente con autorización para que lo compartas con otros',
  DASHBOARD_SHARE_SHAREDASH: 'Comparta este tablero en tiempo real en privado',

  DASHBOARDINFO_REMOVEDASH: '¿Eliminar este tablero?',
  DASHBOARDINFO_ACTIONREMOVEDESC: 'Esta acción también lo eliminará de la lista de todas las personas con las que compartió.',
  DASHBOARDINFO_NO: 'No',
  DASHBOARDINFO_YES: 'Si',
  DASHBOARDINFO_DASHREMOVED: 'Tablero eliminado con éxito',
  DASHBOARDINFO_YOUACCESSREMOVED: 'Su acceso a este tablero ha sido eliminado.',
  DASHBOARDINFO_OK: 'OK',
  DASHBOARDINFO_TRYA: 'Inténtalo de nuevo',
  DASHBOARDINFO_INDEF: 'Indefinidamente',
  DASHBOARDINFO_SHAREBY: 'Compartido por:',
  DASHBOARDINFO_YOUOWNER: 'Tú eres el dueño',
  DASHBOARDINFO_SHAREEXPAT: 'Compartir caduca el:',
  DASHBOARDINFO_REMOVETDASH: 'Eliminar este tablero',
  DASHBOARDINFO_SHARETHISDASH: 'Compartir este tablero',
  DASHBOARDINFO_SHARETHISDASHDESC: 'Compartir permite que otros accedan a este tablero en tiempo real durante el período que defina. Puede permitir que los usuarios compartan este tablero con otros.',

  DASHBOARDSHAREPRIV_STOPSHARE: 'Dejar de compartir con este usuario?',
  DASHBOARDSHAREPRIV_STOPSHAREDESC: 'Esto también eliminará compartir con todos los usuarios invitados por este usuario.',
  DASHBOARDSHAREPRIV_NO: 'No',
  DASHBOARDSHAREPRIV_YES: 'Si',
  DASHBOARDSHAREPRIV_SHARESUCCESS: 'Compartir eliminado correctamente',
  DASHBOARDSHAREPRIV_NOLONGERACCESS: 'El usuario ya no puede acceder a este tablero.',
  DASHBOARDSHAREPRIV_OK: 'OK',
  DASHBOARDSHAREPRIV_ERRORSHARE: 'Eliminar compartir falló',
  DASHBOARDSHAREPRIV_TRYA: 'Inténtalo de nuevo',
  DASHBOARDSHAREPRIV_INDEF: 'Indefinidamente',
  DASHBOARDSHAREPRIV_USERNOACC: 'El usuario aún no tiene una cuenta',
  DASHBOARDSHAREPRIV_ACCEPTED: 'Aceptado',
  DASHBOARDSHAREPRIV_PENDING: 'Pendiente',
  DASHBOARDSHAREPRIV_INVITSTA: 'Estado de la invitación:',
  DASHBOARDSHAREPRIV_SHAREBY: 'Compartido por:',
  DASHBOARDSHAREPRIV_USERCANOTHERS: 'El usuario puede compartir con otros:',
  DASHBOARDSHAREPRIV_SHAREEXPIRE: 'Compartir con este usuario caduca el:',
  DASHBOARDSHAREPRIV_SHARENOW: 'Compartir este tablero ahora',
  DASHBOARDSHAREPRIV_NORIGHTS: 'No tienes derechos para compartir este tablero',
  DASHBOARDSHAREPRIV_LISTDOESNTHTHERS: 'Esta lista no incluye tableros que otros usuarios hayan eliminado o que hayan expirado.',

  APPLICATION_REMOVEAPPQ: 'Eliminar la aplicación?',
  APPLICATION_REMOVEAPPDESC: 'Esta acción eliminará la aplicación por completo.',
  APPLICATION_CANCEL: 'Cancelar',
  APPLICATION_REMOVE: 'Eliminar',
  APPLICATION_CREATED: 'Creado por:',
  APPLICATION_VERSION: 'Versión:',
  APPLICATION_REMOVEAPP: 'Eliminar Aplicación',
  APPLICATION_DEVICES: 'Dispositivos',

  APPLICATION_DEVICES_REMOVEQ: '¿Eliminar dispositivo?',
  APPLICATION_DEVICES_REMOVEDESC: 'Esta acción eliminará el dispositivo por completo.',
  APPLICATION_DEVICES_CANCEL: 'Cancelar',
  APPLICATION_DEVICES_REMOVE: 'Eliminar',
  APPLICATION_DEVICES_DELETE: 'Borrar',
  APPLICATION_DEVICES_NONAME: 'Sin nombre',
  APPLICATION_DEVICES_ADDD: 'Añadir Dispositivo',
  APPLICATION_DEVICES_APPNOTREQ: 'Esta aplicación no requiere dispositivos.',

  APPLICATION_NDEVICES_SELECTD: 'Seleccionar Dispositivo',
  APPLICATION_NDEVICES_HOWINT: 'Cómo instalar',
  APPLICATION_NDEVICES_HOWQ: '¿Cómo instalar esta aplicación?',
  APPLICATION_NDEVICES_SELECTDAPPL: 'Seleccione el tipo de dispositivo de esta aplicación',
  APPLICATION_NDEVICES_APPNAME: 'Nombre de la aplicación:',
  APPLICATION_NDEVICES_DEVTYPE: 'Tipo de dispositivo:',
  APPLICATION_NDEVICES_NAME: 'Nombre:',
  APPLICATION_NDEVICES_ENAME: 'Ingrese el nombre...',
  APPLICATION_NDEVICES_SERIAL: 'Número de serie:',
  APPLICATION_NDEVICES_ESERIAL: 'Ingrese el número de serie...',
  APPLICATION_NDEVICES_VERIFCODE: 'Código de verificación:',
  APPLICATION_NDEVICES_EVERIFCODE: 'Introduzca el código de verificación...',
  APPLICATION_NDEVICES_ADDD: 'Añadir dispositivo',
};
