module.exports = {
  LANDING_PAGE_GET_STARTED: 'Get started',
  LANDING_PAGE_BUTTON_GET_STARTED: 'Click here to get started!',
  COLD_CHAIN_GET_STARTED_DESCRIPTION: 'Automotive companies of all types and sizes, from global automakers to startups rely on AWS. Contact our experts and start your own AWS Cloud journey today.',
  COLD_CHAIN_SUBTITLE: 'TagoIO offers many sensors to monitor containers, boxes and different kinds of refrigerators in your supply chain',
  COLD_CHAIN_CONTENT_1_TITLE: '',
  COLD_CHAIN_CONTENT_1_DESCRIPTION: 'Aplique sensores inteligentes para monitorar contêineres, caixas e diferentes tipos de refrigeradores em sua cadeia de suprimentos. Com mais informações disponíveis, sua empresa poderá reduzir a perda de carga e os custos operacionais. Melhore a satisfação do cliente ou cumpra com o ambiente regulatório, monitorando temperatura, umidade e outras variáveis em tempo real - combine tudo isso com relatórios e notificações que indicarão quando determinada condição é cumprida ou quando trailers / caminhões chegam ou saem de certas áreas. Todos os dados do sensor podem ser automaticamente combinados ou transferidos para o back-end de negócios usando nossa poderosa API (Application Programming Interface).',
  COLD_CHAIN_CONTENT_2_TITLE: 'Mobile',
  COLD_CHAIN_CONTENT_2_DESCRIPTION: 'TagoIO offers many sensors to monitor containers, boxes and different kinds of refrigerators in your supply chain',
  COLD_CHAIN_CONTENT_3_TITLE: 'Benefits',
  COLD_CHAIN_CONTENT_4_TITLE: 'Customers Stories',
  COLD_CHAIN_GET_STARTED_DESCRITPION: 'Automotive companies of all types and sizes, from global automakers to startups rely on AWS. Contact our experts and start your own AWS Cloud journey today.',
  COLD_CHAIN_BENEFIT_1_TITLE: 'Technologies for Innovation',
  COLD_CHAIN_BENEFIT_1_DESCRIPTION: 'AWS wide array of services for automotive applications, including IoT, AI and machine learning, allow you to develop advanced connected experiences and innovative  ways to engage with your customers digital lifestyle.',
  COLD_CHAIN_BENEFIT_2_TITLE: 'Agility & Scalability',
  COLD_CHAIN_BENEFIT_2_DESCRIPTION: 'AWS wide array of services for automotive applications, including IoT, AI and machine learning, allow you to develop advanced connected experiences and innovative  ways to engage with your customers digital lifestyle.',
  COLD_CHAIN_BENEFIT_3_TITLE: 'Agility & Scalability',
  COLD_CHAIN_BENEFIT_3_DESCRIPTION: 'AWS wide array of services for automotive applications, including IoT, AI and machine learning, allow you to develop advanced connected experiences and innovative  ways to engage with your customers digital lifestyle.',
  COLD_CHAIN_BENEFIT_4_TITLE: 'Agility & Scalability',
  COLD_CHAIN_BENEFIT_4_DESCRIPTION: 'AWS wide array of services for automotive applications, including IoT, AI and machine learning, allow you to develop advanced connected experiences and innovative  ways to engage with your customers digital lifestyle.',
  COLD_CHAIN_CUSTOMER_STORY_1_TITLE: 'Depois de compararmos várias plataformas de IoT, optamos pela Tago devido aos seus fortes recursos de gerenciamento de dispositivos e dados, e a solução intuitiva e fácil de usar para criação de painéis. Ao executar nossas análises no Tago, conseguimos fornecer uma solução robusta.',
  COLD_CHAIN_CUSTOMER_STORY_1_AUTHOR: '<b>Julio Almeida</b>, <small>SW Dev - Agrusdata<small>',
  COLD_CHAIN_CUSTOMER_STORY_2_TITLE: 'TagoIO ajudou tremendamente no desenvolvimento de nossos produtos. Sua versatilidade e facilidade de uso nos ajudaram a atingir as metas de nossos produtos com muito mais rapidez do que outras alternativas.',
  COLD_CHAIN_CUSTOMER_STORY_2_AUTHOR: '<b>Eric Hoog</b>, <small>CEO - Zquel<small>',
  COLD_CHAIN_CUSTOMER_STORY_3_TITLE: 'A Tago tem sido fundamental no fornecimento de elementos críticos para nossa plataforma de Monitoramento/Controle Remoto Cellio IoT. A capacidade de costumizar a hospedagem de dados, painéis, aplicativos móveis, alertas e notificações permitiu o desenvolvimento de uma solução completa e pronta para uso, o que provou ser extremamente flexível, desejável e valiosa para nossos clientes corporativos.',
  COLD_CHAIN_CUSTOMER_STORY_3_AUTHOR: '<b>Brent Ward</b>, <small>VP. Device Solutions Inc.<small>',
};
