module.exports = {
  LANDING_PAGE_GET_STARTED: 'Get started',
  LANDING_PAGE_BUTTON_GET_STARTED: 'Click here to get started!',
  COLD_CHAIN_GET_STARTED_DESCRIPTION: 'Automotive companies of all types and sizes, from global automakers to startups rely on AWS. Contact our experts and start your own AWS Cloud journey today.',
  COLD_CHAIN_SUBTITLE: 'TagoIO offers integration with a wide range of sensors to monitor containers, boxes and different kinds of refrigerators in your supply chain',
  COLD_CHAIN_CONTENT_1_TITLE: '',
  COLD_CHAIN_CONTENT_1_DESCRIPTION: 'Apply smart sensors to monitor containers, boxes, and different types of refrigerators in your supply chain. By having more information on hand, your business will be able to reduce cargo loss and operating costs. Improve customer satisfaction or comply with regulatory environment by monitoring temperature, humidity and other variables all in real-time – combine all this with reports and notifications that will indicate when a certain condition is met or when trailers/trucks arrive or leave certain areas. All sensor data can be automatically combined or transferred to the business back-end by using our powerful API (Application Programming Interface)..',
  COLD_CHAIN_CONTENT_2_TITLE: 'Mobile',
  COLD_CHAIN_CONTENT_2_DESCRIPTION: 'TagoIO offers many sensors to monitor containers, boxes and different kinds of refrigerators in your supply chain',
  COLD_CHAIN_CONTENT_3_TITLE: 'Benefits',
  COLD_CHAIN_CONTENT_4_TITLE: 'Customers Stories',
  COLD_CHAIN_GET_STARTED_DESCRITPION: 'Automotive companies of all types and sizes, from global automakers to startups rely on AWS. Contact our experts and start your own AWS Cloud journey today.',
  COLD_CHAIN_BENEFIT_1_TITLE: 'Integrity of Goods',
  COLD_CHAIN_BENEFIT_1_DESCRIPTION: 'Executing TagoIO real-time scripts to analyze data from sensor 24/7, your staff and customers will receive precise information during each step of the process for any given condition.',
  COLD_CHAIN_BENEFIT_2_TITLE: 'Regulation Compliance',
  COLD_CHAIN_BENEFIT_2_DESCRIPTION: 'Reliable generation of easy to read reports that are customized to meet customers requirements and individual industry regulations.',
  COLD_CHAIN_BENEFIT_3_TITLE: 'Operation Optimization',
  COLD_CHAIN_BENEFIT_3_DESCRIPTION: 'By combining data from different sensors is possible to quicky adapt the system response based on customer demand, transit status, and environmental conditions.',
  COLD_CHAIN_BENEFIT_4_TITLE: 'Easy Integration',
  COLD_CHAIN_BENEFIT_4_DESCRIPTION: 'TagoIO offers several interfaces to connect your application to databases, webservices, and a high number of services like ERP, CRM, and others.',
  COLD_CHAIN_CUSTOMER_STORY_1_TITLE: 'The use of TagoIO platform was essential to allow us to successfully deploy our Cold Chain solution to an important Foold & Beverage market leader in Latin America',
  COLD_CHAIN_CUSTOMER_STORY_1_AUTHOR: '<b>Joe Doe</b>, <small>Business Developer PwC <small>',
  COLD_CHAIN_CUSTOMER_STORY_2_TITLE: 'Built on TagoIO, our Cellio Cold Storage Monitoring system based on LoRa technology eliminated product loss and reduced labor cost for monitoring cold storage coolers and freezers.',
  COLD_CHAIN_CUSTOMER_STORY_2_AUTHOR: '<b>Bob Witter </b>, <small>CEO - Device Solutions Inc<small>',
  COLD_CHAIN_CUSTOMER_STORY_3_TITLE: '',
  COLD_CHAIN_CUSTOMER_STORY_3_AUTHOR: '<b> starte up? </b>, <small>VP. Device Solutions Inc<small>',
  ENERGY_GET_STARTED_DESCRIPTION: 'Companies of all types and sizes, from global players to startups can rely on TagoIO.',
  ENERGY_SUBTITLE: 'TagoIO offers many sensors to monitor containers, boxes and different kinds of refrigerators in your supply chain',
  ENERGY_CONTENT_1_TITLE: '',
  ENERGY_CONTENT_1_DESCRIPTION: 'Aplique sensores inteligentes para monitorar contêineres, caixas e diferentes tipos de refrigeradores em sua cadeia de suprimentos. Com mais informações disponíveis, sua empresa poderá reduzir a perda de carga e os custos operacionais. Melhore a satisfação do cliente ou cumpra com o ambiente regulatório, monitorando temperatura, umidade e outras variáveis em tempo real - combine tudo isso com relatórios e notificações que indicarão quando determinada condição é cumprida ou quando trailers / caminhões chegam ou saem de certas áreas. Todos os dados do sensor podem ser automaticamente combinados ou transferidos para o back-end de negócios usando nossa poderosa API (Application Programming Interface).',
  ENERGY_CONTENT_2_TITLE: 'Mobile',
  ENERGY_CONTENT_2_DESCRIPTION: 'TagoIO offers many sensors to monitor containers, boxes and different kinds of refrigerators in your supply chain',
  ENERGY_CONTENT_3_TITLE: 'Benefits',
  ENERGY_CONTENT_4_TITLE: 'Customers Stories',
  ENERGY_GET_STARTED_DESCRITPION: 'Automotive companies of all types and sizes, from global automakers to startups rely on AWS. Contact our experts and start your own AWS Cloud journey today.',
  ENERGY_BENEFIT_1_TITLE: 'Technologies for Innovation',
  ENERGY_BENEFIT_1_DESCRIPTION: 'AWS wide array of services for automotive applications,\n    including IoT, AI and machine learning, allow you to\n    develop advanced connected experiences and innovative \n    ways to engage with your customers digital lifestyle.',
  ENERGY_BENEFIT_2_TITLE: 'Agility & Scalability',
  ENERGY_BENEFIT_2_DESCRIPTION: 'AWS wide array of services for automotive applications,\n    including IoT, AI and machine learning, allow you to\n    develop advanced connected experiences and innovative \n    ways to engage with your customers digital lifestyle.',
  ENERGY_BENEFIT_3_TITLE: 'Agility & Scalability',
  ENERGY_BENEFIT_3_DESCRIPTION: 'AWS wide array of services for automotive applications,\n    including IoT, AI and machine learning, allow you to\n    develop advanced connected experiences and innovative \n    ways to engage with your customers digital lifestyle.',
  ENERGY_BENEFIT_4_TITLE: 'Agility & Scalability',
  ENERGY_BENEFIT_4_DESCRIPTION: 'AWS wide array of services for automotive applications,\n    including IoT, AI and machine learning, allow you to\n    develop advanced connected experiences and innovative \n    ways to engage with your customers digital lifestyle.',
  ENERGY_CUSTOMER_STORY_1_TITLE: 'Depois de compararmos várias plataformas de IoT, optamos pela Tago devido aos seus fortes recursos de gerenciamento de dispositivos e dados, e a solução intuitiva e fácil de usar para criação de painéis. Ao executar nossas análises no Tago, conseguimos fornecer uma solução robusta.',
  ENERGY_CUSTOMER_STORY_1_AUTHOR: '<b>Julio Almeida</b>, <small>SW Dev - Agrusdata<small>',
  ENERGY_CUSTOMER_STORY_2_TITLE: 'TagoIO ajudou tremendamente no desenvolvimento de nossos produtos. Sua versatilidade e facilidade de uso nos ajudaram a atingir as metas de nossos produtos com muito mais rapidez do que outras alternativas.',
  ENERGY_CUSTOMER_STORY_2_AUTHOR: '<b>Eric Hoog</b>, <small>CEO - Zquel<small>',
  ENERGY_CUSTOMER_STORY_3_TITLE: 'A Tago tem sido fundamental no fornecimento de elementos críticos para nossa plataforma de Monitoramento/Controle Remoto Cellio IoT. A capacidade de costumizar a hospedagem de dados, painéis, aplicativos móveis, alertas e notificações permitiu o desenvolvimento de uma solução completa e pronta para uso, o que provou ser extremamente flexível, desejável e valiosa para nossos clientes corporativos.',
  ENERGY_CUSTOMER_STORY_3_AUTHOR: '<b>Brent Ward</b>, <small>VP. Device Solutions Inc<small>',
  DEVICES_DESCRIPTION: 'TagoIO is integrated with most network providers and sensors so that it is easy for you to build your IoT solution. Just select your device, add the credentials and click on install.',
};
