module.exports = {
  CREATE_ACCOUNT: 'create account',
  ENTER_YOUR_EMAIL_ADDRESS_RESEND_YOUR_CONFIRMATION: 'Enter your email address to resend your confirmation. You may need to check your spam folder.',
  ENTER_YOUR_EMAIL_ADDRESS_RESEND_YOUR_CONFIRMATION_WL: 'Enter your email address to resend your confirmation.',
  ENTER_YOUR_EMAIL_ADDRESS_RESET_YOUR_PASSWORD: 'Enter your email address to reset your password. You may need to check your spam folder.',
  ENTER_YOUR_EMAIL_ADDRESS_RESET_YOUR_PASSWORD_WL: 'Enter your email address to reset your password.',
  FORGOT_YOUR_PASSWORD: 'Forgot your password?',
  RESEND_CONFIRMATION_EMAIL: 'Resend confirmation email',
  RESEND_EMAIL: 'Resend email',
  RESET_PASSWORD: 'Reset password',
  SELECT_PROFILE: 'Select a profile shared with you',
  SIGN_IN: 'Sign in',
  VERIFY_YOU_HAVE_VERIFIED_YOUR_ACCOUNT: 'Verify that you have verified your account',
  SELECT_YOUR_PROFILE: 'Select one of your profiles',
};
