module.exports = {
  ACCEPT: 'Accept',
  ACCEPTED: 'Accepted',
  ACCOUNT: 'account',
  ALL: 'All',
  APPLICATION: 'Application',
  APPLICATIONS: 'Applications',
  APRIL: 'April',
  ARE_YOU_SURE: 'Are you sure',
  AUDIT_LOG: 'Audit log',
  AUGUST: 'August',
  BACK: 'Back',
  CANCEL: 'Cancel',
  CLEAR: 'Clear',
  CLICK: 'Click',
  CLOSE: 'Close',
  COLLAPSE: 'Collapse',
  COMMA: 'Comma',
  COMPANY: 'Company',
  CUSTOM: 'Custom',
  DAY: 'Day',
  DASHBOARD: 'Dashboard',
  DASHBOARDS: 'Dashboards',
  DECEMBER: 'December',
  DECLINE: 'Decline',
  DECLINED: 'Declined',
  DEVELOPER: 'Developer',
  DEVICES: 'Devices',
  DOT: 'Dot',
  EMAIL: 'E-mail',
  END_DATE: 'End date',
  ENTER_EMAIL: 'enter the email address',
  ENTER_YOUR_EMAIL: 'enter your email',
  EXPAND: 'Expand',
  FEBRUARY: 'February',
  FILTER: 'filter',
  FINISH: 'Finish',
  FREE: 'free',
  FRIDAY: 'Friday',
  FROM: 'From',
  GENERAL_INFORMATION: 'General information',
  GO_TO: 'Go to',
  HERE: 'here',
  HOUR: 'Hour',
  IGNORE: 'Ignore',
  INDEFINITELY: 'Indefinitely',
  INFORMATION: 'Information',
  INVITE: 'Invite',
  JANUARY: 'January',
  JULY: 'July',
  JUNE: 'June',
  LANGUAGE: 'Language',
  LOCATION: 'location',
  MARCH: 'March',
  MAY: 'May',
  MINUTE: 'Minute',
  MONDAY: 'Monday',
  MONTH: 'Month',
  MORE: 'More',
  MY_ACCOUNT: 'My account',
  MY_BILLING: 'My billing',
  NAME: 'Name',
  NEXT: 'Next',
  NO: 'No',
  NOTIFICATIONS: 'Notifications',
  NO_OPTIONS: 'No options',
  NOVEMBER: 'November',
  OCTOBER: 'October',
  OF_PAGINATION: 'Of',
  OR: 'or',
  REFUSED: 'Refused',
  PASSWORD: 'password',
  PENDING: 'Pending',
  PLAN: 'Plan',
  PHONE: 'Phone',
  PLEASE_CHECK_YOUR_EMAIL: 'Please, check your email',
  PLEASE_ENTER_YOUR_EMAIL: 'Please, enter your email address',
  PLEASE_ENTER_REQUIRED_FIELDS: 'Please enter required fields',
  PREVIOUS: 'Previous',
  SATURDAY: 'Saturday',
  SAVE: 'Save',
  SECOND: 'Second',
  SELECT_ALL: 'Select all',
  SELECT_FILE: 'Select a file',
  SELECT_VALUE: 'select a value',
  SEPTEMBER: 'September',
  SERVICES: 'Services',
  SHARE: 'Share',
  SIGN_OUT: 'Sign out',
  SOUND: 'Sound',
  START_DATE: 'Start Date',
  SUBMIT: 'Send',
  SUNDAY: 'Sunday',
  TIMEZONE: 'Time zone',
  THIS_FIELD_IS_REQUIRED: 'This field is required',
  THIS_FIELD_REQUIRES_AT_LEAST_THREE_CHARACTERS: 'This field requires at least 3 characters',
  THURSDAY: 'Thursday',
  TUESDAY: 'Tuesday',
  UNDO: 'Undo',
  VALUE: 'Value',
  VARIABLE: 'Variable',
  WEDNESDAY: 'Wednesday',
  WEEK: 'week',
  YEAR: 'year',
  YES: 'Yes',
  CONFIGURATION: 'Configure',
  DASHBOARDS_SHARE_DASHBOARD: 'Share',
  DUPLICATE_DASHBOARD: 'Duplicate',
  BUILD_TEMPLATE: 'Distribute',
  DASHBOARDS_DELETE_DASHBOARD: 'Remove',
  DISMISS: 'Dismiss',
  NOT_A_DEVELOPER: 'Not a developer?',
  A_DEVELOPER: 'Are you a Developer? Click here',
  NOTIFICATION: 'Notification',
  SHARE_DASHBOARDS: 'Share dashboards',
  WELCOME: 'Hey, how are you',
  REALTIME: 'Realtime',
  CONNECTED: 'Connected',
  DISCONNECTED: 'Disconnected',
  WELCOME_DEVELOPER: 'Welcome Developer',
  CHANGE_MY_SETTINGS: 'Change my settings',
  EXPLORE: 'Explore',
  CLICK_HERE: 'Click here',
  IGNORED: 'Ignored',
  MAP: 'Map',
  SATELLITE: 'Satellite',
  NEW_HERE: 'New here?',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
};
