module.exports = {
  ACCEPT: 'Accept',
  ACCEPTED: 'Accepted',
  ACCOUNT: 'account',
  ALL: 'All',
  APPLICATION: 'Application',
  APPLICATIONS: 'Applications',
  APRIL: 'April',
  ARE_YOU_SURE: 'Are you sure',
  AUDIT_LOG: 'Audit log',
  AUGUST: 'August',
  BACK: 'Back',
  BACKGROUND_IMAGE: 'Background Image',
  CANCEL: 'Cancel',
  CLEAR: 'Clear',
  CLICK: 'Click',
  CLOSE: 'Close',
  COLLAPSE: 'Collapse',
  COMMA: 'Comma',
  SEMICOLON: 'Semicolon',
  COMPANY: 'Company',
  CUSTOM: 'Custom',
  DATE_FORMAT: 'Date format',
  DAY: 'Day',
  DASHBOARD: 'Dashboard',
  DASHBOARDS: 'Dashboards',
  DECEMBER: 'December',
  DECLINE: 'Decline',
  DELETE: 'Delete',
  DECLINED: 'Declined',
  DEVELOPER: 'Developer',
  DEVICES: 'Devices',
  DOT: 'Dot',
  EMAIL: 'E-mail',
  END_DATE: 'End date',
  ENTER_EMAIL: 'enter the email address',
  ENTER_LABEL: 'enter the label',
  ENTER_EMBED_URL: 'enter the embed url',
  ENTER_IMAGE_URL: 'enter the url of image',
  ENTER_NAME: 'enter the name',
  ENTER_YOUR_EMAIL: 'enter your email',
  EXPAND: 'Expand',
  FEBRUARY: 'February',
  FILTER: 'filter',
  FINISH: 'Finish',
  FREE: 'free',
  FRIDAY: 'Friday',
  FROM: 'From',
  GENERAL_INFORMATION: 'General information',
  GO_TO: 'Go to',
  HERE: 'here',
  HOUR: 'Hour',
  IGNORE: 'Ignore',
  IMAGE: 'Image',
  INDEFINITELY: 'Indefinitely',
  INFORMATION: 'Information',
  INVITE: 'Invite',
  JANUARY: 'January',
  JULY: 'July',
  JUNE: 'June',
  LANGUAGE: 'Language',
  LOCATION: 'location',
  MARCH: 'March',
  MAY: 'May',
  MINUTE: 'Minute',
  MONDAY: 'Monday',
  MONTH: 'Month',
  MORE: 'More',
  MY_ACCOUNT: 'My account',
  MY_BILLING: 'My billing',
  NAME: 'Name',
  NEXT: 'Next',
  NO: 'No',
  NOTIFICATIONS: 'Notifications',
  NO_OPTIONS: 'No options',
  NOVEMBER: 'November',
  OCTOBER: 'October',
  OF_PAGINATION: 'Of',
  OR: 'or',
  REFUSED: 'Refused',
  PASSWORD: 'password',
  PENDING: 'Pending',
  PLAN: 'Plan',
  PHONE: 'Phone',
  PLEASE_CHECK_YOUR_EMAIL: 'Please, check your email',
  PLEASE_ENTER_YOUR_EMAIL: 'Please, enter your email address',
  PLEASE_ENTER_REQUIRED_FIELDS: 'Please enter required fields',
  PREVIOUS: 'Previous',
  SATURDAY: 'Saturday',
  SAVE: 'Save',
  SECOND: 'Second',
  SELECT_ALL: 'Select all',
  SELECT_FILE: 'Select a file',
  SELECT_VALUE: 'select a value',
  SELECT_IMAGE: 'select a image',
  SEPTEMBER: 'September',
  SERVICES: 'Services',
  SHARE: 'Share',
  SIGN_OUT: 'Sign out',
  SOUND: 'Sound',
  START_DATE: 'Start Date',
  SUBMIT: 'Send',
  SUNDAY: 'Sunday',
  TIME_FORMAT: 'Time format',
  TIMEZONE: 'Time zone',
  THIS_FIELD_IS_REQUIRED: 'This field is required',
  THIS_FIELD_REQUIRES_AT_LEAST_THREE_CHARACTERS: 'This field requires at least 3 characters',
  THIS_FIELD_REQUIRES_VALID_HTTPS_URL: 'This field requires a valid HTTPS url',
  THURSDAY: 'Thursday',
  TUESDAY: 'Tuesday',
  UNDO: 'Undo',
  VALUE: 'Value',
  VARIABLE: 'Variable',
  WEDNESDAY: 'Wednesday',
  WEEK: 'week',
  YEAR: 'year',
  YES: 'Yes',
  CONFIGURATION: 'Configure',
  DASHBOARDS_SHARE_DASHBOARD: 'Share',
  DUPLICATE_DASHBOARD: 'Duplicate',
  BUILD_TEMPLATE: 'Distribute',
  DASHBOARDS_DELETE_DASHBOARD: 'Remove',
  DISMISS: 'Dismiss',
  NOT_A_DEVELOPER: 'Not a developer?',
  A_DEVELOPER: 'Are you a Developer? Click here',
  NOTIFICATION: 'Notification',
  SHARE_DASHBOARDS: 'Share dashboards',
  WELCOME: 'Hey, how are you',
  REALTIME: 'Realtime',
  CONNECTED: 'Connected',
  DISCONNECTED: 'Disconnected',
  WELCOME_DEVELOPER: 'Welcome Developer',
  CHANGE_MY_SETTINGS: 'Change my settings',
  EXPLORE: 'Explore',
  CLICK_HERE: 'Click here',
  IGNORED: 'Ignored',
  MAP: 'Map',
  SATELLITE: 'Satellite',
  NEW_HERE: 'New here?',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
  PUBLIC_DASHBOARD: 'Public Dashboard',
  UNLIMITED: 'Unlimited',
  ADD_PROFILES: 'Add Profiles',
  USER_MANAGEMENT: 'User Management',
  ACCESS_MANAGEMENT: 'Access Management',

  CONFIRM_YOUR_E_MAIL_BEFORE_PROCEEDING: 'Confirm your e-mail before proceeding.',
  ACCOUNT_CREATION_HAS_BEEN_SUBMITTED: 'Account creation has been submitted',
  YOUR_ACCOUNT_WAS_CREATED: 'Your account was created!',
  YOU_WILL_BE_NOTIFIED_WHEN_IT_IS_ACTIVATED: 'You will be notified when it is activated.',

  NO_NOTIFICATIONS: 'No notifications',
  NO_DASHBOARDS: 'No dashboards',
  NO_CONTENT: 'No content',

  MAP_BASIC: 'Map Basic',
  MAP_DARK: 'Map Dark',
  MAP_LIGHT: 'Map Light',

  AGREE_WITH: "I agree with the",
  DYNAMIC_TABLE_ROW_DELETED: "The row was successfully deleted.",
  DYNAMIC_TABLE_ROW_EDITED: "Row successfully edited!",
  DYNAMIC_TABLE_SEARCH: "search",
  LAST_UPDATE_AT: "Last update",
  PRESET_CALENDAR_CUSTOM: "Custom",
  PRESET_CALENDAR_DAY: "Day",
  PRESET_CALENDAR_MINUTE: "Minute",
  PRESET_CALENDAR_MONTH: "Month",
  PRESET_CALENDAR_SECOND: "Second",
  PRESET_CALENDAR_WEEK: "Week",
  PRESET_CALENDAR_YEAR: "Year",
  PRESET_CALENDAR_FOREVER: "Forever",

  EXPORT_CSV_DOWNLOAD: "Download file",
  EXPORT_CSV_MODAL_TITLE: "Export CSV",
  EXPORT_CSV_SELECT_SEPARATOR: "Select the separator for the CSV file",
  SEMICOLON: "Semicolon",

  NOTIFICATION_CLICK_ON: "Click on",
  NOTIFICATION_CONFIRMATION_READ_ALL_CONFIRM: "Yes, mark all notifications as read",
  NOTIFICATION_CONFIRMATION_READ_ALL_DESC:
    "Do you really want to mark all notifications as read? This may take a while depending on the amount of notifications.",
  NOTIFICATION_DELETE: "Delete notification",
  NOTIFICATION_FILTERED_BY: "Filtered by:",
  NOTIFICATION_MARK_ALL_AS_READ: "Mark all notifications as read",
  NOTIFICATION_MARK_AS_READ: "Mark as read",
  NOTIFICATION_MARK_AS_UNREAD: "Mark as unread",
  NOTIFICATION_NONE: "You have no notifications",
  NOTIFICATION_NOT_FOUND: "No Notifications found",
  NOTIFICATION_SHOW_ALL: "Show all notifications",
  NOTIFICATION_SHOW_UNREAD: "Show unread notifications",
  NOTIFICATION_TO_SEE_ALL: "to see all notifications.",
  NOTIFICATION_UNREAD: "Unread",
  NOTIFICATION_YOUVE_READ_ALL: "You've read them all!",

  DELETE_ACCOUNT: "Delete account",
  ARE_YOU_SURE_DELETE_ACCOUNT: "Are you sure? Deleting an account is an irreversible action.",
  CONFIRM_DELETE_ACCOUNT: "Yes, delete my account",
  DELETE_ACCOUNT_MESSAGE: "A request to delete the account has been sent!",
  MOBILE_RUN_ACCOUNT_SETTINGS: "Account settings",
  MOBILE_RUN_DELETE_ACCOUNT: "Delete account",
  MOBILE_SETTINGS_DORELLY_DELETE_ACCOUNT: "Are you sure? Deleting an account is an irreversible action.",

  "2FA_AUTHENTICATION": "Two-Factor Authentication (2FA)",
  SECURITY_PREFERENCES: "Security Preferences",
  APP_AUTHENTICATOR: "App Authenticator",
  SMS: "SMS",
  "2FA_CONFIGURED": "Configured",
  "2FA_YOU_HAVE_ENABLED": "You have two-factor authentication enabled.",
  "2FA_APP_AUTHENTICATOR_TIP": "Your app will display an authentication code.",
  "2FA_6_DIGIT_CODE": "6-digit code",
  "2FA_CANT_ACCESS_DEVICE": "Can't access your two-factor device?",
  "2FA_CODE_INCORRECT": "The code you entered is incorrect",
  "2FA_ADD": "Add Two-Factor Authentication (2FA)",
  "2FA_INTRODUCTION":
    "Two-factor authentication (2FA) is an extra layer of security used when logging into websites or apps.",
  "2FA_INTRODUCTION_REINFORCEMENT":
    "After being configured, the only way for someone to sign into your account is if they know the password and have access to the authentication code.",
  "2FA_HOW_TO_APP_AUTHENTICATOR":
    "Use an application on your phone to get two-factor authentication codes when prompted. We recommend using cloud-based TOTP such as: 1Password, Microsoft Authenticator, Google Authenticator.",
  CONFIRM_THIS_ACTION_BY_PASSWORD: "Confirm this action by typing your password",
  PASSWORD_INCORRECT: "The password you entered is incorrect",
  "2FA_ENABLED_WARNING":
    "For security reasons, once two-factor authentication is enabled, if you lose your two-factor authentication credentials, the only way to recover them is by contacting support.",
  "2FA_APP_AUTHENTICATOR_CONFIG":
    "Scan the image below with the two-factor authentication app on your phone. If you can't use a QR code, enter the following text code instead:",
  "2FA_YOU_ARE_ENABLING": "You are enabling two-factor authentication",
  "2FA_ADD_METHOD": "Add authentication method",
  "2FA_SETTINGS_BEEN_SAVED":
    "Two-factor authenticator settings have been saved. If you have made other changes in your profile, make sure to click Save",
  "2FA_SENT_SMS": "We sent you an SMS with the authentication code to your phone",
  MAY_TAKE_A_MINUTE: "It can take up to 1 minute to arrive.",
  "2FA_HAVENT_RECEIVED_CODE": "Haven't received a code? Send one again.",
  "2FA_YOU_WILL_RECEIVE_SMS_FOR": "You are going to receive a SMS with the authentication code when prompted for:",
  COUNTRY_CODE: "Country code",
  PHONE_NUMBER: "Phone number",
  "2FA_PHONE_CHANGE": "This will change your account's phone information.",
  "2FA_WE_HAVE_SENT_YOU_CODE": "We've sent you a new code. If that still doesn't work, please contact support",
  "2FA_SENT_EMAIL": "We sent you an authentication code to your email.",
  "2FA_YOU_WILL_RECEIVE_EMAIL_FOR":
    "You are going to receive an e-mail with the authentication code when prompted for:",
  "2FA_REQUEST_NEW_CODE": "Request a new code",
  "2FA_ENDING_PHONE": "Phone ending with",
  "2FA_SENDING_EMAIL_TO": "Send e-mail to",
  "2FA_OR_TYPE_CODE_AGAIN": "Or type the code again",
  "2FA_TOO_MANY_REQUESTS": "You have made too many requests. E-mail and SMS have been temporarily disabled.",
  "2FA_REMOVE": "Remove Two-Factor Authentication (2FA)",
  "2FA_APP_AUTHENTICATOR_REMOVE": "You are going to remove your App Authenticator method.",
  "2FA_EMAIL_REMOVE": "You are going to remove your E-mail method.",
  "2FA_SMS_REMOVE": "You are going to remove your SMS method.",
  "2FA_REMOVE_MESSAGE": "After that, you will simply use your password to sign in.",
  PASSWORD_MIN_LENGTH: "Must contain the minimum length required",
  MUST_CONTAIN_SPECIAL_CHARACTERS: "Must contain special characters (@, !, &, …)",
  MUST_CONTAIN_MIX_LETTERS_NUMBERS: "Must contain a mix of letters and numbers",
  MUST_CONTAIN_UPPER_LOWER_CASE_CHARACTERS: "Must contain upper and lower case letters",
  STRONG_PASSWORD: "Great job. This is an excellent password",
};
