module.exports = {
  NOTIFICATIONS_FROM_INSTALL: 'Application installée avec succès',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'Nouvel utilisateur enregistré',
  NOTIFICATIONS_SEARCH: 'Rechercher des notifications',
  NOTIFICATIONS_FROM_USER_REGISTERED: '$0 a créé un compte sur Tago. L\'article que vous avez partagé est disponible pour qu\'il accepte.',
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: 'Oups... $0 est maintenant enregistr? sur Tago, mais quelque chose s\'est mal tourné avec le partage. Essayez de partager à nouveau',
  ONLY_UNREAD: 'seulement non lu',
  OTHER_USERS: 'autres utilisations',
  RESEND_EMAIL_CONFIRMATION: 'Renvoyer un courriel de confirmation',
  TAGO_SYSTEM: 'système de Tago',
  YOU_REALLY_WANT_EXIT: 'Voulez-vous vraiment sortir',
  YOUR_EMAIL_HASNT_BEEN_CONFIRMED: 'Votre email n’a pas encore été confirmé. Confirmez votre email pour utiliser toutes les fonctionnalités de TagoIO.',
  TEMPLATE_TAB_NAME: 'Distribute the template of this $0',
  TEMPLATE_TAB_DESCRIPTION: 'Send the generated URL to others so they can access your $0 through a customized install page.',
  TEMPLATE_TAB_LINK_DESCRIPTION: 'Create a link that contains the template of this $0. Share the link with anyone.',
  TEMPLATE_TAB_URL_PLACEHOLDER: 'build your template to generate an url',
  TEMPLATE_LAST_GENERATED_AT: 'Last generated at',
  CUSTOMIZE_TEMPLATE_TITLE: 'Customize the page',
  CUSTOMIZE_TEMPLATE_DESCRIPTION: 'Add a logo and an image that better represents your template.',
  CUSTOMIZE_TEMPLATE_DESCRIPTION2: 'Images will be shown when users access the page using the generated URL.',
  TEMPLATE_LABEL_TITLE: 'Title of the page',
  TEMPLATE_PLACEHOLDER_TITLE: 'The title of the page',
  TEMPLATE_LABEL_LOGO: 'Logo of the page',
  TEMPLATE_PLACEHOLDER_LOGO: 'https url of the logo',
  TEMPLATE_LABEL_MAIN_IMG: 'Main image of the page',
  TEMPLATE_PLACEHOLDER_MAIN_IMG: 'https url of the main image',
  TEMPLATE_ANALYSIS_SETUP_TITLE: 'If you use environment variables, describe each "variable value" here.',
  TEMPLATE_ANALYSIS_SETUP_DESCRIPTION: 'Whoever receives this analysis will use this information to configure the variable value',
  TEMPLATE_DASHBOARD_SETUP_TITLE: 'Enter a description for each device',
  TEMPLATE_DASHBOARD_SETUP_DESCRIPTION: 'This information will help the user to select the right device in his/her account. (e.g. GPS Calamp LMU3030, Generator GRX2000, …).',
  TEMPLATE_BUILD_TEMPLATE: 'Build Template',
  SETUP_LIST_DESCRIPTION_ANALYSIS: 'enter a description for this "variable value"',
  SETUP_LIST_DESCRIPTION_DASHBOARD: 'enter a detailed description for this device',
  COPIED: 'Copied',
  COPY: 'Copy',
  NOTIFICATION_PROFILE_SHARE: '$0 veut partager un profil avec vous',
  NOTIFICATION_BUCKET_SHARE: '$0 veut partager le seau $1 avec vous',
  NOTIFICATION_DASHBOARD_SHARE: '$0 veut partager le tableau de bord $1 avec vous',
  NEW_USER_RESENT_CONFIRMATION_EMAIL: 'Nous avons envoyé un courrier électronique à <b> $0</b>. S\'il vous plaît, confirmez votre email pour avoir accès à toutes les fonctionnalités!',
  DASHBOARD_ACCEPTED_NOTIFICATION: 'Le tableau de bord a été ajouté à la <b> barre latérale gauche</b>.',
  PROFILE_ACCEPTED_NOTIFICATION: 'Le profil a été accepté! <br /> <b> Veuillez vous déconnecter</b> pour accéder au compte de $0.',
  BUCKET_ACCEPTED_NOTIFICATION: 'Le compartiment a été accepté et ajouté à la <b> liste de compartiments</b>.',
  GO_TO_DASHBOARD: 'Aller au tableau de bord',
  HOME_END_USER_INTRO: 'Découvrez comment interagir avec des périphériques connectés à leurs applications. Il suffit de sélectionner un tableau de bord et de suivre les instructions pour utiliser l\'application.',
  NOT_A_DEV_DESCRIPTION: 'Si vous n\'êtes pas un développeur, utilisez notre vue simple. C\'est plus facile à utiliser!',
  CHANGE_TO_SIMPLE_USER_VIEW: 'Changer en vue simple',
  CHANGE_TO_DEVELOPER_VIEW: 'Changer en développeur',
  A_DEV_DESCRIPTION: 'Je suis un développeur et je construirai des applications sur la plate-forme.',
  DASHBOARD_DESCRIPTION_HOME: 'Un tableau de bord est l\'endroit où se trouvent toutes les informations d\'une application. Pour accéder à un tableau de bord, sélectionnez-en un dans le menu de gauche.',
  EXPLORE_DESCRIPTION_HOME: 'Explorez où vous pouvez voir des exemples de tableaux de bord. Pour y accéder, cliquez sur l\'option explorer dans le menu de gauche',
  NOTIFICATION_DESCRIPTION_HOME: 'Les notifications sont l\'endroit où vous recevez des informations importantes concernant les tableaux de bord et votre compte. Comme notificaçes estão do lado direito do sistema.',
  SHARE_DASHBOARDS_DESCRIPTION_HOME: 'Vous pouvez partager des tableaux de bord avec d\'autres utilisateurs, en leur accordant l\'accès pour afficher et interagir avec un tableau de bord.',
  USER_ACCOUNT_DESCRIPTION_HOME: 'Vous pouvez modifier les informations de votre compte dans la partie supérieure droite de la page, où votre nom apparaît.',
  HOME_END_USER_INTRO_TITLE: 'En savoir plus sur les ressources',
  REALTIME_INFO_HOME: 'Cet état indique si votre navigateur est connecté au serveur temps réel, utile pour certains widgets.',
  NOTIFICATIONS_INFO_HOME: 'Les notifications sont des messages que vous recevez via le système.',
  DOWNLOAD_OUR_APP: 'Téléchargez notre application pour',
  ACCOUNT_INFO_HOME1: 'Vous changez de compte à votre guise.',
  ACCOUNT_INFO_HOME2: 'Cliquez ici pour le faire!',
  DOWNLOAD_OUR_APP_TITLE: 'Téléchargez notre application',
  HOME_SUBTITLE_HAS_DASHBOARD: 'Vous pouvez visiter votre dernier tableau de bord en cliquant sur le bouton ci-dessous',
  HOME_SUBTITLE_NO_DASHBOARD: 'Vous pouvez consulter des exemples de tableaux de bord en cliquant sur le bouton ci-dessous.',
  HOME_BUTTON_NO_DASHBOARD: 'Découvrez les exemples',
  HOME_BUTTON_DASHBOARD: 'Aller à votre dernier tableau de bord',
  HOME_EXPLORE_INFO: 'explorer des exemples de tableaux de bord.',
  HOME_SUBTITLE_WL: 'On dirait que tu es nouveau ici. Pourquoi ne pas demander à quelqu\'un de partager un tableau de bord avec vous?',
  NOTIFICATION_WELCOME_TO_TAGO_DEV: 'Si vous êtes développeur, vous pouvez modifier le type de votre compte dans la page des paramètres du compte.',
  NOTIFICATION_SHARE_DASHBOARD: '$0 souhaite partager le tableau de bord $0 avec vous.',
  NOTIFICATION_SHARE_DASHBOARD_TITLE: 'Demande de partage - Tableau de bord',
  NOTIFICATION_SHARE_BUCKET: '$0 souhaite partager le seau $0 avec vous',
  NOTIFICATION_SHARE_BUCKET_TITLE: 'Demande de partage - Bucket',
  NOTIFICATION_SHARE_PROFILE: '$0 souhaite partager un profil avec vous.',
  NOTIFICATION_SHARE_PROFILE_TITLE: 'Demande de partage - Profil',
  NOTIFICATION_SEARCH: "Notifications de recherche",
  NOTIFICATION_ORIGIN: "Origine",
};
