module.exports = {
  NOTIFICATIONS_FROM_INSTALL: 'Application installée avec succès',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'Nouvel utilisateur enregistré',
  NOTIFICATIONS_SEARCH: 'Rechercher des notifications',
  NOTIFICATIONS_FROM_USER_REGISTERED: '$0 a créé un compte sur Tago. L\'article que vous avez partagé est disponible pour qu\'il accepte.',
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: 'Oups... $0 est maintenant enregistr? sur Tago, mais quelque chose s\'est mal tourné avec le partage. Essayez de partager à nouveau',
  ONLY_UNREAD: 'seulement non lu',
  OTHER_USERS: 'autres utilisations',
  RESEND_EMAIL_CONFIRMATION: 'Renvoyer un courriel de confirmation',
  TAGO_SYSTEM: 'système de Tago',
  YOU_REALLY_WANT_EXIT: 'Voulez-vous vraiment sortir',
  YOUR_EMAIL_HASNT_BEEN_CONFIRMED: 'Votre email n’a pas encore été confirmé. Confirmez votre email pour utiliser toutes les fonctionnalités de TagoIO.',
  TEMPLATE_TAB_NAME: 'Distribute the template of this $0',
  TEMPLATE_TAB_DESCRIPTION: 'Send the generated URL to others so they can access your $0 through a customized install page.',
  TEMPLATE_TAB_LINK_DESCRIPTION: 'Create a link that contains the template of this $0. Share the link with anyone.',
  TEMPLATE_TAB_URL_PLACEHOLDER: 'build your template to generate an url',
  TEMPLATE_LAST_GENERATED_AT: 'Last generated at',
  CUSTOMIZE_TEMPLATE_TITLE: 'Customize the page',
  CUSTOMIZE_TEMPLATE_DESCRIPTION: 'Add a logo and an image that better represents your template.',
  CUSTOMIZE_TEMPLATE_DESCRIPTION2: 'Images will be shown when users access the page using the generated URL.',
  TEMPLATE_LABEL_TITLE: 'Title of the page',
  TEMPLATE_PLACEHOLDER_TITLE: 'The title of the page',
  TEMPLATE_LABEL_LOGO: 'Logo of the page',
  TEMPLATE_PLACEHOLDER_LOGO: 'https url of the logo',
  TEMPLATE_LABEL_MAIN_IMG: 'Main image of the page',
  TEMPLATE_PLACEHOLDER_MAIN_IMG: 'https url of the main image',
  TEMPLATE_ANALYSIS_SETUP_TITLE: 'If you use environment variables, describe each "variable value" here.',
  TEMPLATE_ANALYSIS_SETUP_DESCRIPTION: 'Whoever receives this analysis will use this information to configure the variable value',
  TEMPLATE_DASHBOARD_SETUP_TITLE: 'Enter a description for each device',
  TEMPLATE_DASHBOARD_SETUP_DESCRIPTION: 'This information will help the user to select the right device in his/her account. (e.g. GPS Calamp LMU3030, Generator GRX2000, …).',
  TEMPLATE_BUILD_TEMPLATE: 'Build Template',
  SETUP_LIST_DESCRIPTION_ANALYSIS: 'enter a description for this "variable value"',
  SETUP_LIST_DESCRIPTION_DASHBOARD: 'enter a detailed description for this device',
  COPIED: 'Copied',
  COPY: 'Copy',
  NOTIFICATION_PROFILE_SHARE: '$0 veut partager un profil avec vous',
  NOTIFICATION_BUCKET_SHARE: '$0 veut partager le seau $1 avec vous',
  NOTIFICATION_DASHBOARD_SHARE: '$0 veut partager le tableau de bord $1 avec vous',
  NEW_USER_RESENT_CONFIRMATION_EMAIL: 'Nous avons envoyé un email à $0. S\'il vous plaît, confirmez votre email pour avoir accès à toutes les fonctionnalités!',
  DASHBOARD_ACCEPTED_NOTIFICATION: 'Le tableau de bord a été ajouté à la <b> barre latérale gauche</b>.',
  PROFILE_ACCEPTED_NOTIFICATION: 'Le profil a été accepté! <br /> <b> Veuillez vous déconnecter</b> pour accéder au compte de $0.',
  BUCKET_ACCEPTED_NOTIFICATION: 'Le compartiment a été accepté et ajouté à la <b> liste de compartiments</b>.',
  GO_TO_DASHBOARD: 'Emmenez-moi au tableau de bord',
};
