module.exports = {
  NOTIFICATIONS_FROM_INSTALL: 'Application installée avec succès',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'Nouvel utilisateur enregistré',
  NOTIFICATIONS_SEARCH: 'Rechercher des notifications',
  NOTIFICATIONS_FROM_USER_REGISTERED: "$0 a créé un compte sur Tago. L'article que vous avez partagé est disponible pour qu'il accepte.",
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: "Oups... $0 est maintenant enregistr? sur Tago, mais quelque chose s'est mal tourné avec le partage. Essayez de partager à nouveau",
  ONLY_UNREAD: 'seulement non lu',
  OTHER_USERS: 'autres utilisations',
  RESEND_EMAIL_CONFIRMATION: 'Renvoyer un courriel de confirmation',
  TAGO_SYSTEM: 'système de Tago',
  YOU_REALLY_WANT_EXIT: 'Voulez-vous vraiment sortir',
  YOUR_EMAIL_HASNT_BEEN_CONFIRMED: 'Votre email n’a pas encore été confirmé. Confirmez votre email pour utiliser toutes les fonctionnalités de TagoIO.',

  TEMPLATE_TAB_NAME: 'Modèle',
  TEMPLATE_TAB_DESCRIPTION: 'Envoyez l\'URL générée à d\'autres personnes pour accéder à votre tableau de bord via une page d\'installation personnalisée.',
  TEMPLATE_TAB_LINK_DESCRIPTION: 'Créez un lien contenant le modèle de ce $ 0. Partagez le lien avec n\'importe qui.',
  TEMPLATE_TAB_URL_PLACEHOLDER: 'construisez votre template pour générer une URL',
  TEMPLATE_LAST_GENERATED_AT: 'Dernier généré à',
  CUSTOMIZE_TEMPLATE_TITLE: 'Personnaliser',
  CUSTOMIZE_TEMPLATE_DESCRIPTION: 'Ajoutez un logo et une image qui représente mieux votre modèle. Les images seront affichées lorsque les utilisateurs accéderont à l\'URL ci-dessus.',
  TEMPLATE_LABEL_TITLE: 'Titre de la page',
  TEMPLATE_PLACEHOLDER_TITLE: 'Titre de la page',
  TEMPLATE_LABEL_LOGO: 'Logo de la page',
  TEMPLATE_PLACEHOLDER_LOGO: 'https url du logo',
  TEMPLATE_LABEL_MAIN_IMG: 'Image principale de la page',
  TEMPLATE_PLACEHOLDER_MAIN_IMG: 'URL https de l\'image principale',
  TEMPLATE_ANALYSIS_SETUP_TITLE: 'Décrivez le type de variables d\'environnement attendues par cette analyse.',
  TEMPLATE_ANALYSIS_SETUP_DESCRIPTION: 'Cette information aidera l\'utilisateur à utiliser la bonne valeur dans son compte.',
  TEMPLATE_DASHBOARD_SETUP_TITLE: 'Décrivez le type de périphérique attendu par ce tableau de bord.',
  TEMPLATE_DASHBOARD_SETUP_DESCRIPTION: 'Ces informations aideront l’utilisateur à sélectionner le bon appareil dans son compte. (par exemple, GPS Calamp LMU3030, générateur GRX2000,…).',
  TEMPLATE_BUILD_TEMPLATE: 'Modèle de construction',
  COPIED: 'Copié',
  COPY: 'Copie',
};
