module.exports = {
  NOTIFICATIONS_FROM_INSTALL: 'Aplicación instalada con éxito',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'Nuevo usuario registrado',
  NOTIFICATIONS_SEARCH: 'notificaciones de búsqueda',
  NOTIFICATIONS_FROM_USER_REGISTERED: '$0 acaba de crear una cuenta en Tago. El artículo que compartiste está disponible para que él lo acepte.',
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: 'Oops... $0 ahora está registrado en Tago, pero algo salió mal con el intercambio. Intenta compartir de nuevo.',
  ONLY_UNREAD: 'Solo sin leer',
  OTHER_USERS: 'Otros usuarios',
  RESEND_EMAIL_CONFIRMATION: 'Reenviar email de confirmación',
  TAGO_SYSTEM: 'Tago System',
  YOU_REALLY_WANT_EXIT: '¿Realmente desea salir',
  YOUR_EMAIL_HASNT_BEEN_CONFIRMED: 'Tu correo electrónico no ha sido confirmado todavía. Confirma tu correo electrónico para utilizar todas las funciones de TagoIO.',

  TEMPLATE_TAB_NAME: 'Modelo',
  TEMPLATE_TAB_DESCRIPTION: 'Agrega un logo y una imagen que mejor represente tu plantilla. Las imágenes se mostrarán cuando los usuarios accedan a la URL anterior.',
  TEMPLATE_TAB_LINK_DESCRIPTION: 'Crea un enlace que contenga la plantilla de este $0. Comparte el enlace con cualquiera.',
  TEMPLATE_TAB_URL_PLACEHOLDER: 'construye tu plantilla para generar un url',
  TEMPLATE_LAST_GENERATED_AT: 'Última generada en',
  CUSTOMIZE_TEMPLATE_TITLE: 'Personalizar',
  CUSTOMIZE_TEMPLATE_DESCRIPTION: 'Agrega un logo y una imagen que mejor represente tu plantilla. Las imágenes se mostrarán cuando los usuarios accedan a la URL anterior.',
  TEMPLATE_LABEL_TITLE: 'Título de la página',
  TEMPLATE_PLACEHOLDER_TITLE: 'Título de la página',
  TEMPLATE_LABEL_LOGO: 'Logo de la pagina',
  TEMPLATE_PLACEHOLDER_LOGO: 'https url del logo',
  TEMPLATE_LABEL_MAIN_IMG: 'Imagen principal de la página.',
  TEMPLATE_PLACEHOLDER_MAIN_IMG: 'https url de la imagen principal.',
  TEMPLATE_ANALYSIS_SETUP_TITLE: 'Describe the type of environment variables expected by this analysis.',
  TEMPLATE_ANALYSIS_SETUP_DESCRIPTION: 'Describa el tipo de variables de entorno esperadas por este análisis.',
  TEMPLATE_DASHBOARD_SETUP_TITLE: 'Describa el tipo de dispositivo esperado por este panel.',
  TEMPLATE_DASHBOARD_SETUP_DESCRIPTION: 'Esta información ayudará al usuario a seleccionar el dispositivo correcto en su cuenta. (por ejemplo, GPS Calamp LMU3030, Generador GRX2000,…).',
  TEMPLATE_BUILD_TEMPLATE: 'Construir plantilla',
  COPIED: 'Copiado',
  COPY: 'Copiar',
};
