module.exports = {
  NOTIFICATIONS_FROM_INSTALL: 'Aplicación instalada con éxito',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'Nuevo usuario registrado',
  NOTIFICATIONS_SEARCH: 'notificaciones de búsqueda',
  NOTIFICATIONS_FROM_USER_REGISTERED: '$0 acaba de crear una cuenta en Tago. El artículo que compartiste está disponible para que él lo acepte.',
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: 'Oops... $0 ahora está registrado en Tago, pero algo salió mal con el intercambio. Intenta compartir de nuevo.',
  ONLY_UNREAD: 'Solo sin leer',
  OTHER_USERS: 'Otros usuarios',
  RESEND_EMAIL_CONFIRMATION: 'Reenviar email de confirmación',
  TAGO_SYSTEM: 'Tago System',
  YOU_REALLY_WANT_EXIT: '¿Realmente desea salir',
  YOUR_EMAIL_HASNT_BEEN_CONFIRMED: 'Tu correo electrónico no ha sido confirmado todavía. Confirma tu correo electrónico para utilizar todas las funciones de TagoIO.',
  
  TEMPLATE_TAB_NAME: 'Distribute the template of this $0',
  TEMPLATE_TAB_DESCRIPTION: 'Send the generated URL to others so they can access your $0 through a customized install page.',
  TEMPLATE_TAB_LINK_DESCRIPTION: 'Create a link that contains the template of this $0. Share the link with anyone.',
  TEMPLATE_TAB_URL_PLACEHOLDER: 'build your template to generate an url',
  TEMPLATE_LAST_GENERATED_AT: 'Last generated at',
  CUSTOMIZE_TEMPLATE_TITLE: 'Customize the page',
  CUSTOMIZE_TEMPLATE_DESCRIPTION: 'Add a logo and an image that better represents your template.',
  CUSTOMIZE_TEMPLATE_DESCRIPTION2: 'Images will be shown when users access the page using the generated URL.',
  TEMPLATE_LABEL_TITLE: 'Title of the page',
  TEMPLATE_PLACEHOLDER_TITLE: 'The title of the page',
  TEMPLATE_LABEL_LOGO: 'Logo of the page',
  TEMPLATE_PLACEHOLDER_LOGO: 'https url of the logo',
  TEMPLATE_LABEL_MAIN_IMG: 'Main image of the page',
  TEMPLATE_PLACEHOLDER_MAIN_IMG: 'https url of the main image',
  TEMPLATE_ANALYSIS_SETUP_TITLE: 'If you use environment variables, describe each "variable value" here.',
  TEMPLATE_ANALYSIS_SETUP_DESCRIPTION: 'Whoever receives this analysis will use this information to configure the variable value',
  TEMPLATE_DASHBOARD_SETUP_TITLE: 'Enter a description for each device',
  TEMPLATE_DASHBOARD_SETUP_DESCRIPTION: 'This information will help the user to select the right device in his/her account. (e.g. GPS Calamp LMU3030, Generator GRX2000, …).',
  TEMPLATE_BUILD_TEMPLATE: 'Build Template',
  SETUP_LIST_DESCRIPTION_ANALYSIS: 'enter a description for this "variable value"',
  SETUP_LIST_DESCRIPTION_DASHBOARD: 'enter a detailed description for this device',
  COPIED: 'Copied',
  COPY: 'Copy',
};
