module.exports = {
  NOTIFICATIONS_FROM_INSTALL: 'Aplicación instalada con éxito',
  NOTIFICATIONS_NEW_USER_REGISTERED: 'Nuevo usuario registrado',
  NOTIFICATIONS_SEARCH: 'notificaciones de búsqueda',
  NOTIFICATIONS_FROM_USER_REGISTERED: '$0 acaba de crear una cuenta en Tago. El artículo que compartiste está disponible para que él lo acepte.',
  NOTIFICATIONS_FROM_USER_REGISTERED_FAIL: 'Oops... $0 ahora está registrado en Tago, pero algo salió mal con el intercambio. Intenta compartir de nuevo.',
  ONLY_UNREAD: 'Solo sin leer',
  OTHER_USERS: 'Otros usuarios',
  RESEND_EMAIL_CONFIRMATION: 'Reenviar email de confirmación',
  TAGO_SYSTEM: 'Tago System',
  YOU_REALLY_WANT_EXIT: '¿Realmente desea salir',
  YOUR_EMAIL_HASNT_BEEN_CONFIRMED: 'Tu correo electrónico no ha sido confirmado todavía. Confirma tu correo electrónico para utilizar todas las funciones de TagoIO.',
  TEMPLATE_TAB_NAME: 'Distribute the template of this $0',
  TEMPLATE_TAB_DESCRIPTION: 'Send the generated URL to others so they can access your $0 through a customized install page.',
  TEMPLATE_TAB_LINK_DESCRIPTION: 'Create a link that contains the template of this $0. Share the link with anyone.',
  TEMPLATE_TAB_URL_PLACEHOLDER: 'build your template to generate an url',
  TEMPLATE_LAST_GENERATED_AT: 'Last generated at',
  CUSTOMIZE_TEMPLATE_TITLE: 'Customize the page',
  CUSTOMIZE_TEMPLATE_DESCRIPTION: 'Add a logo and an image that better represents your template.',
  CUSTOMIZE_TEMPLATE_DESCRIPTION2: 'Images will be shown when users access the page using the generated URL.',
  TEMPLATE_LABEL_TITLE: 'Title of the page',
  TEMPLATE_PLACEHOLDER_TITLE: 'The title of the page',
  TEMPLATE_LABEL_LOGO: 'Logo of the page',
  TEMPLATE_PLACEHOLDER_LOGO: 'https url of the logo',
  TEMPLATE_LABEL_MAIN_IMG: 'Main image of the page',
  TEMPLATE_PLACEHOLDER_MAIN_IMG: 'https url of the main image',
  TEMPLATE_ANALYSIS_SETUP_TITLE: 'If you use environment variables, describe each "variable value" here.',
  TEMPLATE_ANALYSIS_SETUP_DESCRIPTION: 'Whoever receives this analysis will use this information to configure the variable value',
  TEMPLATE_DASHBOARD_SETUP_TITLE: 'Enter a description for each device',
  TEMPLATE_DASHBOARD_SETUP_DESCRIPTION: 'This information will help the user to select the right device in his/her account. (e.g. GPS Calamp LMU3030, Generator GRX2000, …).',
  TEMPLATE_BUILD_TEMPLATE: 'Build Template',
  SETUP_LIST_DESCRIPTION_ANALYSIS: 'enter a description for this "variable value"',
  SETUP_LIST_DESCRIPTION_DASHBOARD: 'enter a detailed description for this device',
  COPIED: 'Copied',
  COPY: 'Copy',
  NOTIFICATION_PROFILE_SHARE: '$0 quiere compartir un perfil contigo',
  NOTIFICATION_BUCKET_SHARE: '$0 quiere compartir el cubo $1 contigo',
  NOTIFICATION_DASHBOARD_SHARE: '$0 quiere compartir el tablero $1 contigo',
  NEW_USER_RESENT_CONFIRMATION_EMAIL: 'Hemos enviado un correo electrónico a <b> $0 </b>. Por favor, confirme su correo electrónico para obtener acceso a todas las funciones!',
  DASHBOARD_ACCEPTED_NOTIFICATION: 'El panel de control se agregó a la <b> barra lateral izquierda </b>.',
  PROFILE_ACCEPTED_NOTIFICATION: '¡Se aceptó el perfil! <br /> <b> Por favor cierre la sesión </b> para obtener acceso a la cuenta de $0.',
  BUCKET_ACCEPTED_NOTIFICATION: 'El grupo se aceptó y se agregó a la <b> lista de grupos </b>.',
  GO_TO_DASHBOARD: 'Ir al panel de control',
  HOME_END_USER_INTRO: 'Aprenda sobre cómo interactuar con dispositivos conectados a sus aplicaciones. Simplemente seleccione un panel y siga las instrucciones para operar la aplicación.',
  NOT_A_DEV_DESCRIPTION: 'Si no eres un desarrollador, usa nuestra Vista Simple. ¡Es más fácil de usar!',
  CHANGE_TO_SIMPLE_USER_VIEW: 'Cambiar a vista simple',
  CHANGE_TO_DEVELOPER_VIEW: 'Cambiar a desarrollador',
  A_DEV_DESCRIPTION: 'Soy un desarrollador y construiré aplicaciones en la plataforma.',
  DASHBOARD_DESCRIPTION_HOME: 'Un Dashboard es donde se encuentra toda la información de una aplicación. Para acceder a un panel, seleccione uno en el menú del lado izquierdo.',
  EXPLORE_DESCRIPTION_HOME: 'Explorar es donde puedes ver ejemplos de paneles de control. Para acceder a él, haga clic en la opción de exploración en el menú en el lado izquierdo',
  NOTIFICATION_DESCRIPTION_HOME: 'Las notificaciones son donde recibe información importante sobre los tableros y su cuenta. Como se indica en este lado, direito do sistema.',
  SHARE_DASHBOARDS_DESCRIPTION_HOME: 'Puede compartir paneles con otros usuarios, otorgándoles acceso para ver e interactuar con un panel.',
  USER_ACCOUNT_DESCRIPTION_HOME: 'Puede cambiar la información de su cuenta en la parte superior derecha de la página, donde aparece su nombre.',
  HOME_END_USER_INTRO_TITLE: 'Aprende más sobre los recursos.',
  REALTIME_INFO_HOME: 'Este estado muestra si su navegador está conectado al servidor en tiempo real, útil para algunos widgets',
};
