module.exports = {
  ABOUT_THIS_SHARING: 'Sobre esse compartilhamento',
  ALLOW_SHARE_WITH_OTHERS: 'Permitir compartilhar com outros',
  CANCEL_SHARING: 'Cancelar Compartilhamento',
  CREATE_MORE_DASHBOARDS: 'crie mais painéis',
  DASHBOARD_ID: 'Painel ID',
  DASHBOARD_NAME: 'Nome do painel',
  DASHBOARD_SHARED_BY: 'Painel compartilhado por',
  DELETE_DASHBOARD: 'Excluir Painel',
  ENTER_NAME_DASHBOARD: 'entre com o nome do painel',
  INVITED_BY: 'Convidado por $0$',
  INVITE_USER: 'Convidar usuário',
  LAST_ACCESS: 'Último acesso',
  MAKE_DASHBOARD_VISIBLE: 'Tornar esse painel visível',
  MORE_ABOUT_DASHBOARD: 'Mais sobre o painel',
  ONCE_YOU_DELETE_DASHBOARD: 'Esse procedimento é irreversível. Tenha certeza que realmente deseja excluir',
  REGISTERED_AT: 'Registrado em',
  REMOVE_INVITE: 'Remover convite',
  SHARE_EXPIRES_AT: 'Compartilhamento expira em',
  SHARE_IT_DURING: 'Compartilhar durante',
  SHARE_PRIVATE: 'Compartilhamento privado',
  SHARED_WITH: 'Compartilhado com',
  THIS_DASHBOARD_HAS_BEEN_SHARED: 'Este painel foi compartilhado com você (você não pode editá-lo)',
  USER_DOESNT_HAVE_AN_ACCOUNT_YET: 'Usuário não possui uma conta ainda',
  WHEN_HIDDEN_THE_DASHBOARD_WILL_NOT_LISTED: 'Quando oculto, o painel não será exibido no menu esquerdo do admin',
  WHEN_YOU_SHARE_DASHBOARD_OTHERS: 'Quando você compartilhar esse painel, outros não poderão editá-lo.',
  YOU_ARE_CURRENTLY_SHARING_DASHBOARD: 'Você está compartilhando esse painel com outros usuários. Se você confirmar, o compartilhamento do painel também será removido',
  YOU_CANNOT_MANUALLY_REMOVE_DASHBOARDS: 'Você não pode remover painéis manualmente quando vinculados a uma aplicação',
  YOU_NOT_SHARING_THIS_DASHBOARD_PRIVATELY: 'Você ainda não compartilhou esse painel de forma privada',
  YOU_DONT_HAVE_PERMISSION_ACCESS_PAGE: 'Você não tem permissão para acessar essa página',
  YOU_SHARED_DASHBOARD_WITH_EXPIRATION_DATE_GREATER: 'Você compartilhou um painel com uma data de validade maior do que a data de validade de expiração que foi feita para você. A participação por $0$ expira em: $1$.',
  YOU_REALLY_WANT_DELETE_DASHBOARD: 'Você realmente deseja exluir esse painel',
  YOU_REALLY_WANT_DELETE_SHARE: 'Você realmente deseja exluir esse compartilhamento',
  YOU_REALLY_WANT_CANCEL_SHARING: 'Você realmente deseja cancelar o compartilhamento desse painel',
  YOUR_PLAN_ALLOWS_YOU_CREATE_UP: 'Seu plano permite que você crie até 5 painéis',
};
