module.exports = {
  ADD_MARKER: 'Ajouter un pin à cette couche',
  ADD_LAYER: 'Ajouter une couche',
  DEFINE_EMBED_TO_APPEAR_TOOLBOX: 'Définir une incorporation à apparaître dans la boîte à outils',
  DEFINE_LABEL_TO_APPEAR_TOOLBOX: 'Définir une étiquette à afficher dans la boîte à outils',
  DEFINE_IMAGE_EMBED_APPEAR_TOOLBOX: 'Définir une image ou une incorporation à apparaître dans la boîte à outils',
  DO_YOU_REALLY_DELETE_LAYER: 'Voulez-vous vraiment supprimer cette couche',
  DO_YOU_REALLY_DELETE_PIN: 'Voulez-vous vraiment supprimer cette épingle?',
  EDIT_LAYER: 'Modifier le calque',
  EDIT_MARKER: "Modifier l'épingle",
  ENTER_VALUE_VARIABLE: "entrer la valeur de cette pin",
  ICON_MARKER: "Définir une icône pour cette épingle",
  IMAGE_MARKER: "Définir une image à afficher dans l'info-bulle",
  VALUE_MARKER: 'Définir la valeur pour cette pin',
  VARIABLE_MARKER: 'Définit où cette pin sera stockée',
};
