module.exports = {
  ACCEPT: 'Acceptez',
  ACCEPTED: 'Accepté',
  ACCOUNT: 'compte',
  ALL: 'Tout',
  APPLICATION: 'Application',
  APPLICATIONS: 'Applications',
  APRIL: 'Avril',
  ARE_YOU_SURE: 'Êtes-vous sûr',
  AUDIT_LOG: 'Journal d\'audit',
  AUGUST: 'Août',
  BACK: 'Retourner',
  BACKGROUND_IMAGE: 'image de fond',
  CANCEL: 'Annuler',
  CLEAR: 'Deblayer',
  CLICK: 'Cliquez',
  CLOSE: 'Ferme',
  COLLAPSE: 'Effondrer',
  COMMA: 'Virgule',
  SEMICOLON: 'Point-virgule',
  COMPANY: 'Firme',
  CUSTOM: 'Coutume',
  DATE_FORMAT: 'Format de date',
  DAY: 'Jour',
  DASHBOARD: 'Tableau de bord',
  DASHBOARDS: 'Tableaux de bord',
  DECEMBER: 'Décembre',
  DECLINE: 'Déclin',
  DECLINED: 'refusé',
  DELETE: 'Effacer',
  DEVELOPER: 'Développeur',
  DEVICES: 'Appareil',
  DOT: 'Point',
  EMAIL: 'E-mail',
  END_DATE: 'Date de fin',
  ENTER_EMBED_URL: "entrez l'URL intégrée",
  ENTER_IMAGE_URL: "entrez l'URL de l'image",
  ENTER_NAME: 'entrez le nom',
  ENTER_EMAIL: 'Entrez l\'adresse e-mail',
  ENTER_LABEL: "entrer l'étiquette",
  ENTER_YOUR_EMAIL: 'Entre votre e-mail',
  EXPAND: '?tendre',
  FEBRUARY: 'Février',
  FILTER: 'filtrage',
  FINISH: 'Terminer',
  FREE: 'gratuit',
  FRIDAY: 'Vendredi',
  FROM: 'De',
  GENERAL_INFORMATION: 'Informations générales',
  GO_TO: 'Aller à',
  HERE: 'Ici',
  HOUR: 'Heure',
  IGNORE: 'Ignore',
  IMAGE: 'Image',
  INDEFINITELY: 'Indéfiniment',
  INFORMATION: 'Information',
  INVITE: 'Invite',
  JANUARY: 'Janvier',
  JULY: 'Juillet',
  JUNE: 'Juin',
  LANGUAGE: 'La langue',
  LOCATION: 'emplacement',
  MARCH: 'Mars',
  MAY: 'Mai',
  MINUTE: 'Minute',
  MONDAY: 'Lundi',
  MONTH: 'Mois',
  MORE: 'Plus',
  MY_ACCOUNT: 'Mon compte',
  MY_BILLING: 'Ma facturation',
  NAME: 'Prénom',
  NEXT: 'Prochain',
  NO: 'Non',
  NO_OPTIONS: 'Pas d\'options',
  NOTIFICATIONS: 'Notifications',
  NOVEMBER: 'Novembre',
  OCTOBER: 'Octobre',
  OF_PAGINATION: 'de',
  OR: 'ou',
  REFUSED: 'Refusé',
  PASSWORD: 'Mot de passe',
  PENDING: 'En attendant',
  PLAN: 'Plan',
  PHONE: 'Téléphone',
  PLEASE_CHECK_YOUR_EMAIL: 'Merci de consulter vos emails',
  PLEASE_ENTER_YOUR_EMAIL: 'S\'il vous plaît, entrez votre adresse email',
  PLEASE_ENTER_REQUIRED_FIELDS: 'Veuillez entrer les domaines obligatoires',
  PREVIOUS: 'Antérieur',
  SAVE: 'Enregistre',
  SATURDAY: 'Samedi',
  SECOND: 'Seconde',
  SELECT_ALL: 'Tout sélectionner',
  SELECT_FILE: 'Sélectionnez un fichier',
  SELECT_VALUE: 'sélectionnez une valeur',
  SELECT_IMAGE: 'sélectionner une image',
  SEPTEMBER: 'Septembre',
  SERVICES: 'Service',
  SHARE: 'Partager',
  SIGN_OUT: 'Déconnexion',
  SOUND: 'Son',
  START_DATE: 'Data inicial',
  SUBMIT: 'Envoyer',
  SUNDAY: 'Dimanche',
  TIME_FORMAT: "Format de l'heure",
  TIMEZONE: 'Fuseau horaire',
  THIS_FIELD_IS_REQUIRED: 'Ce domaine est requis',
  THIS_FIELD_REQUIRES_AT_LEAST_THREE_CHARACTERS: 'Ce domaine nécessite au moins 3 caractères',
  THIS_FIELD_REQUIRES_VALID_HTTPS_URL: 'Ce champ nécessite une URL HTTPS valide',
  THURSDAY: 'Jeudi',
  TUESDAY: 'Mardi',
  UNDO: 'annuler le changement',
  VALUE: 'Valeur',
  VARIABLE: 'Variable',
  WEDNESDAY: 'Mercredi',
  WEEK: 'Semaine',
  YEAR: 'an',
  YES: 'Oui',
  CONFIGURATION: 'Paramètres',
  DASHBOARDS_SHARE_DASHBOARD: 'Partager',
  DUPLICATE_DASHBOARD: 'Dupliqué',
  BUILD_TEMPLATE: 'Modèle',
  DASHBOARDS_DELETE_DASHBOARD: 'Supprimer',
  DISMISS: 'Rejeter',
  NOT_A_DEVELOPER: 'Pas un développeur?',
  A_DEVELOPER: 'Vous êtes développeur? Cliquez ici',
  NOTIFICATION: 'Notification',
  SHARE_DASHBOARDS: 'Partager des tableaux de bord',
  WELCOME: 'Salut, comment vas tu',
  REALTIME: 'Temps réél',
  CONNECTED: 'Connecté',
  DISCONNECTED: 'Débranché',
  WELCOME_DEVELOPER: 'Bienvenue développeur',
  CHANGE_MY_SETTINGS: 'Changer mes paramètres',
  EXPLORE: 'Explorer',
  CLICK_HERE: 'Cliquez ici',
  IGNORED: 'Ignoré',
  MAP: 'Carte',
  SATELLITE: 'Satellite',
  NEW_HERE: 'Nouveau ici?',
  ALREADY_HAVE_AN_ACCOUNT: 'Vous avez déjà un compte?',
  PUBLIC_DASHBOARD: 'Tableau de bord public',
  UNLIMITED: 'Illimité',
  ADD_PROFILES: 'Ajouter un profil',
  USER_MANAGEMENT: 'Gestion de utilisateurs',
  ACCESS_MANAGEMENT: 'Gestion des accès',

  CONFIRM_YOUR_E_MAIL_BEFORE_PROCEEDING: 'Confirmez votre e-mail avant de continuer.',
  ACCOUNT_CREATION_HAS_BEEN_SUBMITTED: 'La création du compte a été soumise',
  YOUR_ACCOUNT_WAS_CREATED: 'Votre compte a été créé!',
  YOU_WILL_BE_NOTIFIED_WHEN_IT_IS_ACTIVATED: 'Vous serez averti quand il sera activé.',

  NO_NOTIFICATIONS: 'Aucune notification',
  NO_DASHBOARDS: 'Pas de tableaux de bord',
  NO_CONTENT: 'Pas content',

  MAP_BASIC: 'Carte de Base',
  MAP_DARK: 'Carte Sombre',
  MAP_LIGHT: 'Lumière de la carte',

  AGREE_WITH: "Je suis d'accord avec les",
  DYNAMIC_TABLE_ROW_DELETED: "La ligne a été supprimée avec succès.",
  DYNAMIC_TABLE_ROW_EDITED: "Ligne modifiée avec succès!",
  DYNAMIC_TABLE_SEARCH: "rechercher",
  LAST_UPDATE_AT: "Dernière mise à jour à",
  PRESET_CALENDAR_CUSTOM: "Douane",
  PRESET_CALENDAR_DAY: "Journée",
  PRESET_CALENDAR_MINUTE: "Minute",
  PRESET_CALENDAR_MONTH: "Mois",
  PRESET_CALENDAR_SECOND: "Seconde",
  PRESET_CALENDAR_WEEK: "Semaine",
  PRESET_CALENDAR_YEAR: "An",
  PRESET_CALENDAR_FOREVER: "Pour toujours",

  EXPORT_CSV_DOWNLOAD: "Télécharger fichier",
  EXPORT_CSV_MODAL_TITLE: "Exporter au format CSV",
  EXPORT_CSV_SELECT_SEPARATOR: "Sélectionnez le séparateur du fichier CSV",
  SEMICOLON: "Point virgule",

  NOTIFICATION_CLICK_ON: "Cliquez sur",
  NOTIFICATION_CONFIRMATION_READ_ALL_CONFIRM: "Oui, marquer toutes les notifications comme lues",
  NOTIFICATION_CONFIRMATION_READ_ALL_DESC:
    "Voulez-vous vraiment marquer toutes les notifications comme lues ? Cela peut prendre un certain temps selon le nombre de notifications.",
  NOTIFICATION_DELETE: "Supprimer la notification",
  NOTIFICATION_FILTERED_BY: "Filtrer par:",
  NOTIFICATION_MARK_ALL_AS_READ: "Marquer toutes les notifications comme lues",
  NOTIFICATION_MARK_AS_READ: "Marquer comme lu",
  NOTIFICATION_MARK_AS_UNREAD: "Marquer comme non lu",
  NOTIFICATION_NONE: "Vous n'avez aucune notification",
  NOTIFICATION_NOT_FOUND: "Aucune notification trouvée",
  NOTIFICATION_SHOW_ALL: "Afficher toutes les notifications",
  NOTIFICATION_SHOW_UNREAD: "Afficher les notifications non lues",
  NOTIFICATION_TO_SEE_ALL: "pour voir toutes les notifications.",
  NOTIFICATION_UNREAD: "non lu",
  NOTIFICATION_YOUVE_READ_ALL: "Vous les avez tous lus !",

  DELETE_ACCOUNT: "Supprimer le compte",
  ARE_YOU_SURE_DELETE_ACCOUNT: "Êtes-vous sûr? La suppression d'un compte est une action irréversible.",
  CONFIRM_DELETE_ACCOUNT: "Oui, supprimer mon compte",
  DELETE_ACCOUNT_MESSAGE: "Une demande de suppression de compte a été envoyée !",
  MOBILE_RUN_ACCOUNT_SETTINGS: "Paramètres du compte",
  MOBILE_RUN_DELETE_ACCOUNT: "Supprimer le compte",
  MOBILE_SETTINGS_DORELLY_DELETE_ACCOUNT: "Êtes-vous sûr? La suppression d'un compte est une action irréversible.",

  "2FA_AUTHENTICATION": "Authentification à deux facteurs",
  SECURITY_PREFERENCES: "Préférences de sécurité",
  APP_AUTHENTICATOR: "Application d'authentification",
  SMS: "SMS",
  "2FA_CONFIGURED": "Configuré",
  "2FA_YOU_HAVE_ENABLED": "Vous avez activé l'authentification à deux facteurs.",
  "2FA_APP_AUTHENTICATOR_TIP": "Votre application affichera un code d'authentification.",
  "2FA_6_DIGIT_CODE": "code à 6 chiffres",
  "2FA_CANT_ACCESS_DEVICE": "Vous ne pouvez pas accéder à votre appareil à deux facteurs ?",
  "2FA_CODE_INCORRECT": "Le code que vous avez entré est incorrect",
  "2FA_ADD": "Ajoutez l'authentification à deux facteurs",
  "2FA_INTRODUCTION":
    "L'authentification à deux facteurs est un niveau de sécurité supplémentaire utilisé lors de la connexion à des sites web ou à des applications.",
  "2FA_INTRODUCTION_REINFORCEMENT":
    "Une fois le compte configuré, la seule façon pour quiconque de se connecter à votre compte est de connaître le mot de passe ET d'avoir accès au code d'authentification.",
  "2FA_HOW_TO_APP_AUTHENTICATOR":
    "Utilisez une application sur votre téléphone pour obtenir les codes d'authentification à deux facteurs lorsque vous y êtes invité. Nous recommandons d'utiliser un TOTP basé sur le cloud, tel que : 1Password, Microsoft Authenticator, Google Authenticator.",
  CONFIRM_THIS_ACTION_BY_PASSWORD: "Confirmez cette action en entrant votre mot de passe",
  PASSWORD_INCORRECT: "Le mot de passe que vous avez entré est incorrect",
  "2FA_ENABLED_WARNING":
    "Pour des raisons de sécurité, une fois l'authentification à deux facteurs activée, si vous perdez vos identifiants d'authentification, le seul moyen de les récupérer est de contacter le support.",
  "2FA_APP_AUTHENTICATOR_CONFIG":
    "Scanner l'image ci-dessous avec l'application d'authentification à deux facteurs sur votre téléphone. Si vous ne pouvez pas utiliser de code QR, saisissez le code texte suivant :",
  "2FA_YOU_ARE_ENABLING": "Vous activez l'authentification à deux facteurs",
  "2FA_ADD_METHOD": "Ajouter une méthode d'authentification",
  "2FA_SETTINGS_BEEN_SAVED":
    "Les paramètres de l'authentificateur à deux facteurs ont été enregistrés. Si vous avez apporté d'autres modifications à votre profil, cliquez sur \"Enregistrer\".",
  "2FA_SENT_SMS": "Nous envoyons un SMS contenant le code d'authentification sur votre téléphone",
  MAY_TAKE_A_MINUTE: "Il peut prendre jusqu'à 1 minute pour arriver.",
  "2FA_HAVENT_RECEIVED_CODE": "Vous n'avez pas reçu de code ? Envoyez-en un autre.",
  "2FA_YOU_WILL_RECEIVE_SMS_FOR":
    "Vous recevrez un SMS contenant le code d'authentification lorsque vous serez invité à entrer :",
  COUNTRY_CODE: "Code pays",
  PHONE_NUMBER: "Numéro de téléphone",
  "2FA_PHONE_CHANGE": "Cela modifie les informations téléphoniques de votre compte.",
  "2FA_WE_HAVE_SENT_YOU_CODE":
    "Nous vous avons envoyé un nouveau code. Si cela ne fonctionne toujours pas, veuillez contacter l'assistance technique.",
  "2FA_SENT_EMAIL": "Nous envoyons un code d'authentification à votre e-mail.",
  "2FA_YOU_WILL_RECEIVE_EMAIL_FOR":
    "Vous recevrez un email contenant le code d'authentification lorsque vous y serez invité :",
  "2FA_REQUEST_NEW_CODE": "Demander un nouveau code",
  "2FA_ENDING_PHONE": "Téléphone se terminant par",
  "2FA_SENDING_EMAIL_TO": "Envoyez un email à",
  "2FA_OR_TYPE_CODE_AGAIN": "Ou entrez à nouveau le code",
  "2FA_TOO_MANY_REQUESTS":
    "Vous avez fait trop de demandes. Le courrier électronique et les SMS ont été temporairement désactivés.",
  "2FA_REMOVE": "Supprimer l'authentification à deux facteurs",
  "2FA_APP_AUTHENTICATOR_REMOVE": "Cela supprimera votre méthode d'application d'authentification.",
  "2FA_EMAIL_REMOVE": "Vous supprimerez votre méthode de courrier électronique.",
  "2FA_SMS_REMOVE": "Vous supprimerez votre méthode SMS.",
  "2FA_REMOVE_MESSAGE": "Ensuite, il vous suffira d'utiliser votre mot de passe pour vous connecter.",
  PASSWORD_MIN_LENGTH: "Doit contenir le nombre minimum de caractères",
  MUST_CONTAIN_SPECIAL_CHARACTERS: "Doit contenir au moins un caractère spécial (@, !, &, …)",
  MUST_CONTAIN_MIX_LETTERS_NUMBERS: "Doit contenir une combinaison de lettres et de chiffres",
  MUST_CONTAIN_UPPER_LOWER_CASE_CHARACTERS: "Doit contenir des lettres majuscules et minuscules",
  STRONG_PASSWORD: "Bon travail. c'est un excellent mot de passe",
};
