module.exports = {
  ACCEPT: 'Acceptez',
  ACCEPTED: 'Accepté',
  ACCOUNT: 'compte',
  ALL: 'Tout',
  APPLICATION: 'Application',
  APPLICATIONS: 'Applications',
  APRIL: 'Avril',
  ARE_YOU_SURE: 'Êtes-vous sûr',
  AUDIT_LOG: "Journal d'audit",
  AUGUST: 'Août',
  BACK: 'Retourner',
  CANCEL: 'Annuler',
  CLEAR: 'Deblayer',
  CLICK: 'Cliquez',
  CLOSE: 'Ferme',
  COLLAPSE: 'Effondrer',
  COMPANY: 'Firme',
  CUSTOM: 'Coutume',
  DAY: 'Jour',
  DASHBOARD: 'Tableau de bord',
  DASHBOARDS: 'Tableaux de bord',
  DECEMBER: 'Décembre',
  DECLINE: 'Déclin',
  DECLINED: 'refusé',
  DEVELOPER: 'Développeur',
  DEVICES: 'Appareil',
  EMAIL: 'Email',
  END_DATE: 'Date de fin',
  ENTER_EMAIL: "Entrez l'adresse e-mail",
  ENTER_YOUR_EMAIL: 'Entre votre e-mail',
  EXPAND: '?tendre',
  FEBRUARY: 'Février',
  FREE: 'gratuit',
  FRIDAY: 'Vendredi',
  FROM: 'De',
  GENERAL_INFORMATION: 'Informations générales',
  GO_TO: 'Aller à',
  HERE: 'Ici',
  HOUR: 'Heure',
  IGNORE: 'Ignore',
  INDEFINITELY: 'Indéfiniment',
  INFORMATION: 'Information',
  INVITE: 'Invite',
  JANUARY: 'Janvier',
  JULY: 'Juillet',
  JUNE: 'Juin',
  LANGUAGE: 'La langue',
  LOCATION: 'emplacement',
  MARCH: 'Mars',
  MAY: 'Mai',
  MINUTE: 'Minute',
  MONDAY: 'Lundi',
  MONTH: 'Mois',
  MORE: 'Plus',
  MY_ACCOUNT: 'Mon compte',
  MY_BILLING: 'Ma facturation',
  NAME: 'Prénom',
  NEXT: 'Prochain',
  NO: 'Non',
  NOTIFICATIONS: 'Notifications',
  NOVEMBER: 'Novembre',
  OCTOBER: 'Octobre',
  OF_PAGINATION: 'de',
  OR: 'ou',
  REFUSED: 'Refusé',
  PASSWORD: 'Mot de passe',
  PENDING: 'En attendant',
  PHONE: 'Téléphone',
  PLEASE_CHECK_YOUR_EMAIL: 'Merci de consulter vos emails',
  PLEASE_ENTER_YOUR_EMAIL: "S'il vous plaît, entrez votre adresse email",
  PLEASE_ENTER_REQUIRED_FIELDS: 'Veuillez entrer les domaines obligatoires',
  PREVIOUS: 'Antérieur',
  SAVE: 'Enregistre',
  SATURDAY: 'Samedi',
  SECOND: 'Seconde',
  SEPTEMBER: 'Septembre',
  SHARE: 'Partager',
  SIGN_OUT: 'Déconnexion',
  SOUND: 'Son',
  START_DATE: 'Data inicial',
  SUBMIT: 'Envoyer',
  SUNDAY: 'Dimanche',
  TIMEZONE: 'Fuseau horaire',
  THIS_FIELD_IS_REQUIRED: 'Ce domaine est requis',
  THIS_FIELD_REQUIRES_AT_LEAST_THREE_CHARACTERS: 'Ce domaine nécessite au moins 3 caractères',
  THURSDAY: 'Jeudi',
  TUESDAY: 'Mardi',
  UNDO: 'annuler le changement',
  VALUE: 'Valeur',
  VARIABLE: 'Variable',
  WEDNESDAY: 'Mercredi',
  WEEK: 'Semaine',
  YEAR: 'an',
  YES: 'Oui',
};
