module.exports = {
  ACCEPT: 'Aceptar',
  ACCEPTED: 'Aceptado',
  ACCOUNT: 'cuenta',
  ALL: 'Todos',
  APPLICATION: 'Aplicación',
  APPLICATIONS: 'aplicaciones',
  APRIL: 'Abril',
  ARE_YOU_SURE: '¿Estás seguro',
  AUDIT_LOG: 'Registro de auditoría',
  AUGUST: 'Agosto',
  BACK: 'Regresar',
  CANCEL: 'Cancelar',
  CLEAR: 'Limpiar',
  CLICK: 'Hacer clic',
  CLOSE: 'Cerrar',
  COLLAPSE: 'colapsar',
  COMPANY: 'Empresa',
  CUSTOM: 'Personalizado',
  DAY: 'Día',
  DASHBOARD: 'Tablero',
  DASHBOARDS: 'Tableros',
  DECEMBER: 'Diciembre',
  DECLINE: 'Desistir',
  DECLINED: 'Declinado',
  DEVELOPER: 'Desarrollador',
  DEVICES: 'Dispositivos',
  EMAIL: 'Correo electrónico',
  END_DATE: 'Fecha final',
  ENTER_EMAIL: 'ingrese la dirección de correo electrónico',
  ENTER_YOUR_EMAIL: 'Introduce tu correo electrónico',
  EXPAND: 'Expandir',
  FEBRUARY: 'Febrero',
  FILTER: 'filtrar',
  FINISH: 'Finalizar',
  FREE: 'Gratis',
  FRIDAY: 'Viernes',
  FROM: 'Desde',
  GENERAL_INFORMATION: 'Informaciones Generales',
  GO_TO: 'Ir para',
  HERE: 'Aquí',
  HOUR: 'Hora',
  IGNORE: 'Ignorar',
  INDEFINITELY: 'Indefinidamente',
  INFORMATION: 'información',
  INVITE: 'Invitar',
  JANUARY: 'Enero',
  JULY: 'Julio',
  JUNE: 'Junio',
  LANGUAGE: 'Idioma',
  LOCATION: 'ubicación',
  MARCH: 'Marzo',
  MAY: 'Mayo',
  MINUTE: 'Minuto',
  MONDAY: 'Lunes',
  MONTH: 'Mes',
  MORE: 'Más',
  MY_ACCOUNT: 'Mi cuenta',
  MY_BILLING: 'Mi facturación',
  NAME: 'Nombre',
  NEXT: 'Siguiente',
  NO: 'No',
  NOTIFICATIONS: 'Notificaciones',
  NOVEMBER: 'Noviembre',
  OCTOBER: 'Octubre',
  OF_PAGINATION: 'De',
  OR: 'o',
  REFUSED: 'Rechazado',
  PASSWORD: 'contraseña',
  PENDING: 'Pendiente',
  PLAN: 'Plan',
  PHONE: 'Teléfono',
  PLEASE_CHECK_YOUR_EMAIL: 'Por favor, verifique su correo electrónico',
  PLEASE_ENTER_YOUR_EMAIL: 'Por favor, introduzca su correo electrónico',
  PLEASE_ENTER_REQUIRED_FIELDS: 'Por favor ingrese los campos requeridos',
  PREVIOUS: 'Anterior',
  SAVE: 'Salvar',
  SATURDAY: 'Sabado',
  SECOND: 'Segundo',
  SELECT_VALUE: 'selecciona un valor',
  SEPTEMBER: 'Septiembre',
  SERVICES: 'Servicios',
  SHARE: 'Compartir',
  SIGN_OUT: 'Desconectar',
  SOUND: 'Sonido',
  START_DATE: 'Date de début',
  SUBMIT: 'Enviar',
  SUNDAY: 'Domingo',
  TIMEZONE: 'Zona horaria',
  THIS_FIELD_IS_REQUIRED: 'Este campo es requerido',
  THIS_FIELD_REQUIRES_AT_LEAST_THREE_CHARACTERS: 'Este campo requiere al menos 3 caracteres',
  THURSDAY: 'Jueves',
  TUESDAY: 'Martes',
  UNDO: 'deshacer',
  VALUE: 'Valor',
  VARIABLE: 'Variable',
  WEDNESDAY: 'Miércoles',
  WEEK: 'Semana',
  YEAR: 'Año',
  YES: 'Sí',
};
