module.exports = {
  ACCEPT: 'Aceptar',
  ACCEPTED: 'Aceptado',
  ACCOUNT: 'cuenta',
  ALL: 'Todos',
  APPLICATION: 'Aplicación',
  APPLICATIONS: 'aplicaciones',
  APRIL: 'Abril',
  ARE_YOU_SURE: '¿Estás seguro',
  AUDIT_LOG: 'Registro de auditoría',
  AUGUST: 'Agosto',
  BACK: 'Regresar',
  BACKGROUND_IMAGE: 'imagen de fondo',
  CANCEL: 'Cancelar',
  CLEAR: 'Limpiar',
  CLICK: 'Hacer clic',
  CLOSE: 'Cerrar',
  COLLAPSE: 'colapsar',
  COMMA: 'Coma',
  COMPANY: 'Empresa',
  CUSTOM: 'Personalizado',
  DATE_FORMAT: 'Formato de fecha',
  DAY: 'Día',
  DASHBOARD: 'Tablero',
  DASHBOARDS: 'Tableros',
  DECEMBER: 'Diciembre',
  DECLINE: 'Desistir',
  DECLINED: 'Declinado',
  DELETE: 'Eliminar',
  DEVELOPER: 'Desarrollador',
  DEVICES: 'Dispositivos',
  DOT: 'Punto',
  EMAIL: 'Correo electrónico',
  END_DATE: 'Fecha final',
  ENTER_EMBED_URL: 'ingrese la URL de inserción',
  ENTER_IMAGE_URL: 'ingrese la url de la imagen',
  ENTER_NAME: 'ingrese el nombre',
  ENTER_EMAIL: 'ingrese la dirección de correo electrónico',
  ENTER_LABEL: 'ingrese la etiqueta',
  ENTER_YOUR_EMAIL: 'Introduce tu correo electrónico',
  EXPAND: 'Expandir',
  FEBRUARY: 'Febrero',
  FILTER: 'filtrar',
  FINISH: 'Finalizar',
  FREE: 'Gratis',
  FRIDAY: 'Viernes',
  FROM: 'Desde',
  GENERAL_INFORMATION: 'Informaciones Generales',
  GO_TO: 'Ir para',
  HERE: 'Aquí',
  HOUR: 'Hora',
  IGNORE: 'Ignorar',
  IMAGE: 'Imagen',
  INDEFINITELY: 'Indefinidamente',
  INFORMATION: 'información',
  INVITE: 'Invitar',
  JANUARY: 'Enero',
  JULY: 'Julio',
  JUNE: 'Junio',
  LANGUAGE: 'Idioma',
  LOCATION: 'ubicación',
  MARCH: 'Marzo',
  MAY: 'Mayo',
  MINUTE: 'Minuto',
  MONDAY: 'Lunes',
  MONTH: 'Mes',
  MORE: 'Más',
  MY_ACCOUNT: 'Mi cuenta',
  MY_BILLING: 'Mi facturación',
  NAME: 'Nombre',
  NEXT: 'Siguiente',
  NO: 'No',
  NO_OPTIONS: 'Sin opciones',
  NOTIFICATIONS: 'Notificaciones',
  NOVEMBER: 'Noviembre',
  OCTOBER: 'Octubre',
  OF_PAGINATION: 'De',
  OR: 'o',
  REFUSED: 'Rechazado',
  PASSWORD: 'contraseña',
  PENDING: 'Pendiente',
  PLAN: 'Plan',
  PHONE: 'Teléfono',
  PLEASE_CHECK_YOUR_EMAIL: 'Por favor, verifique su correo electrónico',
  PLEASE_ENTER_YOUR_EMAIL: 'Por favor, introduzca su correo electrónico',
  PLEASE_ENTER_REQUIRED_FIELDS: 'Por favor ingrese los campos requeridos',
  PREVIOUS: 'Anterior',
  SAVE: 'Salvar',
  SATURDAY: 'Sabado',
  SECOND: 'Segundo',
  SELECT_ALL: 'Seleccionar todo',
  SELECT_FILE: 'Seleccione un archivo',
  SELECT_VALUE: 'selecciona un valor',
  SELECT_IMAGE: 'selecciona una imagen',
  SEPTEMBER: 'Septiembre',
  SERVICES: 'Servicios',
  SHARE: 'Compartir',
  SIGN_OUT: 'Desconectar',
  SOUND: 'Sonido',
  START_DATE: 'Date de début',
  SUBMIT: 'Enviar',
  SUNDAY: 'Domingo',
  TIME_FORMAT: 'Formato de tiempo',
  TIMEZONE: 'Zona horaria',
  THIS_FIELD_IS_REQUIRED: 'Este campo es requerido',
  THIS_FIELD_REQUIRES_AT_LEAST_THREE_CHARACTERS: 'Este campo requiere al menos 3 caracteres',
  THIS_FIELD_REQUIRES_VALID_HTTPS_URL: 'Este campo requiere una URL HTTPS válida',
  THURSDAY: 'Jueves',
  TUESDAY: 'Martes',
  UNDO: 'deshacer',
  VALUE: 'Valor',
  VARIABLE: 'Variable',
  WEDNESDAY: 'Miércoles',
  WEEK: 'Semana',
  YEAR: 'Año',
  YES: 'Sí',
  CONFIGURATION: 'Ajustar',
  DASHBOARDS_SHARE_DASHBOARD: 'Compartir',
  DUPLICATE_DASHBOARD: 'Duplicar',
  BUILD_TEMPLATE: 'Distribuir',
  DASHBOARDS_DELETE_DASHBOARD: 'Eliminar',
  DISMISS: 'Despedir',
  NOT_A_DEVELOPER: '¿No eres un desarrollador?',
  A_DEVELOPER: '¿Eres desarrollador? haga clic aquí',
  NOTIFICATION: 'Notificación',
  SHARE_DASHBOARDS: 'Compartir cuadros de mando',
  WELCOME: 'Hola, qué tal',
  REALTIME: 'Tiempo real',
  CONNECTED: 'Conectado',
  DISCONNECTED: 'Desconectado',
  WELCOME_DEVELOPER: 'Bienvenido desarrollador',
  CHANGE_MY_SETTINGS: 'Cambiar mi configuración',
  EXPLORE: 'Explorar',
  CLICK_HERE: 'haga clic aquí',
  IGNORED: 'Ignorado',
  MAP: 'Mapa',
  SATELLITE: 'Satélite',
  NEW_HERE: '¿Nuevo aquí?',
  ALREADY_HAVE_AN_ACCOUNT: '¿Ya tienes una cuenta?',
  PUBLIC_DASHBOARD: 'Tablero Público',
  UNLIMITED: 'Ilimitado',
  ADD_PROFILES: 'Añadir perfiles',
  USER_MANAGEMENT: 'Gestión de usuarios',
  ACCESS_MANAGEMENT: 'Gestión de Acceso',

  CONFIRM_YOUR_E_MAIL_BEFORE_PROCEEDING: 'Confirme su correo electrónico antes de continuar.',
  ACCOUNT_CREATION_HAS_BEEN_SUBMITTED: 'Se ha enviado la creación de la cuenta.',
  YOUR_ACCOUNT_WAS_CREATED: 'Su cuenta fue creada!',
  YOU_WILL_BE_NOTIFIED_WHEN_IT_IS_ACTIVATED: 'Se le notificará cuando se active.',

  NO_NOTIFICATIONS: 'No notificaciones',
  NO_DASHBOARDS: 'Sin tableros',
  NO_CONTENT: 'Sin contenido',

  MAP_BASIC: 'Mapa Basico',
  MAP_DARK: 'Mapa Oscuro',
  MAP_LIGHT: 'Mapa Luz',
};
