module.exports = {
  RESOURCES_DEVELOPERS: 'Desenvolvedores',
  RESOURCES_DEVELOPERS_SUBTITLE: 'Encontre aqui vários recursos para lhe ajudar a desenvolver sua aplicação com TagoIO',
  RESOURCES_DEVELOPERS_DOCUMENTATION: 'Documentação',
  RESOURCES_DEVELOPERS_DOCUMENTATION_DESCRIPTION: 'Acesse nossa documentação completa - do básico ao avançado.',
  RESOURCES_DEVELOPERS_DOCUMENTATION_LINK1: 'Comece aqui',
  RESOURCES_DEVELOPERS_DOCUMENTATION_LINK2: 'Conceitos',
  RESOURCES_DEVELOPERS_DOCUMENTATION_LINK3: 'Tutoriais',
  RESOURCES_DEVELOPERS_DOCUMENTATION_LINK4: 'MQTT',
  RESOURCES_DEVELOPERS_SDK: 'SDK',
  RESOURCES_DEVELOPERS_SDK_DESCRIPTION: 'Desenvolva mais rapidamente usando nosso SDK para a linguagem que você precisar.',
  RESOURCES_DEVELOPERS_SDK_LINK1: 'NodeJS',
  RESOURCES_DEVELOPERS_SDK_LINK2: 'Java',
  RESOURCES_DEVELOPERS_SDK_LINK3: 'Python',
  RESOURCES_DEVELOPERS_GITHUB: 'Github',
  RESOURCES_DEVELOPERS_DESCRIPTION: 'Acesse nossas bibliotecas disponíveis no Github. Faça o download, customize, e rode os códigos em suas aplicaçoões.',
  RESOURCES_DEVELOPERS_LINK1: 'Repositórios',
  RESOURCES_DEVELOPERS_COMMUNITY: 'Comunidade',
  RESOURCES_DEVELOPERS_COMMUNITY_DESCRIPTION: 'Junte-se a comunidade TagoIO no Slack e ganhe acesso aos experts, incluindo nossos desenvolvedores.',
  RESOURCES_DEVELOPERS_COMMUNITY_LINK1: 'Slack',
  RESOURCES_DEVELOPERS_CHANGELOG: 'Changelog',
  RESOURCES_DEVELOPERS_CHANGELOG_DESCRIPTION: 'Não perca o histórico de lançamento das mais recentes versões do nosso back-end e front-end.',
  RESOURCES_DEVELOPERS_CHANGELOG_LINK1: 'Back-end Changelog',
  RESOURCES_DEVELOPERS_CHANGELOG_LINK2: 'Front-end Changelog',
  RESOURCES_DEVELOPERS_SYSTEM_STATUS: 'Status Operacional do Sistema',
  RESOURCES_DEVELOPERS_SYSTEM_STATUS_DESCRIPTION: 'Acompanhe o status de todos os serviços da TagoIO em tempo-real. Os relatórios incluem uptime e o tempo de resposta para os métodos GET e POST.',
  RESOURCES_DEVELOPERS_SYSTEM_STATUS_LINK1: 'Relatório de Status',
  RESOURCES_DEVELOPERS_DOWNLOADS: 'Download',
  RESOURCES_DEVELOPERS_DOWNLOADS_DESCRIPTION: 'Acelere sua curva de aprendizado usando nosso guia de lançamento e de boas práticas.',
  RESOURCES_DEVELOPERS_DOWNLOADS_LINK1: 'Guia de lançamento',
  RESOURCES_DEVELOPERS_DOWNLOADS_LINK2: 'Melhores práticas para Painéis',
  RESOURCES_DEVELOPERS_DOWNLOADS_LINK3: 'Melhores práticas para Análises',
  RESOURCES_PARTNERS: 'Nossos Parceiros',
  RESOURCES_PARTNERS_DESCRIPTION: 'Nossos parceiros trazem os melhores hardware, firmware, aplicaçoões, e experiência em conectividade para ajudar no desenvolvimento da sua solução usando a plataforma TagoIO',
  RESOURCES_VIDEOS_TITLE: 'Vídeos',
  RESOURCES_VIDEOS_SUBTITLE: 'Assista nossos vídeos que explicam como você pode construir e publicar soluções IoT para o seu negócio',
  RESOURCES_VIDEOS_SEARCH: 'Pesquise exemplos, recursos, tutorials ...',
  RESOURCES_VIDEOS_NEXT_PAGE: 'Próxima página',
  RESOURCES_VIDEOS_PREVIOUS_PAGE: 'Página anterior',
  RESOURCES_VIDEOS_SUBSCRIBE: 'Inscreva-se',
  RESOURCES_FAQ: '\'FAQ\' - Perguntas Frequentes',
  RESOURCES_FAQ_DESCRIPTION: 'Se você ainda tiver mais dúvidas, estas FAQs poderão ajudar',
  RESOURCES_FAQ_QUESTION1: 'Quais são os navegadores que o Admin da TagoIO pode rodar?',
  RESOURCES_FAQ_ANSWER1: 'O Admin da TagoIO é otimizado para Chrome (última versão), Firefox (última versão), Safari (última versão), Edge, e com algumas limitações, para o Internet Explorer 11. A TagoIO roda também nos navegadores de celulares Chrome para Android (última versão), e Safari para iOS (última versão).',
  RESOURCES_FAQ_QUESTION2: 'Onde os meus dados são armazenados?',
  RESOURCES_FAQ_ANSWER2: 'O banco de dados da TagoIO é localizado em servidores nos Estados Unidos.' +
    ' Nós estamos planejando adicionar servidores em outras regiões em breve (Europa, Japão, Brasil...), ' + 
    ' para que usuários mantenham todos os dados na sua própria região. É importante lembrar que usuários podem ' + 
    ' baixar todos os dados para seus próprios servidores e definir um período de retenção para configurar por ' + 
    ' quanto tempo os dados devem ser mantidos na TagoIO.',
  RESOURCES_FAQ_QUESTION3: 'Como os meus clientes podem ter acesso as aplicações que eu desenvolver?',
  RESOURCES_FAQ_ANSWER3: 'Você pode compartilhar manualmente, ou liberar a sua aplicação no \'Explore\' da TagoIO. Além disto, existe a versão \'Whitelabel\' que separa todos os usuários para serem visualizados somente por sua empresa, de modo que você terá controle e visão total sabendo quem acessa o que na sua aplicação.',
  RESOURCES_FAQ_QUESTION4: 'Quais são as linguages disponíveis para o Admin da TagoIO?',
  RESOURCES_FAQ_ANSWER4: 'A versão Desenvolvedor do Admin da TagoIO está totalmente em Ingles. Já a versão para usuário final (Modo reduzido) está disponível em Português, Ingles, Espanhol e Frances.',
  RESOURCES_FAQ_QUESTION5: 'Existe uma versão da TagoIO que possa ser instalada em meus próprios servidores?',
  RESOURCES_FAQ_ANSWER5: 'A TagoIO roda em servidores na nuvem para obter a melhor garantia de redundância, tempo de acesso, qualidade de serviços e menor custo. No momento, ainda não oferecemos uma versão para instalação \'on-premises\'',
  RESOURCES_FAQ_QUESTION6: 'A TagoIO está certificada para os padrões HIPAA ou FedRAMP?',
  RESOURCES_FAQ_ANSWER6: 'Nosso planejamento inclue a certificação para HIPPA (Health Insurance Portability and Accountability Act of 1996) e FedRAMP (Federal Risk and Authorization Management Program ). Entre em contato se sua empresa precisar desta ou de qualquer outra certificação.',
  DEVELOPERS_DESCRIPTION: 'Nossa área de conhecimento contém recursos valiosos para você desenvolver rapidamente soluções de IoT usando as ferramentas TagoIO.',
};
