module.exports = {
  COMMUM_NEXT: 'Next',

  WELCOME_GET_STARTED: 'Get Started',
  WELCOME_CONNECT_DEVICE: 'Connect your device',
  WELCOME_CONNECT_DEVICE_DESC: 'Connect any device that we already built a driver for. Follow our guidelines to connect your own device easily.',
  WELCOME_BUILD_APP: 'Build your application',
  WELCOME_BUILD_APP_DESC: 'Combine data from different types of devices inside your own application. Access your account at www.tago.io and start to build now.​',
  WELCOME_SHARE_ANY: 'Share with anyone',
  WELCOME_SHARE_ANY_DESC: 'Share your dashboards with anyone by using private or public options. Others will receive updates in real-time.​',

  LOGIN_EMAIL: 'E-mail address',
  LOGIN_PASSWORD: 'Password',
  LOGIN_BTN_SIGNIN: 'Sign in',
  LOGIN_BTN_SIGNUP: 'Create an Account',

  SECTION_DASHBOARD: 'Dashboards',
  SECTION_EXPLORE: 'Explore',
  SECTION_NOTIFICATION: 'Notifications',
  SECTION_SETTINGS: 'Settings',

  SETTINGS_TOUCHID: 'Enable TouchID',
  SETTINGS_NOTIFICATIONS: 'Notifications',
  SETTINGS_FULLSCREEN: 'Fullscreen on landscape',
  SETTINGS_KEEPAWAKE: 'Keep Awake',
  SETTINGS_LOGOUT: 'Logout',
  SETTINGS_VERSION: 'Version:',

  NOTIFICATIONS_ACCEPTED: 'Accepted',
  NOTIFICATIONS_DECLINED: 'Declined',
  NOTIFICATIONS_ACCEPT: 'Accept',
  NOTIFICATIONS_DECLINE: 'Decline',
  NOTIFICATIONS_IGNORE: 'Ignore',
  NOTIFICATIONS_GOTODASH: 'Go to dashboard',
  NOTIFICATIONS_APPSETTINGS: 'Application settings',
  NOTIFICATIONS_NEWUSERREGISTERED: 'New user registered',
  NOTIFICATIONS_NEWUSERREGISTERED_DESC: '$0$ just created an account on Tago. The item you shared is available for him to accept',
  NOTIFICATIONS_SHAREPROFILE: 'Sharing profile',
  NOTIFICATIONS_SHAREPROFILE_DESC: '$0$ wishes to share the profile with you',
  NOTIFICATIONS_SHAREREQUEST_DASH: 'Sharing request - Dashboard',
  NOTIFICATIONS_SHAREREQUEST_DASH_DESC: '$0$ wishes to share dashboard $1$ with you',
  NOTIFICATIONS_SHAREREQUEST_BUCKET: 'Sharing request - Bucket',
  NOTIFICATIONS_SHAREREQUEST_BUCKET_DESC: '${notification.ref_from.name} wishes to share bucket ${notification.ref_id.name} with you',

  EXPLORER_SHOWALL: 'Show All',
  EXPLORER_TRANSPORTATION: 'Transportation',
  EXPLORER_HOME: 'Home',
  EXPLORER_AGRICULTURE: 'Agriculture',
  EXPLORER_ENERGY: 'Energy',
  EXPLORER_INDUSTRIAL: 'Industrial',
  EXPLORER_ALREADYADDED: 'Already added',
  EXPLORER_BY: 'By',
  EXPLORER_FILTERCATEGORY: 'Filter by Category',
  EXPLORER_SEARCHFORMODEL: 'Search for model, brand or application...',
  EXPLORER_CANCEL: 'Cancel',
  EPLORER_COMPATIBLE: 'Compatible Devices:',
  EXPLORER_HOWTOALERT: 'How to Install',
  EXPLORER_HOWTOINSTALL: 'How to install this application?',
  EXPLORER_ADDAPPLI: 'Add application',
  EXPLORER_CONFIGURE: 'Configure',
  EXPLORER_DOWANTCONT: 'Do you want to continue?',
  EXPLORER_THISACTIONWILL: 'This action will add it to your dashboard list.',
  EXPLORER_NO: 'No',
  EXPLORER_YES: 'Yes',
  EXPLORER_ENTERPIN: 'This requires a PIN code. Enter the code provided by the creator.',
  EXPLORER_ENTERCODE: 'Enter required code...',
  EXPLORER_ADD: 'Add',
  EXPLORER_OOPS: 'Oops, something was wrong',
  EXPLORER_BACK: 'Back',
  EXPLORER_DONE: 'Done!',
  EXPLORER_YOUWILLRECEIVE: "You'll receive a notification when it is available on your account.Don't worry it will take only a few seconds.",
  EXPLORER_BACKTOEXPLORE: 'Back to Explore',
  EXPLORER_LOADING: 'We are working on it...',

  DASHBOARD_SHARE_ONEHOUR: 'Share for One Hour',
  DASHBOARD_SHARE_ENDDAY: 'Share Until End of Day',
  DASHBOARD_SHARE_INDEF: 'Share Indefinitely',
  DASHBOARD_SHARE_CANCEL: 'Cancel',
  DASHBOARD_SHARE_EMAIL: 'Enter user e-mail',
  DASHBOARD_SHARE_INVITE: 'Invite',
  DASHBOARD_SHARE_ALLOWOTHERS: 'Allow the user to share with others?',
  DASHBOARD_SHARE_NO: 'No',
  DASHBOARD_SHARE_YES: 'Yes',
  DASHBOARD_SHARE_INVEMAIL: 'Invalid email structure',
  DASHBOARD_SHARE_TRYA: 'Try again',
  DASHBOARD_SHARE_YOUSHARE: 'You shared a dashboard with an expiration date that is greater than the expiration date of the share that was made for you. The share for:',
  DASHBOARD_SHARE_WILLEXP: 'will expire at: $0$',
  DASHBOARD_SHARE_OK: 'OK',
  DASHBOARD_SHARE_SHARESUCESS: 'Share successfull',
  DASHBOARD_SHARE_FAIL: 'Share failed',
  DASHBOARD_SHARE_USERINVITED: 'The user has been invited to access this dashboard.',
  DASHBOARD_SHARE_NOTALLOWED: 'You don’t have rights to share this dashboard. Ask $0$ to send it again with authorization for you to share with others',
  DASHBOARD_SHARE_SHAREDASH: 'Share this dashboard in real-time privately',
};
