module.exports = {
  ACCOUNT_SETTINGS: 'Configurações da conta',
  ACCOUNT_TYPE: 'Tipo de conta',
  ALL_OTHER_EVENTS: 'Todos os outros eventos',
  ARE_YOU_SURE_YOU_WANT_CHANGE_YOUR_ACCOUNT: 'Tem certeza que deseja mudar sua conta para',
  CHANGE_YOUR_PASSWORD: 'Mudar sua senha',
  CONFIRM_PASSWORD: 'Confirmar senha',
  CONFIRM_YOUR_PASSWORD: 'confirme sua senha',
  DEVELOPER_FULL_VIEW: 'Desenvolvedor (visualização completa com todas as ferramentas disponíveis)',
  ENTER_YOUR_NAME: 'entre com seu nome',
  ENTER_YOUR_PASSWORD: 'entre com sua senha',
  ENTER_YOUR_PHONE_NUMBER: 'entre com seu número de telefone',
  FINAL_USER: 'Usuário Final',
  HIDE_TOUR: "Esconder botão 'Tour'",
  I_AM_USER_FINAL_USER: 'Eu sou um',
  I_AM_DEVELOPER: 'Eu sou um',
  I_WILL_BUILD_APPLICATIONS_TAGO: 'Eu irei construir aplicações na Tago',
  I_WILL_ONLY_USE_APPLICATIONS: 'Eu irei somente usar aplicações da Tago',
  MIDDLEWARE: 'Middleware',
  NEW_PASSWORD: 'Nova senha',
  RECEIVE_NEWSLATTER: 'Receber noticias',
  SAFARI_IE_NOT_SUPPORT_BROWSER_NOTIFICATION_SOUND: 'Safari e IE não suportam notificações e som nativo do navegador',
  SHOW_NOTIFICATION_FROM: 'Exibir notificações vindas de',
  SHOW_LAST_UPDATE_AT: 'Mostrar a última atualização em',
  USAGE_STATISTICS: 'Estatística de Uso',
  USER_ONLY: 'Usuário final',
  USER_REDUCE_VIEW: 'Usuário (visualização reduzida)',
  USERS_MANAGEMENT: 'Gerenciamento de Usuários',
  TOKENS: 'Tokens',
  VIEW_MODE: 'Modo visualização do admin',
  VISUALIZATION_PREFERENCES: 'Preferências de Visualização',
  WE_OCCASIONALLY_SEND_NEWSLETTERS_WITH_RELEVANT_TOPICS: 'Enviamos ocasionalmente noticias com tópicos relevantes',
  WIDGET_MENU: 'Menu do widget',
  WIDGET_FOOTER: 'Rodapé do widget',
  YOU_NEED_ENTER_SAME_PASSWORD_TWICE: 'Senhas não podem ser diferentes',
};
